### ISSUE TITLE
Error from stripe __init__.py where file is unable to import name 'six' from 'stripe'

### ISSUE THREAD

**Issue by jjuncho** [stripe/stripe-python#1021]
### Describe the bug

When attempting to run my stripe integrated project in local, I am erroring out with the message: cannot import name 'six' from 'stripe' (/Users.../project_name/lib/python3.8/site-packages/stripe/__int__.py)

### To Reproduce

Using stripe package version 3.0.0 in pipfile; tried to use the most up to date version by putting in stripe: "*" but still get the same error message

### Expected behavior

We expect the stripe library to initialize properly 

### Code snippets

```Python
Unable to post code snippets due to non-open source enterprise code being used
```

### OS

macOS

### Language version

python 3.8

### Library version

stripe v3.0.0

### API version

NA

### Additional context

Our team was previously in contact with the stripe-apps-ecosystem-team, not sure if we should continue communications via email

**Comment by anniel-stripe** [comment]
You might have a local cache of the old version of the library. Can you run `pip uninstall stripe` and `pip install stripe`?

**Comment by jjuncho** [comment]
So I just noticed that we were using the six library from stripe which is no longer included with the most recent version. Thank you!
