### ISSUE TITLE
Creating a session with blank customer does not create a new one

### ISSUE THREAD

**Issue by jmortezz** [stripe/stripe-python#1022]
### Describe the bug

I noticed this using the python library, and it didn't happen before release 6.0.0, when creating a Checkout Session without providing the Customer ID, the documentation says [here](https://stripe.com/docs/api/checkout/sessions/create?lang=python#create_checkout_session-customer)

> If blank for Checkout Sessions in payment or subscription mode, Checkout will create a new Customer object based on information provided during the payment flow.

However, when I retrieve the Checkout Session after a successful payment, the Customer ID is null. 

### To Reproduce

1. Create a Checkout Session without Customer ID
2. Retrieve that Session at the success endpoint
3. The customer id is null

### Expected behavior

A new Customer Object should have been created as it was done in previous releases

### Code snippets

```Python
# Creating the checkout session
session = stripe.checkout.Session.create(
        line_items=items,
        payment_method_types=['card'],
        allow_promotion_codes=True,
        tax_id_collection={'enabled': True},
        phone_number_collection={'enabled': True},
        metadata=metadata,
        mode='payment',
        success_url=success_url,
        cancel_url=referer,
    )
```

```Python
# At the success endpoint
checkout_session = stripe.checkout.Session.retrieve(session_id)
checkout_session['customer'] # This is null !
```

### OS

Linux

### Language version

Python 3.9

### Library version

6.0.0

### API version

2023-08-16

**Comment by remi-stripe** [comment]
@remi-stripe the new major version of stripe-python will use the latest API version by default which we documented in the [changelog](https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#600---2023-08-16) and the [migration guide](https://github.com/stripe/stripe-python/wiki/Migration-guide-for-v6).

The default behaviour of `customer_creation` on Checkout changed from `always` to `if_required` back in a previous API version: [2022-08-01](https://stripe.com/docs/upgrades#2022-08-01).

If your code is not properly pinning, or is explicitly using that latest API version, then it's expected that the `customer_creation` will default to `if_required` and not create one by default.

I agree the docstring in the API Reference is not the clearest and we're working on updating it. But if you want a real Customer each time you need to explicitly pass `customer_creation="required"`
