### ISSUE TITLE
5.5.0b5 has refund issue

### ISSUE THREAD

**Issue by zidaneymar** [stripe/stripe-python#1027]
### Describe the bug

After we upgrade the stripe python SDK from 5.4.0 to 5.5.0b5, we meet an issue which will block the refund.

We use this code snippet to request a refund in 5.4.0:
```
charge = stripe.Charge.retrieve(self._get_transaction_id(credit))
if charge.refunded:
  return AlreadyRefundedStatus()
else:
  charge.refunds.create(metadata={"reason": reason})
```
  
But this is not working in 5.5.0b5, it returns 
`KeyError 'refunds'` in this line `charge.refunds.create(metadata={"reason": reason})`

### To Reproduce

1. Issue a refund using 5.5.0b5
2. Pops up en exception `KeyError 'refunds'` in this line `charge.refunds.create(metadata={"reason": reason})`

### Expected behavior

Upgrading the minor version won't change the API schema

### Code snippets
See issue description
_No response_

### OS

macOS

### Language version

Python 3.9.7

### Library version

stripe-python 5.5.0b5

### API version

2015-01-26;specify_payment_method_config_beta=v1

**Comment by remi-stripe** [comment]
@zidaneymar the `5.5.0b5` version is a **beta** version that works completely differently from the "main trunk". That beta SDK will pin the API version to the latest API version which includes changes from last year to remove the `refunds` property on Charge documented in the API version [2022-11-15](https://stripe.com/docs/upgrades#2022-11-15)

You likely were trying to upgrade to `5.5.0` instead which is in the changelog [here](https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#550---2023-07-13) and wouldn't have that issue.

Note that if you upgrade to the most recent version (6.1.0), this is a new major version and that version will also pin to the latest API version and lack that property. See the migration guide [here](https://github.com/stripe/stripe-python/wiki/Migration-guide-for-v6)

It's also important to note that the stripe-python library has had a top-level resource for Refunds for a few years now. You can instead use `stripe.Refund.create(charge="ch_123')` to create a Refund as documented in our API Reference [here](https://stripe.com/docs/api/refunds/create?lang=python)

Hope this helps overall but the

**Comment by zidaneymar** [comment]
Thanks for the help @remi-stripe , can I use `stripe.Refund.create(charge="ch_123')` in `5.5.0b5` as well?

**Comment by remi-stripe** [comment]
Yep it should work the same in that case!
