### ISSUE TITLE
"ResourceWarning: unclosed <ssl.SSLSocket" 

### ISSUE THREAD

**Issue by johnmee** [stripe/stripe-python#104]
I'm getting ResourceWarnings when using the API for basic listings:

        import stripe
        stripe.api_key = api_key
        response = stripe.Plan.all()
        response = stripe.Customer.all()

    (subscribers)Johns-iMac:src john$ python test.py StripeAuthTestCase
    /Users/john/Code/lib/python3.4/site-packages/stripe/resource.py:99: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('192.168.0.5', 58604), raddr=('50.18.212.223', 443)>
      instance = cls(values.get('id'), api_key)

    /Users/john/Code/subscribers/lib/python3.4/site-packages/stripe/resource.py:48: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('192.168.0.5', 58417), raddr=('50.18.212.223', 443)>
      return super(StripeObject, self).__setattr__(k, v)

    Python 3.4.1 (default, May 19 2014, 13:10:29)
    [GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
    >>> stripe.VERSION
    '1.19.0'

Easy enough to quash by commenting out the `import warnings` in resource.py but an annoyance if you're the type to heed the warnings.

**Comment by kyleconroy** [comment]
Apologies for the late response :crying_cat_face:. Are you still seeing this problem? If so, have you tried updating to the most recent version of stripe-python (and requests)?

**Comment by johnmee** [comment]
Apologies also as I'm unable to follow through (no longer using this library).
