### ISSUE TITLE
Inquiring about Issues related to Hacktoberfest

### ISSUE THREAD

**Issue by JaynouOliver** [stripe/stripe-python#1081]
### Is your feature request related to a problem? Please describe.

Hello, I would like to kindly request the addition of a tag specifically for issues related to Hacktoberfest. This tag would be immensely helpful for us contributors when working on such issues.

**Comment by pakrym-stripe** [comment]
Hi @JaynouOliver! Thank you for your inquiry, the team will take a stock of issues and mark appropriate ones.

**Comment by pakrym-stripe** [comment]
I'm sorry @JaynouOliver, we took stock of open issues in SDK and didn't find much that was approachable for a first time contributor. Most of the issues either require substantial design or changes to the code generator that's not open-source at the moment. 

We hope to open-source the generator in the future which will open a lot more opportunities for contributions.
