### ISSUE TITLE
`subscription_data.description` field not working on checkout session creation

### ISSUE THREAD

**Issue by putnokiabel** [stripe/stripe-python#1111]
### Describe the bug

I'm trying to create a checkout session, and display a custom text to the user for more context during the checkout session (as well as in the portal).

When creating a checkout session, I'm passing the `subscription_data.description` parameter, which according to the documentation is meant exactly for this purpose.

However, the checkout session is still showing the default description of the subscription (set in the Stripe dashboard), and not the custom description that I passed when creating a checkout session.

### To Reproduce

1. Create a checkout session, and set `subscription_data.description` to a custom string.
2. Go to the URL of the created checkout session.

### Expected behavior

The checkout session shows the default description of the subscription, not the custom text that I set `subscription_data.description` to:
![image](https://github.com/stripe/stripe-python/assets/29568469/c7e1a6d0-d08a-402a-a389-b2b240faaae9)

### Code snippets

```Python
checkout_session = stripe.checkout.Session.create(
            success_url=success_url,
            cancel_url=cancel_url,
            mode='subscription',
            line_items=[
                {
                    'price': priceId,
                    'quantity': quantity,
                }
            ],
            customer=customer,
            subscription_data={
                'metadata': {
                    'users': users,
                    'code': code
                },
                'description': 'custom description!!!'
            },
            discounts=discounts
        )

        return jsonify({
            'sessionId': checkout_session['id'],
            'url': checkout_session['url']
        })
```

### OS

macOS

### Language version

Python 3.9

### Library version

stripe-python version 7.1.0

### API version

2023-10-16

### Additional context

I see that the data does arrive at the Stripe server correctly via the dashboard. However, the supplied `subscription_data.description` has no effect at all.
![image](https://github.com/stripe/stripe-python/assets/29568469/96b4a6db-200c-4ea7-90a2-29746a4fbeef)

**Comment by putnokiabel** [comment]
Note that a similar issue was found (and fixed) in stripe-node: https://github.com/stripe/stripe-node/issues/1418

**Comment by remi-stripe** [comment]
@putnokiabel This isn't a bug with the SDK itself. It's a feature request of our API instead which should be directed to our support team: <https://support.stripe.com/contact>. For now that parameter is used in the Customer Portal for when a Customer edits their Subscription in the future, it does not appear in Checkout and we don't have plans to make it appear for now.
