### ISSUE TITLE
Method signatures not interpreted correctly by mypy

### ISSUE THREAD

**Issue by samueljsb** [stripe/stripe-python#1113]
### Describe the bug

Now that the library exports type annotations, mypy is reporting errors in code that appears to be correct. In particular, many methods appear to require (according to mypy) the instance or class to be passed in as the first argument, which is not correct.

### To Reproduce

in `t.py`:

```python
import stripe

def f(payment_method: str, customer: str) -> None:
    stripe.PaymentMethod.attach(payment_method, customer=customer)

def g(payment_method: str) -> None:
    stripe.PaymentMethod.detach(payment_method)
```

```console
$ mypy t.py
t.py:4: error: No overload variant of "attach" of "PaymentMethod" matches argument types "str", "str"  [call-overload]
t.py:4: note: Possible overload variants:
t.py:4: note:     def attach(cls, cls: type[PaymentMethod], payment_method: str, api_key: str | None = ..., stripe_version: str | None = ..., stripe_account: str | None = ..., **params: Any) -> PaymentMethod
t.py:4: note:     def attach(self, self: PaymentMethod, idempotency_key: str | None = ..., **params: Any) -> PaymentMethod
t.py:7: error: No overload variant of "detach" of "PaymentMethod" matches argument type "str"  [call-overload]
t.py:7: note: Possible overload variants:
t.py:7: note:     def detach(cls, cls: type[PaymentMethod], payment_method: str, api_key: str | None = ..., stripe_version: str | None = ..., stripe_account: str | None = ..., **params: Any) -> PaymentMethod
t.py:7: note:     def detach(self, self: PaymentMethod, idempotency_key: str | None = ..., **params: Any) -> PaymentMethod
Found 2 errors in 1 file (checked 1 source file)
```

(observed with mypy 0.991 and 1.6.1)

### Expected behavior

No type checking errors.

I would also expect the function signature to only have one `cls` or `self` argument, rather than the two that mypy seems to think it has.

### OS

macOS

### Language version

observed on 3.10.11 and 3.11.5

### Library version

7.1.0

### API version

N/A

**Comment by richardm-stripe** [comment]
Hello @samueljsb. Thanks for the report. I am able to reproduce and am trying to figure out a fix.

**Comment by richardm-stripe** [comment]
Oops, release pending

**Comment by richardm-stripe** [comment]
Released in https://github.com/stripe/stripe-python/releases/tag/v7.2.0

**Comment by richardm-stripe** [comment]
Thank you @samueljsb for being a patient/quick adopter of the type annotations, writing a detailed report, and helping to make the library better for everyone!

**Comment by samueljsb** [comment]
Thank you for responding and getting an update out so quickly!
