### ISSUE TITLE
`ErrorObject` attributes are not visible to mypy

### ISSUE THREAD

**Issue by samueljsb** [stripe/stripe-python#1114]
### Describe the bug

Since type annotations have been exported, many errors are now being reported for missing attributes on `ErrorObject` instances.

### To Reproduce

in `t.py`:

```python
import stripe

def f() -> None:
    try:
        stripe.PaymentIntent.create()
    except stripe.error.InvalidRequestError as e:
        error = e.construct_error_object()
        assert error is not None  # not relevant to this issue
        print(error.code)
```

```console
$ mypy t.py
t.py:9: error: "ErrorObject" has no attribute "code"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

### Expected behavior

No type checking errors.

### OS

macOS

### Language version

observed on 3.10.11 and 3.11.5

### Library version

7.1.0

### API version

N/A

**Comment by richardm-stripe** [comment]
Released in https://github.com/stripe/stripe-python/releases/tag/v7.2.0
