### ISSUE TITLE
Document bank account creation with a Recipient

### ISSUE THREAD

**Issue by kevinburke** [stripe/stripe-python#122]
The Recipient code snippet doesn't show how to pass a bank account to Stripe. 

https://stripe.com/docs/api/python#create_recipient

I tried grepping the source code for `bank_account`, `routing_number` and `account_number` and came up similarly empty.

**Comment by kevinburke** [comment]
I also tried

```
rp = stripe.Recipient.create(
    name="Kevin Burke",
    type="individual",
    bank_account={
        'account_number': 'xxx',
        'routing_number': 'yyy',
    },
)
```

and got the incomprehensible error message 

```
  File ".../stripe/api_requestor.py", line 129, in request
    resp = self.interpret_response(rbody, rcode)
  File ".../stripe/api_requestor.py", line 249, in interpret_response
    self.handle_api_error(rbody, rcode, resp)
  File ".../stripe/api_requestor.py", line 143, in handle_api_error
    err.get('message'), err.get('param'), rbody, rcode, resp)
InvalidRequestError: Invalid string:
```

**Comment by kevinburke** [comment]
<img src="https://api.monosnap.com/image/download?id=dPTkImiwWMFLqfVtGmOlSpj1lYEwmK" />

Too typed for Python, switching to Go.

**Comment by kyleconroy** [comment]
![](https://golang.org/doc/gopher/appenginegophercolor.jpg)

**Comment by kyleconroy** [comment]
@kevinburke To create a bank account on a recipient, you can either use two forms:

```python
rp = stripe.Recipient.create(
    name="Kevin Burke",
    type="individual",
    bank_account={
        'account_number': 'xxx',
        'country': 'US',
        'routing_number': 'yyy',
    },
)
```

or 

```python
rp = stripe.Recipient.create(
    name="Kevin Burke",
    type="individual",
    bank_account='tok_123123', # provided by Stripe.js
)
```

Your request is failing because you're missing the required `country` parameter. You would have known that if the error message we returned wasn't so strange. I'm going to look into fixing that.
