### ISSUE TITLE
Official Python docs out of date

### ISSUE THREAD

**Issue by alanhamlett** [stripe/stripe-python#1221]
### Describe the bug

https://stripe.com/docs/api/invoices/retrieve?lang=python

The example code doesn't work with latest version.

### To Reproduce

Run it.

### Expected behavior

Should use new StripeClient.

### OS

Python

### Language version

any

### Library version

stripe-python v8.1.0

### API version

2024

**Comment by remi-stripe** [comment]
@alanhamlett I tried that exact code on that exact version and it works as expected locally for me. You didn't give any details about the exact code you are using beyond that line or what exact error you get or the exact Python version (you said any) so it's tough to help further. But I'm fairly confident this is a bug in your implementation right now at least

**Comment by alanhamlett** [comment]
I don't get any exception, just thought using `stripe.api_key = ...` is being replaced with `StripeClient`?

**Comment by remi-stripe** [comment]
The `StripeClient` is a new approach but the old way works (and will likely work for a long time). We definitely to start using the new way if you are willing as it's cleaner but it's fine to keep your code as is. See [those docs](https://github.com/stripe/stripe-python/wiki/Migration-guide-for-v8-(StripeClient)) for more details on the migration.
