### ISSUE TITLE
Creating a plan with an invalid value for 'interval' raises an inaccurate exception

### ISSUE THREAD

**Issue by blubber** [stripe/stripe-python#123]
Trying to create a plan with a value for 'interval' that is invalid (in this case 'daily') raises an exception that is inaccurate:

    stripe.error.InvalidRequestError: Invalid interval: must be one of month, week, or year

Only 'month', 'week' and 'year'  are listed, but the attributed also accepts 'day'.

**Comment by kyleconroy** [comment]
Thanks for the heads up! I've added `day` to the list of intervals in said error message.
