### ISSUE TITLE
Documentation around refund_application_fee unclear

### ISSUE THREAD

**Issue by melinath** [stripe/stripe-python#124]
I have an application that charges a fee on transactions. I can use that application to fetch (and I believe refund) charges during the operation of my application. But if I add refund_application_fee=True to my call, I get the following error:

```
InvalidRequestError: Only an application generating a fee can call refund_application_fee on <charge_id>
```

This is because I need to use the access token associated with the connected account, NOT my application's token. This was unclear to me from the docs and from this error message.

My application *is* in a certain sense "generating" the fee. I'm the cause of it. What I need to do is run the call as the *owner of the charge*. Now that I know that, it totally makes sense, but it was very confusing for a while.

**Comment by melinath** [comment]
Actually, I may still be missing something. This isn't erroring any more, but it doesn't seem to be refunding the application fee.

**Comment by melinath** [comment]
Okay... it *is* refunding the application fee, but that isn't actually reported as part of the Refund's attached fees.

**Comment by kyleconroy** [comment]
@melinath sorry for the confusion here. I've open an internal issue to make our documentation a little bit clear on exactly how application fees are refunded.
