### ISSUE TITLE
Incorrect annotation on `ErrorOrbject.code`

### ISSUE THREAD

**Issue by samueljsb** [stripe/stripe-python#1249]
### Describe the bug

[This attributed](https://github.com/stripe/stripe-python/blob/58feb242636969f0aca32fa2f090dd18c6852191/stripe/_error_object.py#L16) is annotated as `int`, but the [API documentation ](https://docs.stripe.com/api/errors?lang=python#errors-code) indicates that this should be a nullable string (i.e. `Optional[str]`

### To Reproduce

This can be seen in the source code.

### Expected behavior

This attribute should be annotated as a nullable string.

### OS

macOS

### Language version

Python 3.10

### Library version

v8.4.0

### API version

N/A

**Comment by anniel-stripe** [comment]
Hi @samueljsb, thanks for the bug report! I've updated the type in https://github.com/stripe/stripe-python/pull/1250, and this change will go out in next week's release.

**Comment by samueljsb** [comment]
Wonderful, thank you!
