### ISSUE TITLE
`HTTPXClient` `allow_sync_requests` != `allow_sync_methods`

### ISSUE THREAD

**Issue by CallumAtCarter** [stripe/stripe-python#1298]
### Describe the bug

The README refers to `allow_sync_requests`, but `HTTPXClient` only uses `allow_sync_methods`.

### To Reproduce

.

### Expected behavior

.

### OS

.

### Language version

.

### Library version

.

### API version

.

**Comment by richardm-stripe** [comment]
Thanks for the report! Will have the README.md fixed right away.
