### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [stripe/stripe-python#1341]
### Is your feature request related to a problem? Please describe.

My name is McKenna Dallmeyer and I would like to submit stripe-python to OSS-Fuzz.

If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software.

In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you!

**Comment by prathmesh-stripe** [comment]
Thanks for bringing this to our attention. We'll evaluate if fuzzing this repo makes sense for us. If we decide it does, we will submit the information ourselves. Thank you!
