### ISSUE TITLE
Inconsistent syntax in API docs example for card creation

### ISSUE THREAD

**Issue by naoyak** [stripe/stripe-python#138]
From https://stripe.com/docs/api/python#create_card :

> Definition
`customer = stripe.Customer.retrieve({CUSTOMER_ID})`
`customer.sources.create(source={TOKEN_ID})`

> Example Request
`import stripe`
`stripe.api_key = "xxxxxxxxxxxxxxx"`
`customer = stripe.Customer.retrieve("xxxxxxxxxxxxxxx")`
`customer.sources.create(card="xxxxxxxxxxxxxxx")`

Seems like the former syntax (using `source` as the param name rather than `card`) would be correct for the current API version.

**Comment by kyleconroy** [comment]
@naoyak Yep, that's most certainly a bug. The `source` syntax is correct (Note that the `card` syntax continues to work, but has been deprecated).

**Comment by naoyak** [comment]
Looks like this has been corrected in the docs. :+1:
