### ISSUE TITLE
API Calls fail under Python 2.7.9

### ISSUE THREAD

**Issue by pg1671** [stripe/stripe-python#143]
When using python 2.7.9 (with the backported 3.4 SSL updates) API calls fail with the message:

stripe.error.APIConnectionError: Unexpected error communicating with Stripe. It looks like there's
probably a configuration issue locally.  If this problem persists, let
us know at support@stripe.com.

(Network error: A ValueError was raised with error message empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED)

requests 2.6.2   stripe 1.22.2

**Comment by kyleconroy** [comment]
So sorry for the late response! 

This appears to be a configuration issue with your local installation of OpenSSL. Have you attempted to upgrade to the most recent version of OpenSSL?
