### ISSUE TITLE
Cannot set Additional Owner's field through API

### ISSUE THREAD

**Issue by djhohnstein** [stripe/stripe-python#145]
I'm currently in the process of migrating to Stripe and I've run into some issues with the Account creation process.

I have a marketplace application where users can sell to other users, in which I create charges and transfers to different user's Stripe accounts. 

Some of these accounts should be able to be Corporate accounts. When they go to fill out the information for their Corporate account however, one of the fields they need to submit is additional owners. When they submit their information to my server, and the server ships the information off to Stripe, Stripe incorrectly interprets the additional_owners attribute of the account's legal_entity as a list of strings instead of a list of dictionaries. Below is a pastebin of a few attempts to show the problem:

Setting the legal_entity hash all at once:
http://pastebin.com/8FtUHucw
Stripe's interpretation:
http://imgur.com/oZ5lG2B

Setting the additional_owners manually:
http://pastebin.com/ryG7A49m

In IRC I was told to report this as a bug by @rfunduk. If you could give me any insight as to why this is happening, that'd be great.

Cheers,
Dwight

**Comment by kyleconroy** [comment]
@djhohnstein thanks for the report! That's most certainly a bug on our end. I'll report back once I've figured out what's going on.

**Comment by djhohnstein** [comment]
Woo hoo! I'll try it again our end come Monday, and if all is well I'll close the issue!

**Comment by djhohnstein** [comment]
Fixed!

**Comment by kyleconroy** [comment]
woohoo! :dancers:
