### ISSUE TITLE
Cannot delete metadata entry

### ISSUE THREAD

**Issue by catskul** [stripe/stripe-python#148]
Attempting to delete an entry of the metadata dictionary

```
del account.metadata["score"]
```

Results in:

```
TypeError: You cannot delete attributes on a StripeObject. To unset a property, set it to None.
```

It seems odd not to be able to remove items completely from the metadata dictionary. The error message seems to imply intentionality, but it's possible its a side effect of the general case.

I think part of this is that metadata is not a first class object in the strip API despite being a `StripeObject` and so the rules don't apply correctly to it.

It should be possible to implement since replacing the metadata dictionary completely is possible. It just requires creating a separate case where it *is* ok to delete an attribute on a StripeObject if it's metadata, or similar.

**Comment by kyleconroy** [comment]
@catskul This is quirk in the way we handle deletion using the Stripe API. I agree it's strange not being able to use `del` to delete attributes. As the error message states, you can do the following:

```
account.metadata["score"] = None
account.save()
```

**Comment by catskul** [comment]
The interesting thing is though that appears that it is possible by other means. Seems like changing the behavior is must a matter of adjusting the client side library. Though I suppose there's a subtly different meaning since if you post a complete replacement for the dictionary things changed in the mean time get wiped...
