### ISSUE TITLE
save after metadata.update does not save metadata

### ISSUE THREAD

**Issue by catskul** [stripe/stripe-python#149]
The following works as expected:
```
object.metadata = { "test" : "message 1" }
object.save()
assert( object.metadata.test == "message 1" )
```

The the following fails:
```
object.metadata.update({ "test" : "message 2" })
object.save()
assert( object.metadata.test == "message 2" )
```

**Comment by kyleconroy** [comment]
Thanks for all reporting all these issues! I'll be able to review the PRs
on Monday.

The following works as expected:

object.metadata = { "test" : "message 1" }
object.save()
assert( object.metadata.test == "message 1" )

The the following fails:

object.metadata.update({ "test" : "message 2" })
object.save()
assert( object.metadata.test == "message 2" )

—
Reply to this email directly or view it on GitHub
<https://github.com/stripe/stripe-python/issues/149>.
