### ISSUE TITLE
Inconsistent serialization between `create()` and `save()`

### ISSUE THREAD

**Issue by praboud** [stripe/stripe-python#153]
If create a new managed account like:

    token = stripe.Token.create(bank_account={'country': 'US',
        'routing_number': '110000000',
        'account_number': '000111111116
    })
    account = stripe.Account.create(managed=True, bank_account=token, country='US')

This works fine. However, if I do:

    account.bank_account = token # should be account.bank_account = token.id
    account.save()

Then no changes take place. When updating the account, you need to provide `bank_account` as the token's ID, whereas when creating the account, either the ID or the full token object will work.

When saving the account with the full token object, it sends a POST to the accounts endpoint with no parameters. This seems to be because updating a resource uses `serialize`, which discards `APIResource` properties when saving the resource. Creating the resource calls the `APIRequestor` directly, which converts the token object into a string ID before submitting the request.

This is a bit of a gotcha, and it would be nice if the two syntaxes could be made consistent.

**Comment by kyleconroy** [comment]
This is a problem, and I'm not entirely sure how to fix it right now. For now, you should be using 

```
account.bank_account = token.token
account.save()
```

**Comment by praboud** [comment]
Fair enough - if it's at least a known issue now, that's already an improvement.

**Comment by aptwebapps** [comment]
Is the issue that user code might depend on the existing behavior (stripping APIResource silently)? Or is that actually required internally?
