### ISSUE TITLE
Issue with retrieving all refunds on a charge

### ISSUE THREAD

**Issue by aronysidoro** [stripe/stripe-python#160]
The [documentation](https://stripe.com/docs/api/python#list_refunds) says to do:

```
stripe.Charge.retrieve({CHARGE_ID}).refunds.all()
```

However, I am getting the error:

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-1413e6050be3> in <module>()
----> 1 stripe.Charge.retrieve(charge.id).refunds.all()

AttributeError: 'list' object has no attribute 'all'
```

This is because on the `Charge` object, `refunds` is an attribute that is the type `list`, and `list` objects don't have an `all()` method.  It is a python `list`, so you would just index it to access it.  

Can you update the documentation to avoid future confusion on this?

**Comment by aronysidoro** [comment]
My title would better read:

### Issue with retrieving all Stripe Refunds on a Charge

**Comment by kyleconroy** [comment]
The documentation is correct for the most recent version of the Stripe API.  The `refunds` list was changed to a sublist object in API version [`2014-07-26`](https://stripe.com/docs/upgrades#2014-07-26).

You're on an API version <= `2014-07-26`. To use the `all` method, you'll need to [upgrade your API version](https://stripe.com/docs/upgrades#how-can-i-upgrade-my-api).

**Comment by aronysidoro** [comment]
@kyleconroy then the `PyPi` *Stripe* package hasn't been update yet, so that's the issue I think.

I did a `pip install -U stripe` before submitting the ticket.

Thanks

**Comment by kyleconroy** [comment]
This library creates objects dynamically, based on the JSON response from the Stripe API. In this case, the charge object is being returned with regular array of refund objects, instead of a sublist object. The version of the Stripe package won't have any bearing on this behavior.

Can you check what version of the API you're using here? https://dashboard.stripe.com/account/apikeys

**Comment by aronysidoro** [comment]
Ok thank you for your help @kyleconroy.
