### ISSUE TITLE
urllib3 InsecurePlatformWarning

### ISSUE THREAD

**Issue by osroca** [stripe/stripe-python#162]
I'm using stripe 1.23.0 and at least in my development environment I'm getting the following warning

```
/Users/oscar/.virtualenv/sky/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
```

Is there a way to avoid it making sure that Stripe bindings sets the right parameters in order to urllib3 can configure SSL appropriately?
Thanks!

**Comment by kyleconroy** [comment]
From the `urllib3` docs:

> Certain Python platforms (specifically, versions of Python earlier than 2.7.9) have restrictions in their ssl module that limit the configuration that urllib3 can apply. In particular, this can cause HTTPS requests that would succeed on more featureful platforms to fail, and can cause certain security features to be unavailable.
>
> **If you encounter this warning, it is strongly recommended you upgrade to a newer Python version, or that you use pyOpenSSL as described in the OpenSSL / PyOpenSSL section.**

You'll need to upgrade to a newer version of Python to make these warnings disappear, as they are about the version of Python you're running, not how `stripe-python` is using `urllib3`

**Comment by osroca** [comment]
Thanks for your answer
