### ISSUE TITLE
can not set additional_owners to an empty list

### ISSUE THREAD

**Issue by dasony** [stripe/stripe-python#168]
For accounts who do not have any additional owners, I tried to set additional_owners to [], None, and empty string before saving, but it would not post anything to API. Because of this, I had to call the API directly with curl to get rid of additional_owners from fields_needed.

The python binding should recognize empty array and add "legal_entity[additional_owners]=" to the parameter, as explained in https://stripe.com/docs/connect/updating-accounts#additional-owners

**Comment by remistr** [comment]
This is an issue with the documentation at the moment which is currently being fixed. In Python, you need to set it to `None` so the code should be:

```
account.legal_entity.additional_owners = None
```
