### ISSUE TITLE
wheels for stripe

### ISSUE THREAD

**Issue by srkunze** [stripe/stripe-python#182]
Do you consider providing Python wheels for stipe? cf.http://pythonwheels.com/

**Comment by kyleconroy** [comment]
So, I took a stab at creating wheels today and came away a bit confused. I was able to generate and upload a [Python 2.7 wheel](https://pypi.python.org/pypi/stripe/1.27.0) which is now live. I had less success creating a Python 3 wheel. We use `2to3

**Comment by kyleconroy** [comment]
Wheels are now live! https://pypi.python.org/pypi/stripe/1.27.1

**Comment by srkunze** [comment]
Great! +1
