### ISSUE TITLE
Stripe-python's APIRequestor takes an optional client, but there's no way to pass it in

### ISSUE THREAD

**Issue by jdunck** [stripe/stripe-python#184]
APIRequestor defaults to creating a new http client on each request (since it is constructed by the external-api methods without a client being passed in).

This means, for example, the `requests` connection pooling can't be used, and a new SSL handshake is needed for each API call.

Please add a way to pass in an existing client, similar to what you do for `api_key` without setting `stripe.api_key`.

    stripe.Customer.create(..., http_client=client)

for example, would do.

Then you could document using `http_client.new_default_http_client` as the default, which would give people enough clue to pass in a client if they wanted something different.

**Comment by kyleconroy** [comment]
We now have the `stripe.default_http_client`. That client will not be re-created on every request, allowing you to re-use connections. Any reason that doesn't work?

**Comment by jdunck** [comment]
Cool, that's probably good enough.. we're currently on 1.19.0, I'll look into upgrading.  I can still imagine scenarios where APIRequestor(,...http_client) does matter, but not in my current use case.

**Comment by jdunck** [comment]
Upgrading to 1.27.1 works for us.  Closing.
