### ISSUE TITLE
API version documentation is misleading.

### ISSUE THREAD

**Issue by skorokithakis** [stripe/stripe-python#187]
The code mentions that you can set the version per-request by setting a variable on the module. However, that is not thread-safe, and will cause *all* requests running after the property set to run with the different version. This can lead to some very interesting race conditions on multithreaded environments, such as servers.

It is recommended to be able to set the version as a parameter on each method call instead.

**Comment by kyleconroy** [comment]
Where does the code mention the module variable is per-request? The module setting is global and never claims to be thread safe.

**Comment by skorokithakis** [comment]
In https://stripe.com/docs/api/python#versioning:

> To set the API version on a specific request, assign a value to the stripe.api_version property.

**Comment by kyleconroy** [comment]
Yep, that is misleading. I'll work on a change.

**Comment by kyleconroy** [comment]
The language has now been changed to the following, which I think is much clearer.

> To override the API version, assign the version to the stripe.api_version property.
