### ISSUE TITLE
Resource tests are not run in Python 3 (135 tests are missing)

### ISSUE THREAD

**Issue by alex-downtown** [stripe/stripe-python#188]
When tests are run against Python 3, whole `test/resources` directory is omitted, so only 76 tests instead of 211 actually run.

**Comment by agentcoops** [comment]
Hi @alex-downtown, thanks for reporting this! I was able to duplicate the issue and I have a PR to resolve it at https://github.com/stripe/stripe-python/pull/191. Let me know if this settles the matter for you as well.

**Comment by alex-downtown** [comment]
Hi @agentcoops, thanks, your pull request seems to fix the issue with non-discovered tests, and furthermore, it fixes running setuptools-based tests via `setup.py test`, complaining for "resources being function" previously.
