### ISSUE TITLE
`test_save_nothing (resources.test_updateable.UpdateableAPIResourceTests)` is failing

### ISSUE THREAD

**Issue by alex-downtown** [stripe/stripe-python#190]
When running the test suite, following test fails on all versions of library for up to 1 year back in history:

    ======================================================================
    FAIL: test_save_nothing (resources.test_updateable.UpdateableAPIResourceTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/toriningen/Projects/stripe-python/stripe/test/resources/test_updateable.py", line 108, in test_save_nothing
        self.requestor_mock.request.assert_not_called()
      File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 915, in assert_not_called
        raise AssertionError(msg)
    AssertionError: Expected 'request' to not have been called. Called 1 times.

Testcase itself looks like this:

    def test_save_nothing(self):
        acct = MyUpdateable.construct_from({
            'id': 'myid',
            'metadata': {
                'key': 'value',
            }
        }, 'mykey')

        self.assertTrue(acct is acct.save())
        self.requestor_mock.request.assert_not_called()

When `request` is being called (while it shouldn't), it tries to perform following query:

    POST /v1/myupdateables/myid
    {
        "metadata": {}
    }

Also, this does not reproduce on Python 3, because of #188.

**Comment by agentcoops** [comment]
As with #189, I'm unfortunately unable to reproduce this issue. Could you clarify your development environment, the latest version of the library that you've tested with, and how you're executing the tests? Thanks!
