### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by beedub** [stripe/stripe-python#197]
When is there expected to be a new release?

**Comment by brandur** [comment]
Hey @beedub! Sorry about the crazy delay here — I'll get one shipped today.

**Comment by brandur** [comment]
@beedub Released as 1.28.0. [Full changelog here](https://github.com/stripe/stripe-python/blob/7c089c7bb24edc96f435936038423c3c8547c490/CHANGELOG).

**Comment by beedub** [comment]
thx @brandur

**Comment by beedub** [comment]
do you know when this is going to be pushed to pypi?

**Comment by brandur** [comment]
@beedub Sorry! Can you try now?

**Comment by beedub** [comment]
yup, accessible now! thx
