### ISSUE TITLE
Problems with Stripe version v1.28.0

### ISSUE THREAD

**Issue by AnderUstarroz** [stripe/stripe-python#201]
I am using **stripe v1.28.0**. Creating a simple script ``stripe_test.py`` with the following code:

    import stripe

    stripe.api_key = 'sk_test_XYZ'
    stripe.api_version = '2015-10-16'
    stripe.Balance.retrieve()

If I execute the script ``$ python stripe_test.py`` I got  the following error:
    
    line 5, in <module>
    stripe.Balance.retrieve()
    AttributeError: 'module' object has no attribute 'Balance'

Nonetheless if I run this code on python console it works fine. Any idea of what's going on?

**Comment by remistr** [comment]
@AnderUstarroz this code works properly for me on the command line. I'd say that your system must not be loading the correct version of the Python bindings and fallbacks on a version that didn't have the `Balance` class. 

You can try the following script to see where the bindings are loaded from and then check the content of `version.py` to see whether you really are on 1.28.0

```
import os
import stripe
import pprint

pprint.pprint(os.path.abspath(stripe.__file__))
```

**Comment by AnderUstarroz** [comment]
Does it work for you also running this code as a script? 
``$ python stripe_test.py``

**Comment by remistr** [comment]
@AnderUstarroz  yes it does. If you use my code you can compare the bindings loaded between each version and then track down why it doesn't load the same one and fix it.

**Comment by AnderUstarroz** [comment]
yes you are right, this is the one I got in console:

    /lib/python2.7/site-packages/stripe/__init__.pyc

This is the one I got on the script:

    /project/stripe_test.py

I will try to find the issue, thanks for the quick help man ;)

**Comment by remistr** [comment]
Sure thing :)
