### ISSUE TITLE
No documentation on auto_paging_iter

### ISSUE THREAD

**Issue by pjrobertson** [stripe/stripe-python#202]
It would be good if you could document the new `auto_paging_iter` method for listable object in the Pagination docs: https://stripe.com/docs/api/python#pagination

I'm not quite sure of the best way to use it. Should I do this:

```
customers = stripe.Customer.auto_paging_iter()

for customer in customers:
    do_something(customer)
```

What's the deal with `limit` - do I still need to set it? The docs still say the default value is 10, but I can't find any mention of the limit within the code - I'm assuming the default limit is set server-side?

**Comment by kyleconroy** [comment]
Yep, good point, the documentation is a bit behind. 

As for `limit`, you do not need to set it. By default, we'll fetch 10 items per page. If you want to fetch more items per page, you can set the limit higher (maximum is 100).

**Comment by brandur** [comment]
@kyleconroy Any thoughts on what to do to resolve this one for the time being? In a couple of the other language bindings, we've added some basic documentation on the method to help users along. It's still really hard to find without an IDE, but at least it's something. What do you think about trying the same thing in Python?

**Comment by olivierbellone** [comment]
Hey @pjrobertson, sorry it took so long, but the feature is now documented on our site: https://stripe.com/docs/api/python#auto_pagination

**Comment by brandur** [comment]
@olivierbellone So amazing to see this live!

In the meantime, I'm closing this out. Thanks :)

**Comment by pjrobertson** [comment]
Great, thanks! I now know how to get rid of this in my code ;-)

```
        customers = []
        last_customer = None
        while True:
            response = stripe.Customer.all(limit=100, starting_after=last_customer)
            customers.extend(response['data'])
            if not response['has_more']:
                break
            last_customer = customers[-1]
```
