### ISSUE TITLE
Accept dependencies at initialization rather than relying on globals

### ISSUE THREAD

**Issue by justanr** [stripe/stripe-python#206]
I'm needing to customize some behavior on API calls using the RequestClient however, `RequestsClient` doesn't accept a Session object and instead uses `requests.request`.

The other issue I'm having is that I then need to get this configured Client into the method calls. However, almost every API Resource simply creates a new instance of `APIRequestor` instead of accepting one at construction. But almost every time this is created, it's with things known at initialization.

I realize that there is `stripe.default_http_client` but I feel like that's a partial fix. And also of #184 and #192

**Comment by brandur** [comment]
+1. This library could use some serious refactoring for better modularity.

@justanr I'm tagging this as "future" for now since unfortunately I'm not sure anyone will be taking a look immediately. Sorry about the trouble.

**Comment by NahomAgidew** [comment]
@brandur Done!

**Comment by ofek** [comment]
@justanr The functionality you requested was implemented in #288. Is that sufficient to remedy this issue?

**Comment by justanr** [comment]
Probably, I'll pull it down and play with it. But this issue can be closed. Thanks!
