### ISSUE TITLE
Unable to upload an image

### ISSUE THREAD

**Issue by smendes** [stripe/stripe-python#208]
While trying to upload the success image I end up with the error:
`'unicode' does not have the buffer interface`

Using the snippet : 
```python
fp = open('success.png', 'r')
file_obj = stripe.FileUpload.create(
  purpose='identity_document',
  file=fp,
  stripe_account=acct_id
)
file = file_obj.id
```

I tried to use a `io.BufferedReader` instead and I end up with the same error.
I'm using python 2.7.10

**Comment by olivierbellone** [comment]
Is it possible you have a
```python
from __future__ import unicode_literals
```
statement somewhere?

If that's the case, you should be able to get around this issue by converting the strings back to `str`:
```python
fp = open(str('success.png'), 'r')
file_obj = stripe.FileUpload.create(
  purpose=str('identity_document'),
  file=fp,
  stripe_account=acct_id
)
file = file_obj.id
```

Nevertheless, I think we should be able to handle this directly in the bindings themselves. I'll dig further.

**Comment by smendes** [comment]
Yes I do use `unicode_litterals` and you are right that was the problem.
Thanks everything works now.

**Comment by brandur** [comment]
Thanks @olivierbellone! Closing this out.
