### ISSUE TITLE
return stripe.Charge.create( AttributeError: 'module' object has no attribute 'Charge')

### ISSUE THREAD

**Issue by pdonaire1** [stripe/stripe-python#226]
Hi!
I have this:
return stripe.Charge.create(
      amount=amount,
      currency=currency,
      source=source, # obtained with Stripe.js
      description=description
    )
and the answers is that:
File "/home/pdonaire1/desarrollos/4geeks/mall4g/apps/orders/stripe.py", line 16, in stripe_charge_create
    return stripe.Charge.create(
AttributeError: 'module' object has no attribute 'Charge'

Note: I'm using Django, but with the shell works excelent, y don't know why with django don't work.

Thanks.

**Comment by olivierbellone** [comment]
Inside your Django project, you probably have a folder called `stripe` or a file called `stripe.py`. So when you `import stripe`, this folder or file is imported in place of the actual `stripe` module.

Rename this folder or file to anything else and it should solve the issue.

**Comment by pdonaire1** [comment]
AHH of course Thank you so much! ^^

**Comment by brahim024** [comment]
> Inside your Django project, you probably have a folder called `stripe` or a file called `stripe.py`. So when you `import stripe`, this folder or file is imported in place of the actual `stripe` module.
> 
> Rename this folder or file to anything else and it should solve the issue.

thank you so much : )

**Comment by brahim024** [comment]
@olivierbellone 
thank you so much : )
