### ISSUE TITLE
Latest Stripe (1.34.0) won't JSON encode in Python 2.7.9

### ISSUE THREAD

**Issue by bsandrow** [stripe/stripe-python#231]
As far as I can tell, it's a bug (?) in the [C version of the JSON encoder](https://github.com/python/cpython/blob/2.7/Modules/_json.c) in the Python standard library. Here are the steps to reproduce:

```pythonshell
>>> import stripe
>>> stripe.api_key = 'sk_test_XXXXXXXX'
>>> import json
>>> evt = stripe.Event.retrieve('evt_XXXXXXXXX')
>>> result = json.dumps(evt)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-df22ddbe60b6> in <module>()
----> 1 result = json.dumps(evt)

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.pyc in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, encoding, default, sort_keys, **kw)
    241         cls is None and indent is None and separators is None and
    242         encoding == 'utf-8' and default is None and not sort_keys and not kw):
--> 243         return _default_encoder.encode(obj)
    244     if cls is None:
    245         cls = JSONEncoder

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.pyc in encode(self, o)
    205         # exceptions aren't as detailed.  The list call should be roughly
    206         # equivalent to the PySequence_Fast that ''.join() would do.
--> 207         chunks = self.iterencode(o, _one_shot=True)
    208         if not isinstance(chunks, (list, tuple)):
    209             chunks = list(chunks)

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.pyc in iterencode(self, o, _one_shot)
    268                 self.key_separator, self.item_separator, self.sort_keys,
    269                 self.skipkeys, _one_shot)
--> 270         return _iterencode(o, 0)
    271
    272 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

TypeError: keys must be a string
```

Forcing the Python version of the encoder to run does not trigger this ([the code that determines which encoder is run is here](https://github.com/python/cpython/blob/2.7/Lib/json/encoder.py#L259-L269)):

```
>>> result = json.dumps(evt, indent=4)
>>> type(result)
str
```

Manually running `.items()` on varying levels of the `Event` object structure doesn't reveal anything useful (they keys are all `str` or `unicode`). Passing `skipkeys=True` to the encoder prevents the exception, but the encoding stops at this depth: `evt['data']['object']['lines']` (which I'll note is a `ListObject` which I have specifically had issues with on the `json` encoder in the past -- which I got around by passing `list_object.data` to the `json` encoder rather than `list_object`).

I will also note that this issue is _not_ present in Python 3.x:

```
$ ipython3
Python 3.3.5 (default, Mar 13 2014, 10:39:48)
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import stripe

In [2]: stripe.api_key = 'sk_test_XXXXXXXXX'

In [3]: import json

In [4]: evt = stripe.Event.retrieve('evt_XXXXXXXXX')

In [5]: result = json.dumps(evt)

In [6]: 
```

I started experiencing this issue when upgrading from `1.19.1` to `1.33.0` (also present in `1.34.0`). I would normally work around something like this by specifying a function to `defaults` keyword argument in the json encoder (specifying a work-around for the `ListObject` class), but since everything in the `stripe` library inherits from `StripeObject` which is a subclass of `dict`, the encoder never tosses a `ValueError`, and therefore never attempts to run the `defaults` function (instead trying to encode it internally as a `dict`).

**Comment by olivierbellone** [comment]
Possibly a duplicate of #220?

**Comment by bsandrow** [comment]
Yes. This looks like the same issue. I didn't think to search for a dupe issue because the issue was still "live" on the current version of the library, and there wasn't an open issue for it.

I also didn't really expect a fix since there is a workaround, and it's technically a bug in cPython. I just figured that I would put this here to document the issue for others. Thanks for the quick response though.

**Comment by brandur** [comment]
@bsandrow Yep, it's definitely worth having this conversation around. Thanks for reporting!

**Comment by olivierbellone** [comment]
@bsandrow No problem! Thanks for reporting this anyway. Your post also added some useful information, such as the fact that Python 3 is unaffected.
