### ISSUE TITLE
Documented `type` Attribute Missing from `StripeError`

### ISSUE THREAD

**Issue by bsandrow** [stripe/stripe-python#233]
The [Stripe documentation on Errors](https://stripe.com/docs/api#errors) references a `type` attribute on `StripeError` instances, but looking at the [`stripe/error.py`](https://github.com/stripe/stripe-python/blob/master/stripe/error.py) code, there is no `type` attribute on any of the exceptions.

**Comment by remistr** [comment]
@bsandrow: The `type` is part of the JSON response itself. When you catch the error in Python, you access the details directly in `json_body` which is where the type is. It doesn't need to be defined in the error class itself and just parsed dynamically.

To reproduce, simply add the card `4000000000000341` to a customer and then attempt to charge it. If you output `e.json_body` you'd see something like this:

```
{u'error': {u'message': u'Your card was declined.', u'code': u'card_declined', u'type': u'card_error', u'charge': u'ch_18GqfqCCAL7IFULRPPU7XbqU'}}
```

**Comment by bsandrow** [comment]
Ah. That wasn't entirely clear to me from the documentation. Thanks.
