### ISSUE TITLE
stripe.InvoiceItem.create() created error "unknown parameters: period, date"

### ISSUE THREAD

**Issue by marians** [stripe/stripe-python#234]
I'm trying to create an invoiceitem for test purposes. Without `date` and `period` parameters it works fine, but adding one of these yields a `stripe.error.InvalidRequestError`.

Example:

```python
import stripe, pytz, time
from datetime import datetime

stripe.InvoiceItem.create(
    customer=customer.id,
    amount=1000,
    currency="eur",
    date=int(time.mktime(datetime(2016, 6, 1, 0, 0, 0, 0, pytz.utc).timetuple())),
    description="Test item",
    discountable=True,
    metadata={"usage_id": "12345abcde"},
    period={
        "start": int(time.mktime(datetime(2016, 5, 1, 0, 0, 0, 0, pytz.utc).timetuple())),
        "end": int(time.mktime(datetime(2016, 5, 31, 23, 59, 59, 0, pytz.utc).timetuple()))
    }
)
```

**Comment by remistr** [comment]
@marians: If you look at the documentation for that API here https://stripe.com/docs/api#create_invoiceitem you'll see that `date` and `period` are not valid arguments for the invoice item creation. You can't pass those so it's expected that you get an error back.

**Comment by marians** [comment]
Got it, thanks!
