### ISSUE TITLE
There is an "error" in the "error handling" in http_client.py

### ISSUE THREAD

**Issue by JSRainEveryWhere** [stripe/stripe-python#237]
In 4 places in http_client.py the error parameter "msg" is not being passed. Therefore the "actual" underlying errors are not being reported.

The incorrect lines are:
    raise error.APIConnectionError(msg)

The lines should be:
    raise error.APIConnectionError(message=msg)

The class APIConnectionError derives from the class StripeError and that class has no initializer with any inherent parameter for "msg". The instance should be called using the keyword "message".

**Comment by brandur** [comment]
HI @JSRainEveryWhere,

Those named arguments can also be used positionally. This script demonstrates that fairly succinctly:

``` python
import sys

class StripeError(Exception):
	def __init__(self, message=None):
		 print('message is = ' + message)

class APIError(StripeError):
	pass

try:
	raise APIError(message="by name")
except:
	pass


try:
	raise APIError("by position")
except:
	pass
```
