### ISSUE TITLE
Not working for TLS 1.2

### ISSUE THREAD

**Issue by ortutay** [stripe/stripe-python#243]
I'm not able to use this library due to the TLS 1.2 upgrade. I get this error message:

```
AuthenticationError: Request req_941s3unQRAQSV6: Stripe no longer supports 
API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2
 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.
```

I've followed the instructions here: https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#python

I'm using version Stripe library 1.37.0, Python 2.7, and openssl 1.0.2h_1 installed via brew. This is in a Flask app.

I saw another instance of this issue on StackOverflow: http://stackoverflow.com/questions/39109583/stripe-api-calls-with-tls-1-2-from-flask

The following `curl` command was suggested on IRC:

```
$ curl -u sk_test_____: https://api-tls12.stripe.com/v1/account
{"object": "list", "data": [], "has_more": false, "url": "/v1/charges"}
```

**Comment by brandur** [comment]
@ortutay Can you give us the OpenSSL version number from within the Python runtime that's runnings your app? i.e. Something like:

``` python
python -c "import ssl; print ssl.OPENSSL_VERSION"
```

Is it possible you're using the OSX system Python? i.e. Check:

```
which python
```

It's worth nothing that updating OpenSSL via Homebrew doesn't relink an existing Python against it.

**Comment by ortutay** [comment]
Output below:

$ python -c "import ssl; print ssl.OPENSSL_VERSION"

OpenSSL 0.9.8zh 14 Jan 2016

$ which python

/Users/marcell/.virtualenvs/sms-rideshare/bin/python

So it seems like it's an older OpenSSL version

**Comment by brandur** [comment]
@ortutay Cool! Alright, the answer here is pretty straightforward then, this version of OpenSSL is too old to support TLS 1.2, so you should consider upgrading to get access to more modern secure protocols.

I'd recommend something like [pyenv](https://github.com/yyuu/pyenv) for this. Here's my output from such an operation:

``` sh
$ pyenv install 2.7.11
Downloading Python-2.7.11.tgz...
-> https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
Installing Python-2.7.11...
Installed Python-2.7.11 to /Users/brandur/.pyenv/versions/2.7.11

$ pyenv local 2.7.11
$ eval "$(pyenv init -)"
$ python --version
Python 2.7.11

$ python -c "import ssl; print ssl.OPENSSL_VERSION"
OpenSSL 1.0.2h  3 May 2016
```

I'm going to close out this issue, but let us know if you have any other questions here. Thanks!

**Comment by ortutay** [comment]
Thanks, that worked via `pyenv`. Do you know if there's a way to do it with just plain python? I don't currently need to keep multiple python version around. StackOverflow has a few suggestions which don't seem to work [1], and neither does upgrading to python 2.7.12 [2]

[1] http://stackoverflow.com/questions/18752409/updating-openssl-in-python-2-7
[2] https://www.python.org/downloads/release/python-2712/

**Comment by brandur** [comment]
Hi @ortutay, yep, this all works perfectly with normal versions of Python (this is in fact what pyenv is installing for you).

My best guess as to what's happening here is that you're not invoking the version of Python that you think you are. For example, you may have installed 2.7.12, but your system Python is coming first in your `PATH` and ends up taking precedence over your new installation. There are lots of possible permutations here too; i.e. 2.7.12 may be easily available for your user, but maybe isn't for the user that your application is running under.
