### ISSUE TITLE
TLS 1.2 on OS X

### ISSUE THREAD

**Issue by alexei** [stripe/stripe-python#244]
Because of this lib I just reset my computer and gave Homebrew a try, having previously failed upgrading OpenSSL with MacPorts. Had no success with Homebrew either. Apparently it can't link the thing.

This is getting really frustrating. Because while I do understand the rationale behind your requirements, I didn't quite get why the sandbox environment would not be more lax in this regard.

So what do now? Any tips for people running OS X?

**Comment by olivierbellone** [comment]
Hey @alexei, sorry you're having trouble with this. On OS X with brew, you should be able to do something like this:

1. Install OpenSSL: `brew install openssl`

2. Install [pyenv](https://github.com/yyuu/pyenv/#simple-python-version-management-pyenv): `brew install pyenv`

3. Compile your desired Python version (cf. [here](https://github.com/yyuu/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib)):
```bash
CFLAGS="-I$(brew --prefix openssl)/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib" \
pyenv install -v 3.5.2
```

4. Enable the new Python globally or locally: `pyenv global 3.5.2`

(In steps 3 and 4, replace `3.5.2` with `2.7.12` or whatever Python version you want to install.)

**Comment by alexei** [comment]
I eventually installed 2.7.12 with `pyenv` and created a new virtualenv using the newly installed version.

**Comment by mittsh** [comment]
This SO answer actually worked better for me (and quicker to install): http://stackoverflow.com/a/40772858

```shell
$ brew update
$ brew install openssl
$ brew install python --with-brewed-openssl
```

**Comment by sscarduzio** [comment]
--with-brewed-openssl is now default in brew for python in OSX
