### ISSUE TITLE
stripe.Subscription.create returning None

### ISSUE THREAD

**Issue by noilly** [stripe/stripe-python#252]
Calling `stripe.Subscription.create` is returning `None`, even though a subscription is being created in the system (I can see it in the dashboard).

**Comment by noilly** [comment]
Looking at the source, it appears that the bug was introduced at this [commit](https://github.com/stripe/stripe-python/pull/249/commits/48856aea2e35d82d5fa76d0ab4483513039883a0)

It looks like the call to `Subscription.create` should return the call to `super(Subscription, cls).create(**params)`

**Comment by samba** [comment]
I've run into this in my application(s) as well, after upgrade to the Python lib at version 1.40.0.

Suggested workaround? Currently I'm planning to temporarily downgrade to the preceding release.

**Comment by brandur** [comment]
Sorry about the trouble here guys! I've added a patch in #253 and am waiting on review.

> Suggested workaround? Currently I'm planning to temporarily downgrade to the preceding release.

Unfortunately a temporary rollback on version might be the best course of action for right now. We should have the fix released by end of day.

**Comment by brandur** [comment]
We've cut a release for the fix at 1.40.1. Sorry again about the trouble!

**Comment by noilly** [comment]
Thanks for the quick response!
