### ISSUE TITLE
Manipulation with api response with empty string values raise exception

### ISSUE THREAD

**Issue by tbicr** [stripe/stripe-python#259]
I have next situation: lib get Event via api and then I make deepcopy for this response. One time I get value with empty string via api and deepcopy down. See sample:

    from copy import deepcopy
    import json
    import mock

    import stripe

    CHARGE_SUCCEEDED_BODY = json.loads('''{
      "id": "evt_************************",
      "created": 1435304004,
      "livemode": false,
      "type": "charge.succeeded",
      "data": {
        "object": {
          "id": "ch_1************************",
          "object": "charge",
          "created": 1435304004,
          "livemode": false,
          "paid": true,
          "status": "succeeded",
          "amount": 15541,
          "currency": "usd",
          "refunded": false,
          "source": {
            "id": "card_************************",
            "object": "card",
            "last4": "4242",
            "brand": "Visa",
            "funding": "credit",
            "exp_month": 11,
            "exp_year": 2015,
            "fingerprint": "****************",
            "country": "US",
            "name": "email@test.com",
            "address_line1": null,
            "address_line2": null,
            "address_city": null,
            "address_state": null,
            "address_zip": null,
            "address_country": null,
            "cvc_check": "pass",
            "address_line1_check": null,
            "address_zip_check": null,
            "tokenization_method": null,
            "dynamic_last4": null,
            "metadata": {},
            "customer": null
          },
          "captured": true,
          "balance_transaction": "txn_************************",
          "failure_message": null,
          "failure_code": null,
          "amount_refunded": 0,
          "customer": null,
          "invoice": null,
          "description": null,
          "dispute": null,
          "metadata": {},
          "statement_descriptor": null,
          "fraud_details": {},
          "receipt_email": null,
          "receipt_number": null,
          "shipping": null,
          "destination": null,
          "application_fee": null,
          "refunds": {
            "object": "list",
            "total_count": 0,
            "has_more": false,
            "url": "/v1/charges/ch_************************/refunds",
            "data": []
          }
        }
      },
      "object": "event",
      "pending_webhooks": 2,
      "request": "iar_**************",
      "api_version": "2015-06-15",
      "user_id": "acct_****************"
    }''')

    @mock.patch('requests.request')
    def test_charge_api_response_body_parsing_errors(self, request_mock):
        charge_body = deepcopy(CHARGE_SUCCEEDED_BODY)
        charge_body['data']['object']['source']['address_zip'] = ''

        request_mock().content = json.dumps(charge_body)
        request_mock().status_code = 200
        request_mock().headers = {}
        event = stripe.Event.retrieve(charge_body['id'], api_key='XXX')
        deepcopy(event)

raises

    Error
    Traceback (most recent call last):
      File "/home/user/Projects/env27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "/home/user/Projects/tests.py", line 759, in test_charge_api_response_body_parsing_errors
        deepcopy(event)
      File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
        y = copier(x, memo)
      File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib/python2.7/copy.py", line 357, in _reconstruct
        value = deepcopy(value, memo)
      File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib/python2.7/copy.py", line 357, in _reconstruct
        value = deepcopy(value, memo)
      File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib/python2.7/copy.py", line 357, in _reconstruct
        value = deepcopy(value, memo)
      File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "/usr/lib/python2.7/copy.py", line 358, in _reconstruct
        y[key] = value
      File "/home/user/Projects/env27/local/lib/python2.7/site-packages/stripe/resource.py", line 110, in __setitem__
        k, str(self), k))
    ValueError: You cannot set address_zip to an empty string. We interpret empty strings as None in requests.You may set {
      "address_country": null, 
      "address_line1": null, 
      "address_line1_check": null, 
      "address_line2": null, 
      "address_state": null, 
      "address_zip_check": null, 
      "brand": "Visa", 
      "cvc_check": "pass", 
      "dynamic_last4": null, 
      "exp_month": 11, 
      "exp_year": 2015, 
      "fingerprint": "****************", 
      "funding": "credit", 
      "id": "card_************************", 
      "last4": "4242", 
      "metadata": {}, 
      "object": "card", 
      "tokenization_method": null
    }.address_zip = None to delete the property

This is look like normal behaviour, https://github.com/stripe/stripe-python/blob/master/stripe/resource.py#L148, but this case too strange, because exactly api return empty string value.

**Comment by olivierbellone** [comment]
Interesting. I think what's happening here is that `deepcopy` casts `event` to a dict, but the nested object in the `data` key is still a `StripeObject`, and so the copy fails because we raise an exception ([here](https://github.com/stripe/stripe-python/blob/0381b7823990d4d56f2be7e0f3739ca3126a9ea4/stripe/resource.py#L147-L152)) when using an empty string for the value.

**Comment by olivierbellone** [comment]
Terrible workaround: `event_dict = json.loads(str(event))`. This will return a `dict` with all nested `StripeObject`s cast as `dict` themselves.

**Comment by brandur** [comment]
> Interesting. I think what's happening here is that deepcopy casts event to a dict, but the nested object in the data key is still a StripeObject, and so the copy fails because we raise an exception (here) when using an empty string for the value.

So it may be even weirder! StripeObject _inherits_ `dict`, so just trying to interate and set its properties at the top level (say from a `copy` rather than a `deepcopy`) throws an exception if there are an empty string values.

It seems that deep copying objects is pretty useful and something we want to enable, so I added a fix for this #260.

**Comment by brandur** [comment]
Patched this in 1.41.1.
