### ISSUE TITLE
Unable to process refunds

### ISSUE THREAD

**Issue by priyam-maheshwari** [stripe/stripe-python#268]
I am using Stripe Python library version 1.23.0 with Python 2.7. When I try to process a refund using the following code

```
import stripe
stripe.api_key = <my_api_key>
refund = stripe.Refund.create(
        charge=payment_id.stripe_id
    )
```

I get an error that `'module' object has no attribute Refund` 

I have checked the init file and indeed Refund hasn't been imported.

**Comment by remi-stripe** [comment]
@priyam-maheshwari the `Refund` object was added on the 1.25.0 version of our library as mentioned in our changelog [here](https://github.com/stripe/stripe-python/blob/master/CHANGELOG#L114). You'll want to upgrade to this version for that code to work as expected.

**Comment by priyam-maheshwari** [comment]
But is there no way to process refund in version 1.23. I can't find any documentation on version 1.23

**Comment by ob-stripe** [comment]
@priyam-maheshwari With older versions, you can retrieve a charge then call the `refund` method:

```python
charge = stripe.Charge.retrieve("ch_...")
charge.refund()
```

That said, you should be able to upgrade to the latest version of the Stripe Python module without issues -- we increment the major version number when backwards-incompatible changes are introduced.
