### ISSUE TITLE
Travis-CI build pending

### ISSUE THREAD

**Issue by NahomAgidew** [stripe/stripe-python#272]
I'm trying to push my contribution to the repo but Travis-CI does not start building the project. The message I see is: "Hang tight, the log cannot be shown until the build has started."

**Comment by dpetrovics-stripe** [comment]
Hi @NahomAgidew, sorry for the late response! Unfortunately Travis-CI occasionally gets quite backed up which can cause delays. Is this still an issue for you? Looking at the branches here https://travis-ci.org/stripe/stripe-python/branches things seem to be OK at the moment.

**Comment by brandur** [comment]
@dpetrovics-stripe I'm not sure if you saw the other pull, but this is related to #266 which was having some seriously weird problems.

@NahomAgidew Whatever crazy thing was happening in Travis seems to be resolved now. I've opened #276 to replace your last pull which includes the necessary fixes to the test suite to get it green. Sorry about the delay here.
