### ISSUE TITLE
What is the purpose of SingletonAPIResource

### ISSUE THREAD

**Issue by jas32096** [stripe/stripe-python#278]
https://github.com/stripe/stripe-python/blob/b44285ff0156f57b8c589a5d60a514a7da0d27b1/stripe/resource.py#L412

Is this used anywhere?

**Comment by ob-stripe** [comment]
Hey @jas32096. `SingletonAPIResource` is used for API resources that are global to an account and don't have an ID. Currently, the only such resource is [`Balance`](https://github.com/stripe/stripe-python/blob/b44285ff0156f57b8c589a5d60a514a7da0d27b1/stripe/resource.py#L570).

**Comment by jas32096** [comment]
Thanks. @ob-stripe I was wondering, because Balance doesn't seem to be subclassed anywhere and is just `pass`.

**Comment by ob-stripe** [comment]
Just defining the class and inheriting `SingletonAPIResource` is enough to register the API resource with a `retrieve` method :)
