### ISSUE TITLE
`modify` should be able to update Sources and External Accounts

### ISSUE THREAD

**Issue by agilgur5** [stripe/stripe-python#282]
Currently, the implementation requires you to write:

```
customer = stripe.Customers.retrieve(customer_id)  # 1st API call
card = customer.sources.retrieve(card_id)  # 2nd API Call
....
card.save()  # 3rd API Call
```

Which is a total of 3 API calls (large bottleneck) just to update a card. Other bindings (e.g. Node, Go), allow you to do this in a single API call:

```
stripe.Customers.update_card(card_id, customer_id=customer_id, **kwargs_to_update)
```

There's Pythonic ways of updating resources similarly, including Django's ORM implementation. I'm not sure what the exact syntax should look like, but it seems extremely inefficient to have to make 3 API calls to modify one resource (and to have to retrieve resources before modifying them)

**Comment by ob-stripe** [comment]
Hey @agilgur5, thanks for reporting this.

Top-level resources can be updated without being retrieved first with the `modify` method:

```python
customer = stripe.Customer.modify('cus_...', description="New description")
```

However, the bindings currently don't offer a way of doing this for nested resources (such as card objects nested in customer objects). I'm tagging this as "future" for now.

In the meantime, if you absolutely need a way to update cards directly, you can do this with:

```python
card = stripe.Card.construct_from({'id': 'card_...', 'customer': 'cus_...'}, None)
card.exp_year = 2020
card.save()
```

**Comment by agilgur5** [comment]
> However, the bindings currently don't have an officially supported way of doing this for nested resources (such as card objects nested in customer objects). I'm tagging this as "future" for now.

@ob-stripe is there a reason why certain language's binding have implemented this and others haven't? I'm very confused why the only "official" method for the Python bindings is extremely inefficient when there's a clear better solution.

> In the meantime, if you absolutely need a way to update cards directly, you can do this with:

Is this method also applicable for updating External Accounts directly?

**Comment by ob-stripe** [comment]
I don't think it was deliberate -- it's just that for most users, retrieving the resources first is not an issue, and depending on your usecase, might even be required.

In any case, I've prepared a PR to add methods to update customers' sources and accounts' external accounts: #286.

> Is this method also applicable for updating External Accounts directly?

Yes. You'd just need to replace `'customer': 'cus_...'` with `'account': 'acct_...'` in the dictionary passed to `construct_from`.
