### ISSUE TITLE
`retrieve` on List should check existing List before making API call

### ISSUE THREAD

**Issue by agilgur5** [stripe/stripe-python#283]
If I have a Card id e.g. 'card_0', calling `customer.sources.retrieve('card_0')` should first check if the `sources.data` list already has a source with id 'card_0', and then make an API call if it's not in the list. Right now, it seems to always make an API call, even if the item is already in the list (from a previous API call).

I manually do this process right now with a simple list comprehension, e.g. `[card for card in customer.sources.data if card.id == 'card_0'][0]`, but I think it would make sense for the binding to auto re-use the data already retrieved ("cached" in a sense)

**Comment by ob-stripe** [comment]
We won't modify the existing behavior of the `retrieve` method -- currently, there's a 1:1 mapping between calling this method on any `StripeObject` and sending the equivalent API request and we don't want to break that invariant.

We could add a convenience method on `ListObject`s (e.g. `retrieve_cached` or something) to return the resource without querying the API if it's already in the list, but I don't feel there would be much value in it. Esp. in Python, a simple list comprehension will do the job as you noted.

@brandur-stripe @bkrausz-stripe, what do you think?

**Comment by brandur-stripe** [comment]
Oof, wow, good points here.

I think my ultimate preference would be a smart caching layer a little like you'd see in Active Record where it would identify very obviously duplicate requests and save the user an API call if one comes up. That said, once you start maintaining a caching layer, you start to run into all the problems that you'd normally see in cache invalidation. For example, you'd want to know that a `customer.sources.modify` would invalidate any cached sources in the list with a matching identifier. That's a simplistic case, but it probably gets even more complicated from there.

I wouldn't mind doing this eventually, but I think my _next_ preference would be to leave things essentially as they are where any invocation on the library will reliably produce an API call and give you fresh data.

It's a bit of a pain, but from there users can then build their own light caching constructs that will suit their needs. Not all users will have the same requirements here: one producing tens of thousands of creates and updates a day might want to disable caching completely to reduce the possibility of another process performing a concurrent update, while a smaller user could probably cache close to indefinitely and never see a problem.

> We could add a convenience method on ListObjects (e.g. retrieve_cached or something) to return the resource without querying the API if it's already in the list, but I don't feel there would be much value in it. Esp. in Python, a simple list comprehension will do the job as you noted.

Yeah, +1. I think it could be useful, but might produce more questions than answers. For example, if there's no cached values, does it produce an API call? Is the call for a list or the individual object? If the latter, you might be prone to accidentally introducing an N + 1 style performance regression.

I'm going to close this out for now, but if anyone has particular strong feelings on the subject, feel free to follow up. Thanks for opening @agilgur5!

**Comment by agilgur5** [comment]
I see, certainly caching everything and invalidating caches is a lot of extra work and balancing tradeoffs that may be more reasonable to leave to userland.

In light of that, maybe a docs update is more reasonable to explicitly say that `retrieve` etc make API calls? In this case, the docs say to do this (similar for all sources + external accounts):

```
customer = stripe.Customer.retrieve({CUSTOMER_ID})
card = customer.sources.retrieve({CARD_ID})
```

even though if the Card is one of the 10 stored sources on the Customer object, a second API call is completely unnecessary.

It could also be substituted with a single call similar to #286 that accepts the Customer id and Card id and returns the Card (similar for all sources + external accounts).

Right now I'm just seeing a lot of inefficiencies in the bindings (vs. the raw API that lets you do most actions in one API call) as with #282 that are the suggested way of doing it in the docs yet are by far not the most efficient way of doing it (seemingly because of inexistent binding methods). If I hadn't looked at the raw `curl` code or other bindings' docs, I would've thought there was no way around this inefficiency -- and multiple roundtrips are _quite_ an inefficiency. Caching is but one solution to that.

**Comment by deontologician-stripe** [comment]
(Closing per @brandur 's previous comments)

**Comment by agilgur5** [comment]
@deontologician-stripe no one responded to my suggestions of creating a single call method instead or updating docs to note the inefficiency etc ...

**Comment by deontologician-stripe** [comment]
@agilgur5 You mean update the README in some way?

**Comment by agilgur5** [comment]
No, as in the Stripe API docs -- as I mentioned, the raw `curl` code makes one less API call than the Python version of the "same method". They are, in fact, not identical, and that should be noted _OR_ a single API call method (that accepts Customer id and Card id as arguments) should be created and used in the API docs instead (which would be identical to the `curl` then)
