### ISSUE TITLE
data getting mangled in "upcoming invoice" endpoint

### ISSUE THREAD

**Issue by Larrik** [stripe/stripe-python#285]
Confirmed on the #stripe freenode channel by @koopajah

Tested to be an issue in both 1.41.2 and 1.47.0

https://gist.github.com/Larrik/bafb3af39e7a06f9e4518b6311efb850

Is the code I use to trigger it, which is essentially sending

```
{
  'customer': u'cus_A9hP84PRfngyGi',
  'subscription': u'sub_A9hPkvSfTNTrPy',
  'subscription_items': [
    {u'plan': u'lcp_annual_print_usd'},  # $59.40 / year
    {u'plan': u'lcp_annual_online_usd'},  # 129.95 / year
    {'deleted': True, 'id': u'si_19pO0N4FL92IQeJUaDdYbQPQ'},  # $95.70 / year
    {'deleted': True, 'id': u'si_19pO0N4FL92IQeJU9SRI0IhH'}  # $41.70 / year
  ],
 'subscription_proration_date': 1487624768
}
```

But the server is receiving
```
{
  "customer": "cus_A9hP84PRfngyGi",
  "subscription_items": [
    {
      "plan": "lcp_annual_print_usd"
    },
    {
      "plan": "lcp_annual_online_usd",
      "deleted": "True",
      "id": "si_19pO0N4FL92IQeJUaDdYbQPQ"
    },
    {
      "deleted": "True",
      "id": "si_19pO0N4FL92IQeJU9SRI0IhH"
    }
  ],
  "subscription_proration_date": "1487624768",
  "subscription": "sub_A9hPkvSfTNTrPy"
}
```

(from https://dashboard.stripe.com/test/logs/req_A9iXyJedrjMp6r)

Notice how subscription_items goes from 4 elements to 3 (with 2 merged into one) at some point in the Stripe library.

Passing `"deleted": False` in the 'added' plans works around this issue.

P.S. I am NOT using DJ-stripe or any other additional stripe libraries.

**Comment by Larrik** [comment]
It's possible this affects other endpoints, of course.

**Comment by remi-stripe** [comment]
@Larrik Thanks for the report! We worked with koopajah on this yesterday and a fix was pushed by one of our engineers a few hours ago: https://github.com/stripe/stripe-python/pull/284 it should be merged soon.
