### ISSUE TITLE
Repo description says Ruby, not Python

### ISSUE THREAD

**Issue by jsstylos** [stripe/stripe-python#295]
"Ruby library for the Stripe API" should be "Python library for the Stripe API"

**Comment by remi-stripe** [comment]
Thanks for catching this! I just pushed a quick fix in https://github.com/stripe/stripe-python/pull/296 and it should be merged later today!

**Comment by brandur-stripe** [comment]
This one is my fault! I was rebuilding the README a bit, and copying a few things back and forth between Ruby and Python to try and build some consistency. Thanks for catching.
