### ISSUE TITLE
Multiplan Subscriptions should use `*.create()`/`*.delete()` methods.

### ISSUE THREAD

**Issue by anelder-stripe** [stripe/stripe-python#302]
The current approach to adding and removing Plans to a Subscription is non-standard.  Our previous approach to things like this (eg. Create Cards [1] and Create Bank Account [2]) has been to use `*.create()` methods.  However, the approach for Plans in Multiplan Subscriptions is to override the attribute with a partial of the list and have that add to the full list on the backend and return something.

### Old Method
```py
# Retrieve the Subscription
sub = stripe.Subscription.retrieve("sub_xxx")

# Attach a New Subscription Item
sub.items = [{'plan': 'PLAN_ID1', 'quantity': 2}]

# Delete ~some Subscription Item (requires the ID)
sub.items = [{'id': 'si_xxx', 'deleted': True}]
```

### New Proposed Method
```py
# Retrieve Subscription
sub = stripe.Subscription.retrieve("sub_xxx")

# Attach a New Subscription Item
si_one = sub.items.create(plan="PLAN_ID1")

# Delete that Subscription Item
si_one.delete()
```

This affects other language bindings as well including PHP and Ruby.  May file those separately after this has been triaged.

@brandur-stripe believes that this should happen automatically, but it looks like that functionality is broken and we will need to investigate why.

[1] https://stripe.com/docs/api/python#create_card
[2] https://stripe.com/docs/api/python#customer_create_bank_account

**Comment by brandur-stripe** [comment]
+1 that things should work as proposed above. I thought that this was supposed to be enabled automatically if a `list` object is returned from the API, but that might be a Ruby-only thing.

**Comment by ob-stripe** [comment]
The "old method" allows you to create/modify/delete multiple items in a single API request, so we should make sure that we support both.

**Comment by anelder-stripe** [comment]
Just want to make a quick note that I've seen another incident of a user being confused by the current interface in Python.

**Comment by ob-stripe** [comment]
This was solved by the addition of the `/v1/subscription_items` endpoint back in September. The new proposed method works without any change in the Python library (with the exception that you have to use `sub['items']` instead of `sub.items`, cf. #297).
