### ISSUE TITLE
Install started failing for users of older pip

### ISSUE THREAD

**Issue by ofek** [stripe/stripe-python#307]
@brandur-stripe @ob-stripe Requests 2.14.1 just released and now requires pip >= 8.1.2 and a newish version of setuptools https://github.com/kennethreitz/requests/issues/4006

As of today, stripe-python will fail to install for users of older packaging infrastructure, including Travis.
https://travis-ci.org/stripe/stripe-python/jobs/230553497#L497
https://github.com/kennethreitz/requests/pull/4007#issuecomment-300364756

We should deploy an emergency release limiting requests to version 2.13.0 and documentation should be added detailing that in the next major release there will be a minimum required version of pip.

**Comment by ofek** [comment]
A huge number of projects' builds broke today, not just use!

**Comment by ofek** [comment]
https://github.com/stripe/stripe-python/pull/308 fixes our Travis builds.

**Comment by brandur-stripe** [comment]
Thanks for the report here @ofek and the initiative to get the fix in.

Just as a quick explanatory follow up: it seems that Requests 2.14.0 was the version that broke everybody. They followed up with 2.14.1 which is designed to be adaptable to more environments, and with the pip and setuptools upgrades in #308, things seem to be relatively happy again.

Closing this out.

**Comment by ofek** [comment]
Well, #308 only fixes Travis. Our users are still affected even with 2.14.1. https://github.com/kennethreitz/requests/pull/4007#issuecomment-300364756

**Comment by ofek** [comment]
@brandur-stripe @ob-stripe Without releasing a new version that limits requests to 2.13.0 many of our users cannot install this. Unless we're ok with just adding a note to doc saying to upgrade pip and setuptools?

**Comment by brandur-stripe** [comment]
@ofek Good point. I'd be fine with limiting the ceiling on the Requests version. We'll have to kill it eventually lest it start causing transitive dependency hell problems in the future, but hopefully by the time we unlock it more people will be upgraded on pip/setuptools.

I notice that right now we're already doing some conditional shenanigans around versioning Requests in our `setup.py`:
https://github.com/stripe/stripe-python/blob/a84a0c80b2a325a989b14ab9ecf3d59b7b74be6d/setup.py#L20,L29

Do you know if there's an additional check on pip/setuptools versions that we could also add in there with the capped Requests? That might be the best of both worlds.

**Comment by brandur-stripe** [comment]
From the other thread:

> @ofek thanks for pointing this out. It looks like (some or all of) the Travis-CI instances are running on setuptools 12.0.5. While sys_platform was supported then, python_version doesn't seem to have been added until 18.0 (although the change log says 18.5). You'll need to upgrade setuptools on Travis-CI to at least 18.0, or run pip install -U setuptools to get the latest version.

I _think_ we could add a conditional to look for `setuptools` < 18.0 and that might be enough of a heuristic.

**Comment by ofek** [comment]
Fixed in https://github.com/stripe/stripe-python/pull/310, just needs a release after merge.

**Comment by brandur-stripe** [comment]
What do you think about something like #307 instead? I think this approach might be more forwards compatible.

**Comment by brandur-stripe** [comment]
@ofek Released 1.55.1. Let me know if it doesn't work as expected.

**Comment by ob-stripe** [comment]
@brandur-stripe @ofek requests released a couple of minor updates [0] that seem to have widely increased the compatibility with older pip & setuptools version.

I just tested in a venv with pip 1.5.4 and setuptools 3.6 and was able to install stripe 1.55.0.

I've also just pushed a branch where I reverted both the `setup.py` and `.travis.yml` fixes and verified that tests are passing: https://travis-ci.org/stripe/stripe-python/builds/231091378.

Should we revert the fixes?

[0] https://github.com/kennethreitz/requests/blob/master/HISTORY.rst#2142-2017-05-10

**Comment by ofek** [comment]
Nice! If you do, I still think it's wise to pin our deps.

**Comment by brandur-stripe** [comment]
Nice catch @ob-stripe! I agree and have added a revert in #312.

> Nice! If you do, I still think it's wise to pin our deps.

I generally agree, but I think that it makes much more sense for an app than it does for a library like this one that's used as a dependency. By constraining stripe-python's dependencies too tightly, we increase the likelihood that some other library in a user's app that also needs Requests will have conflicting version requirements and lead to transitive dependency hell.

I'll certainly reconsider if it turns out that this leads to serious problems, but given that the version bumps in Requests have been patch releases that were pushed relatively quickly after the breaking version, the prevalence of bad versions (2.14.0 and 2.14.1) should be relatively low.

**Comment by ofek** [comment]
That makes sense, thanks!
