### ISSUE TITLE
to_dict doesn't convert all elements of ListObject to standard Python types

### ISSUE THREAD

**Issue by hardworkingcoder** [stripe/stripe-python#314]
Right now I'm having to do `json.loads(str(stripe.Subscription.list(customer=user.stripe_customer_id)))` because stripe.Subscription.list(customer=user.stripe_customer_id).to_dict() doesn't convert the list to a JSON serializable list.

**Comment by ob-stripe** [comment]
Hey @hardworkingcoder. First, please note that `to_dict` is deprecated. `StripeObject`s inherit from `dict` so you can use them as `dict`s directly.

You are correct that nested objects will not recursively be converted to standard Python types, but I don't think we've ever mentioned that that would be the case. If you want to serialize a `StripeObject` to JSON, then calling `str()` is the correct way to do it.

Can you clarify what you want to do exactly?

**Comment by hardworkingcoder** [comment]
I want to serialize to JSON. To serialize to JSON I currently have to do
json.dumps(ast.literal_eval(str(StripeObject)))

**Comment by ob-stripe** [comment]
I'm probably missing something, but I really don't get why this is necessary. Calling `str()` on any Stripe object will return a valid JSON representation of the object, e.g.:

```py
>>> customer = stripe.Customer.create(email="test@example.com")

>>> type(customer)
<class 'stripe.resource.Customer'>

>>> customer_json = str(customer)

>>> # customer_json is a string containing the JSON representation of customer

>>> type(customer_json)
<type 'str'>

>>> print(customer_json)
{
  ...
  "email": "test@example.com",
  ...
}

>>> customer_params = json.loads(customer_json)

>>> # customer_params is a standard Python dict containing all the parameters decoded from the JSON representation

>>> type(customer_params)
<type 'dict'>

>>> customer_params['email']
'test@example.com'

>>> customer_deserialized = stripe.convert_to_stripe_object(customer_params, stripe.api_key, None)

>>> # customer_deserialized is a StripeObject instance, specifically a Customer instance, initialized from the provided parameters

>>> type(customer_deserialized)
<class 'stripe.resource.Customer'>

>>> customer_deserialized.email
'test@example.com'

>>> customer_deserialized == customer
True
```

**Comment by hardworkingcoder** [comment]
Sorry about that. I thought I had a JSON failure with just str. I was wrong.

**Comment by ob-stripe** [comment]
@hardworkingcoder No problem! :)
