### ISSUE TITLE
Imports are done incorrectly in Stripe Python library

### ISSUE THREAD

**Issue by royleban** [stripe/stripe-python#315]
The Python API package does imports incorrectly. This is what you do:

`from stripe.resource import ...
`

This is what you should do ...

`from resource import ...
`

Why does it matter? Right now, stripe must be at the root of the web server. There is no reason for this and many web sites have packages such as Stripe in a subdirectory. Changing the imports would enable this without any disadvantages.

Support noted that there is an expectation that Stripe is installed globally. That is impossible on Google App Engine and is also not a best practice for people who only have one web server. It makes the server code more fragile because installs must happen before it is moved. Aside from that, fixing this problem would not cause any problems for globally-installed copies of Stripe.

Interestingly, there are comments in your __init__.py which indicate that your developers even know about this bug and haven't fixed it yet.

**Comment by brandur-stripe** [comment]
Hi Roy,

I must admit that I'm not a Python expert and could use some guidance here. Would you mind citing a few references that suggest that this is best practice?

I took a look around at a few popular Python packages to see what's done elsewhere. Requests uses relative paths (different than what you suggested, but involves prefixing modules with a `.`), but [Scrapy (source)](https://github.com/scrapy/scrapy/blob/d847e65aaef68009b1ba4c12e45f34a7783dcc5b/scrapy/http/__init__.py#L10-L12) and [Twisted (source)](https://github.com/twisted/twisted/blob/69b30c9a9b74f44180b8118ce9fde69a70bcfe15/src/twisted/web/distrib.py#L25-L27) are using absolute paths like is done in stripe-python, which leads me to believe that it's not that unusual.

I don't mind moving to something like relative paths if it's helpful. I took a shot at this in #321 to see what that would look like.

> Interestingly, there are comments in your init.py which indicate that your developers even know about this bug and haven't fixed it yet.

Can you reference a comment in particular? I read through it but couldn't find anything that suggested that. Whether or not this is best practice or not, I don't think we can really call it a bug.

**Comment by ob-stripe** [comment]
I'm not sure if there's a strong consensus. I think that previously, PEP 8 strongly discouraged from using relative imports. In its [current version](https://www.python.org/dev/peps/pep-0008/#imports), it seems to merely recommend absolute imports over relative:

> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on `sys.path`)

> However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose

> Standard library code should avoid complex package layouts and always use absolute imports.

> Implicit relative imports should never be used and have been removed in Python 3.

**Comment by brandur-stripe** [comment]
Thanks @ob-stripe! And wow, I should've checked PEP 8; thanks for doing that research.

> Implicit relative imports should never be used and have been removed in Python 3.

I *think* implicit relative imports might be what Roy was referring to above?

@ob-stripe Do you have any opinion on what we should do here? The relative imports in #321 seem fine to me, but I could see us going with or without them. The explicitness of `stripe.` is nice, and the name of this package is not likely to ever change.

**Comment by ob-stripe** [comment]
Yeah, after giving it some more thought, I think we should follow PEP 8 recommendations and stick to absolute imports.

I don't have a very clear idea of the problem that relative imports would solve though. I haven't used Google App Engine myself, but I think that the method documented [here](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27#installing_a_third-party_library) can be used to import the `stripe` module in a GAE app.

**Comment by royleban** [comment]
First, here are the comments:

```
# Error imports.  Note that we may want to move these out of the root
# namespace in the future and you should prefer to access them via
# the fully qualified `stripe.error` module.

# DEPRECATED: These imports will be moved out of the root stripe namespace
# in version 2.0
```
Second, there are two related issues here.

1) Relative imports to files with simple names (like error.py) can break, especially when a module is moved.
2) Absolute imports prevent a module from being anywhere but where the original author intended it to be. This causes several problems:
a) Unnecessary clutter at the root of servers
b) Inability to work in special environments that may impose requirements on where libraries can be installed

Personally, I think PEP 8 is off the mark in recommending absolute imports. While they solve problems caused by implicit relative imports, they are clearly inferior to explicit relative imports in the context of libraries installed as the Stripe library is installed. You should also read PEP 328.

While (2b) doesn't apply for the Stripe library in the Google App Engine flexible environment, it could certainly apply in other situations. A related issue is libraries that expect to be installed via an installer, rather than having a directory placed at a certain location. Such installers cannot run on GAE.

Finally, what I wrote was wrong. You want an _explicit_ relative import, not an implicit one. They were included as of Python 2.5. What you want is:
```
from .resource import ...
```
or
```
from . import ...
```

Switching to explicit relative imports has no disadvantages, is very clear, and has the advantage of allowing Stripe to be installed anywhere.

**Comment by royleban** [comment]
> I don't have a very clear idea of the problem that relative imports would solve though. I haven't used Google App Engine myself, but I think that the method documented here can be used to import the stripe module in a GAE app.

The issue here isn't installing, it's where it's installed. We already have enough clutter at the root of our web server. We should be able to put the library wherever we want. Absolute imports force us to install the library at the root.

**Comment by brandur-stripe** [comment]
Hi Roy,

> First, here are the comments:

Hm, those aren't related to the issue at hand. They're referring to the fact that error types used to be located at the root of the package `stripe`, but have since been pushed down to `stripe.error`. They're still exported at root for compatibility, but this is a note that those shouldn't be used because they're considered deprecated.

> Absolute imports prevent a module from being anywhere but where the original author intended it to be. This causes several problems:

Hm, I don't think that's true. Absolute paths are usable because they're intended to be included from [an import path](https://docs.python.org/3/reference/import.html). End user applications have quite a bit of flexibility in controlling where they're allowed to be.

From App Engine, this seems to be possible [using this technique that OB linked above](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27#installing_a_third-party_library).

> Personally, I think PEP 8 is off the mark in recommending absolute imports. While they solve problems caused by implicit relative imports, they are clearly inferior to explicit relative imports in the context of libraries installed as the Stripe library is installed. You should also read PEP 328.

I might have to leave you to take that up with the PEP 8 people. Would you mind posting the relevant sections of PEP 328 that contradict PEP 8 regarding this topic? I [found this description of PEP 328's announcement](https://docs.python.org/3/whatsnew/2.5.html#pep-328-absolute-and-relative-imports), but reading it they're highlighting the problems of explicit relative imports over implicit relative imports, not over absolute imports:

> Consider the code in the main.py module. What happens if it executes the statement import string? In Python 2.4 and earlier, it will first look in the package’s directory to perform a relative import, finds pkg/string.py, imports the contents of that file as the pkg.string module, and that module is bound to the name string in the pkg.main module’s namespace.
>
> That’s fine if pkg.string was what you wanted. But what if you wanted Python’s standard string module? There’s no clean way to ignore pkg.string and look for the standard module; generally you had to look at the contents of sys.modules, which is slightly unclean. Holger Krekel’s py.std package provides a tidier way to perform imports from the standard library, import py; py.std.string.join(), but that package isn’t available on all Python installations.

> Switching to explicit relative imports has no disadvantages, is very clear, and has the advantage of allowing Stripe to be installed anywhere.

I'll let OB's quote from PEP 8 above argument in favor of absolute imports over explicit relative ones. My reading is that the import behavior of either is essentially the same, but if you feel I'm wrong there, I'm more than happy to be corrected if you cite a source.

**Comment by ob-stripe** [comment]
Closing this issue as we decided to keep using absolute imports for now, but feel free to reply!
