### ISSUE TITLE
Data prefix for expand fields in list command

### ISSUE THREAD

**Issue by milancermak** [stripe/stripe-python#316]
Hi,

I noticed that when I'm using the `stripe.Charge.list` command, I need to prefix every field in the expand group with `data.` otherwise the call fails:

```python
expand = ['application', 'application_fee', 'balance_transaction',
          'customer', 'destination', 'dispute', 'invoice', 'on_behalf_of',
          'order', 'review', 'source_transfer', 'transfer']
charges = stripe.Charge.list(expand=expand)

InvalidRequestError: Request req_AhzbZJOTH53cbs: This property cannot be expanded (application). You may want to try expanding 'data.application' instead.

# works when using the following
expand = ['data.application', 'data.application_fee', 'data.balance_transaction',
          'data.customer', 'data.destination', 'data.dispute', 'data.invoice',
          'data.on_behalf_of', 'data.order', 'data.review', 'data.source_transfer',
          'data.transfer']
```

Fortunately your error messages are very helpful 👍 but I didn't see a mention of this in the documentation, plus the normal way, without the prefix, works for the `retrieve` method.

I can deduce the reasons why the `data.` prefix is necessary for the `list` method, though from my point of view as a user of the library, it's an issue with inconsistent API. Is it something you're considering improving?

**Comment by brandur-stripe** [comment]
Hi @milancermak,

When getting a list of objects through Stripe, you're actually getting them back nested in what we call a "list object" which contains some basic metadata for uses in pagination. You can see an example [in our docs here](https://stripe.com/docs/api#list_charges). `data` is the array within the list object that nests your charges.

Given that expandable keys are always addressed at their path within a JSON document, this is consistent with how other API methods work elsewhere. Does that make sense?

I'm going to close this out for now, but let me know if you have any other questions!
