### ISSUE TITLE
PycurlClient doesn't work with Python 3

### ISSUE THREAD

**Issue by href** [stripe/stripe-python#317]
When using the Stripe Python API in combination with PycurlClient and Python 3, the requests made to the API cannot complete.

In the `http_client.py` file, the first line of the `_handle_request_error` function the value of e is `error(23, 'Failed writing header')`. The error results in another error because the request handling code doesn't work with this specific error value (the error object does not support indexing).

The cause of this problem seems the be the use if StringIO instead of BytesIO:
https://stackoverflow.com/a/23610279/138103

To test run any method that connects to the API in Python 3 after running the following:
```python
stripe.default_http_client = stripe.http_client.PycurlClient()
```

Python Version: 3.5.3
Library Version: 1.55.2

**Comment by ob-stripe** [comment]
Hey @href, thanks for reporting this! I was able to reproduce the issue and prepared a patch here: #320.

**Comment by brandur-stripe** [comment]
We've just pushed @ob-stripe's patch in 1.57.1.

Sorry about the trouble here!

**Comment by href** [comment]
Awesome, thanks for the quick fix :)
