### ISSUE TITLE
Updating account using literal dicts (instead of dot notation) results in weird errors

### ISSUE THREAD

**Issue by btubbs** [stripe/stripe-python#328]
Here's a sample script that seems like it should work (you may need to change the first couple lines setting stripe.api_key).  It creates a barebones custom account, retrieves it, alters the legal_entity field, then saves it back.

```python
from pprint import pprint

from voltron.settings import get_settings
import stripe

settings = get_settings()

stripe.api_key = settings.STRIPE_SECRET_KEY
resp = stripe.Account.create(
    type='custom',
    country='US',
)

acct = stripe.Account.retrieve(resp['id'])

legal_entity={
    'type': 'company',
    'dob': {
        'day': 4,
        'month': 7,
        'year': 1979,
    },
    'first_name': 'Brent',
    'last_name': 'Tubbs',
    'personal_id_number': '123-45-6789',
    'address': {
        'line1': '1600 Pennsylvania Ave NW',
        'line2': None,
        'city': 'Washington',
        'state': 'DC',
        'postal_code': '20500',
        'country': 'US',
    },
}

acct.legal_entity = legal_entity

resp2 = acct.save()
pprint(resp2)
```

When I do that however, I get this exception:

```python
Traceback (most recent call last):
  File "tmp/update_stripe_account.py", line 38, in <module>
    resp2 = acct.save()
  File "/Users/brent.tubbs/.virtualenvs/voltron/lib/python3.5/site-packages/stripe/resource.py", line 491, in save
    updated_params, headers))
  File "/Users/brent.tubbs/.virtualenvs/voltron/lib/python3.5/site-packages/stripe/resource.py", line 229, in request
    response, api_key = requestor.request(method, url, params, headers)
  File "/Users/brent.tubbs/.virtualenvs/voltron/lib/python3.5/site-packages/stripe/api_requestor.py", line 151, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/Users/brent.tubbs/.virtualenvs/voltron/lib/python3.5/site-packages/stripe/api_requestor.py", line 309, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/Users/brent.tubbs/.virtualenvs/voltron/lib/python3.5/site-packages/stripe/api_requestor.py", line 170, in handle_api_error
    rbody, rcode, resp, rheaders)
stripe.error.InvalidRequestError: Request req_AsyrmTGFmAKBuU: You passed an empty string for 'legal_entity[personal_address]'. We assume empty values are an attempt to unset a parameter; however 'legal_entity[personal_address]' cannot be unset. You should remove 'legal_entity[personal_address]' from your request or supply a non-empty value.    
```

Despite what the exception says, I didn't actually set legal_entity[personal_address] to anything.  It's not even present in my `acct` dict.  If I look at the outgoing POST data, however, I can see that it includes `legal_entity%5Bpersonal_address%5D=` (ie, the key is included but no value).

I can stop this from happening if I explicitly set legal_entity[personal_address] to None in the `acct` object.  But then the same error pops up for legal_entity[verification].  And if I set *that* to None, I get an exception about "Received unknown parameters: ssn_last_4_provided, personal_id_number_provided, business_tax_id_provided".

If supplying my own legal_entity dictionary is going to cause problems like this, it should either warn me before hitting the API or at least be noted in documentation that dot notation is the only way to go.

**Comment by ob-stripe** [comment]
Hey @btubbs, the issue is that when you do this:

```python
acct.legal_entity = legal_entity
```

you're replacing the entire `acct.legal_entity` dict with your new `legal_entity` dict. This unsets existing keys such as `personal_address`, so when you then call `acct.save()`, the library explicitly unsets those keys in the API request.

In other words, the behavior you're observing is the expected one. You can solve this issue by updating the existing dictionary instead of overwriting it:

```python
acct.legal_entity.update(legal_entity)
```
