### ISSUE TITLE
Subscription items are not converted to dict when using setattr + save

### ISSUE THREAD

**Issue by ob-stripe** [stripe/stripe-python#336]
When calling `Subscription.create` or `Subscription.modify`, the library converts the `items` parameter from a list of dicts to a numerical-indexed dict of dicts to work around the infamous list of dicts URL-encoding issue.

(Relevant code: https://github.com/stripe/stripe-python/blob/9d149e747758b39e2d3ad939a2cd11a44e3c0267/stripe/resource.py#L868)

However, this doesn't work when retrieving the subscription, setting `items` via `__setattr__` and calling `save`:

```python
sub = stripe.Subscription.retrieve('sub_...')
sub.items = [
  {'id': 'si_...', 'deleted': True},
  {'plan': 'gold'},
]
sub.save()
```

In this case, the `items` parameter is not converted, which causes the API to decode it as `[{'id': 'si_...', 'deleted': True, 'plan': 'gold'}]` due to the lack of a common key between the two dicts. This of course produces incorrect results.

Manually providing a numerical-indexed dict instead of a list does not work either, because in this case the library tries to unset the `object`, `url`,  `data`, `has_more` and `total_count` attributes from the original list object that was set as the value for the `items` attribute when the subscription was retrieved, causing the API to return an "Invalid array" error.

cc @brandur-stripe @kjc-stripe

**Comment by brandur-stripe** [comment]
Nice catch! Added a fix in #338.
