### ISSUE TITLE
Stripe api_version not customizable for stripe.Customer.list

### ISSUE THREAD

**Issue by q-erty** [stripe/stripe-python#343]
When calling `stripe.Customer.list(api_key=key, api_version='2015-10-16')` with a custom api_version, we get the following error:

```
InvalidRequestError: Request req_I25zAXmrYWc3Mj: Received unknown parameter: api_version
```

This is using python 2.7 via the CLI.

It appears that the `api_version` param is not correctly passed into the `APIRequestor` constructor at https://github.com/stripe/stripe-python/blob/master/stripe/resource.py#L451 . I think it should look like https://github.com/stripe/stripe-python/blob/master/stripe/resource.py#L924 . There might be other places where this happens as well.

We are able to work around this by just setting the global stripe api version using `stripe.api_version='2015-10-16'`.

Thank you!

**Comment by brandur-stripe** [comment]
Patched by @ob-stripe and released as 1.65.0.
