### ISSUE TITLE
Better Access to Response Headers

### ISSUE THREAD

**Issue by sedouard** [stripe/stripe-python#370]
On a successful API request the Stripe Java SDK doesn't provide a way of accessing response headers. (At least not that I can tell).

This can be useful in the case you're interested in response metadata (such as Idempotency-Key and Request-ID).

For example in a GET /charges/:id request:

```python
import stripe
stripe.api_key = "sk_test_..."

# list charges
stripe.Charge.list()

# retrieve single charge - no response headers
charge = stripe.Charge.retrieve("ch_1A2PUG2eZvKYlo2C4Rej1B9d")
```

It would be great if there was an optional way to grab the HTTP response metadata through some kind of bound method on the deserialized response:

```python
charge.getResponse()
```

Or simply as a property:

```python
charge.response
```

Because [api_requestor](https://github.com/stripe/stripe-python/blob/master/stripe/api_requestor.py#L352) returns only the deserialized version of the response body it isn't possible to get HTTP request-specific things at the moment. Does it make sense to add a `response` property here so that we mirror the approach [discussed in the node sdk](https://github.com/stripe/stripe-node/issues/406)?

**Comment by sedouard** [comment]
(feel free to assign this to me as I'm happy to do a PR here)

**Comment by brandur-stripe** [comment]
@sedouard To be honest, a lot of the improvements come about when someone is interested enough to tackle them. If you are here, then I think you should take a shot at it — we can always use a few more people able to actively contribute to these libraries. (And it sounds like you already are, but maybe just coordinate with Olivier and co. first to make sure none of them are working on it.)

**Comment by jleclanche** [comment]
Use case: I am creating a database entry in my app upon a particular event which results in a stripe API request. I want this entry to be as auditable as possible and want to include the request_id.

What I'm doing:

```py
customer = Customer.retrieve(...)
customer.account_balance = 5
customer.save(idempotency_key)
```

What I'd like to do here is, as a result of the save() call, I would like to get access to the response headers.

@sedouard Have you worked on a PR for this? If you haven't and it's not on your plate I'll be happy to tackle it.

**Comment by ob-stripe** [comment]
@jleclanche Yes, there is an open PR for this: #371.

Once it's merged, all `StripeObject`s will have a `last_response` property that you'll be able to use access the properties (headers and body) of the last HTTP response for the object, e.g.:

```python
customer.save(idempotency_key=idempotency_key)
request_id = customer.last_response.request_id
```

**Comment by jleclanche** [comment]
Oh, cool, I missed the PR yeah. Just read the backlog and changes, looks great. You guys sure saved me a bunch of work :)

**Comment by ob-stripe** [comment]
Fixed in #371 and released as 1.77.0.

**Comment by danielhao5** [comment]
It seems I cannot get either status_code, or response_code by following the same?

Code snippet: 
customer = stripe.Customer.create(..skip......)
status_code = customer.last_response.status_code
However, I can get the request_id.

Using the latest stripe version and Python 3.7.  Not sure what I'm missing here?

**Comment by ob-stripe** [comment]
@danielhao5 The status code is accessible via the `code` attribute, not `status_code`: https://github.com/stripe/stripe-python/blob/b080ddb2a5bcdc5b0e050ad80369a477c06ba04e/stripe/stripe_response.py#L9

**Comment by pakrym-stripe** [comment]
@inai-suraj can you share a code snippet that's not working for you?

I just tried the following code and it works as expected.

```python
  resp = stripe.PaymentIntent.create(
            amount=1099,
            currency="eur",
            automatic_payment_methods={"enabled": True},
        )
        print(resp.last_response.headers)
```

**Comment by inai-suraj** [comment]
@pakrym-stripe My bad. It works. Thanks.
