### ISSUE TITLE
Can't update French Connect Custom account's legal entity with a new account token

### ISSUE THREAD

**Issue by louischatriot** [stripe/stripe-python#417]
Seems like a bug in the library as I can make it work with curl, see code below

```python
    legal_entity_data = { 'first_name': 'something' }
    account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
    stripe_account = stripe.Account.create(type = 'custom', country = 'FR', account_token = account_token)
    assert(stripe_account['legal_entity']['first_name'] == 'something')

    # Update a legal_entity field
    legal_entity_data = { 'first_name': 'another' }
    account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
    stripe_account = stripe.Account.retrieve(stripe_account['id'])   # Should be idempotent but just in case
    stripe_account.account_token = account_token
    stripe_account.save()

    stripe_account = stripe.Account.retrieve(stripe_account['id'])
    assert(stripe_account['legal_entity']['first_name'] == 'another')
    # ^
    # This assertion fails (first_name is still equal to 'something')
    # But updating the account with the account token using curl does work, 'first_name' becomes 'another'
    # So this seems like a bug with the Python library
```

**Comment by ob-stripe** [comment]
Hey @louischatriot :)

Just tried your exact script, and the assertion does succeed on my end.

I assume you're already on the latest library version (1.79.1)? Just in case, which Python version are you using?

**Comment by louischatriot** [comment]
Hey @ob-stripe !

Sorry, just realizing the above snippet was wrong and did not trigger the error (the last assertion was trying against 'something' instead of 'another'). I edited the code, can you try again?

We're using the latest version of the lib and python 3.5

**Comment by ob-stripe** [comment]
Ah, gotcha. So the issue is on this line:

```python
stripe_account.account_token = account_token
```
should instead be:
```python
stripe_account.account_token = account_token.id
```

That said, it's not great that the library is just silently ignoring the param when you set `account_object` to the entire token object. I'll dig a bit more to see if that's expected or not.

**Comment by remi-stripe** [comment]
Lurking in: I think stripe-ruby has some magic for this while the other libraries don't.

**Comment by louischatriot** [comment]
Thanks @ob-stripe it solves the issue indeed, I can avoid doing direct requests :)

Shame on me I had not tried to just pass the id because in `stripe.Account.create` you can pass the full token (as you can see in the above snippet). So seems this lib has the magic @remi-stripe mentions on account creation but not update?

Closing as not a bug in the lib - though you may want to add a mention in the API docs

**Comment by louischatriot** [comment]
(btw, impressed by the fast turnaround on this one!)
