### ISSUE TITLE
Strange behavior of additional_owners field in Connect Custom accounts

### ISSUE THREAD

**Issue by louischatriot** [stripe/stripe-python#418]
I found two behaviors quite strange when using the library, including something that may be a bug in the library.

**Issue 1**
When creating a Custom account, `additional_owners` cannot be passed as an array even though that's the format the API outputs, see code below:
```python
legal_entity_data = { 'first_name': 'something', 'additional_owners': [{ 'first_name': 'LLL' }] }
account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
# ^
# Raises an InvalidRequestError with message 'Invalid hash'
# But it works if we use { 0: { 'first_name' }: 'LLL' } ...
```

**Issue 2**
I can't remove any formerly created `additional_owners` by deleting the property on the Stripe account object as per https://stripe.com/docs/connect/account-tokens (though given there is no code example I may be interpreting the doc in the wrong way in which case would love to know what the right syntax is)

```python
legal_entity_data = { 'first_name': 'something', 'additional_owners': { 0: { 'first_name': 'LLL' }} }
account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
stripe_account = stripe.Account.create(type = 'custom', country = 'FR', account_token = account_token.id)

legal_entity_data = { 'first_name': 'another' }
account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
stripe_account = stripe.Account.retrieve(stripe_account['id'])   # Should be idempotent but just in case
stripe_account.account_token = account_token.id

del stripe_account.legal_entity.additional_owners
# ^
# This raises a KeyError even though the attribute does exit
# Same if I use stripe_account['legal_entity']['additional_owners']
# Btw being able to access properties both as attributes and dict keys smells a lot like magic
# and there seems to be some in `stripe_object.py`, from where the KeyError originates
#
# I also tried to set it to None but then the field is just not updated

stripe_account.save()
stripe_account = stripe.Account.retrieve(stripe_account['id'])   # Should be idempotent but just in case
assert(stripe_account['legal_entity']['first_name'] == 'another')   # Works, means the update did happen
assert(len(stripe_account['legal_entity']['additional_owners']) == 0)
```

This seems to be an issue with the lib given I was able to empty `additional_owners` with curl like so `curl https://api.stripe.com/v1/accounts/acct_1CFkpND1z7TNlJFl    -u MY_SECRET_KEY: -d legal_entity[additional_owners]=`

**Comment by ob-stripe** [comment]
Argh... I'm not surprised by issue 1. Encoding lists of dicts has always been a pain point (due to them being impossible unambiguously URL-encode) and we have special cases to transparently turn them into numerical-indexed dicts of dicts for parameters where users would expect to be able to pass lists of dicts. It didn't come up for account tokens until now though.

This should be relatively easy to fix, but in the meantime you can work around it by providing a dict of dicts yourself:
```python
legal_entity_data = { 'first_name': 'something', 'additional_owners': {0: { 'first_name': 'LLL' }} }
```

(Also, just to be clear: this is all for your tests, right? In production, account tokens must be created client-side.)

For issue 2, the proper way to unset an attribute is to set it to `None` before calling `save()`, not deleting it. I'm not sure if this is explicitly documented anywhere -- it's not specific to account objects.

> Btw being able to access properties both as attributes and dict keys smells a lot like magic

Yeeep. It's often convenient, but occasionally annoying / confusing. :)

**Comment by louischatriot** [comment]
On issue 1 this is what I ended up doing indeed (and yes this is just for testing purposes, in prod account tokens will be created client side).

On issue 2 I did try to use `None` but to no avail, I may be missing something but the following code does just that and still fails:

```python
legal_entity_data = { 'first_name': 'something', 'additional_owners': { 0: { 'first_name': 'LLL' }} }
account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
stripe_account = stripe.Account.create(type = 'custom', country = 'FR', account_token = account_token.id)

legal_entity_data = { 'first_name': 'another' }   #, 'additional_owners': None }
account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
stripe_account = stripe.Account.retrieve(stripe_account['id'])   # Should be idempotent but just in case
stripe_account.account_token = account_token.id

stripe_account.legal_entity.additional_owners = None
stripe_account.save()
stripe_account = stripe.Account.retrieve(stripe_account['id'])   # Should be idempotent but just in case

assert(stripe_account['legal_entity']['first_name'] == 'another')   # Works, means the update did happen
assert(len(stripe_account['legal_entity']['additional_owners']) == 0)
# ^
# Fails, the array still has length 1
# Still fails if legal_entity_data = { 'first_name': 'another', 'additional_owners': {} }
# Still fails if legal_entity_data = { 'first_name': 'another', 'additional_owners': { 0: {} } }
# But the additional_owners field can be updated if legal_entity_data = { 'first_name': 'another', 'additional_owners': { 0: { 'first_name': 'GGG' } } }
```

**Comment by louischatriot** [comment]
Ooooook so after some more testing this does seem like a bug in the API actually :)

The code above fails because it tries to modify the `legal_entity` in two different ways: through an account token (the `first_name` field) and through a direct modification (for `additional_owners`). So this code does empty `additional_owners`:
```python
legal_entity_data = { 'first_name': 'something', 'additional_owners': { 0: { 'first_name': 'LLL' } } }
account_token = stripe.Token.create( account = { 'legal_entity': legal_entity_data, 'tos_shown_and_accepted': True })
stripe_account = stripe.Account.create(type = 'custom', country = 'FR', account_token = account_token.id)

stripe_account.legal_entity.additional_owners = None
stripe_account.save()
stripe_account = stripe.Account.retrieve(stripe_account['id'])   # Should be idempotent but just in case
assert(len(stripe_account['legal_entity']['additional_owners']) == 0)
```

I think the issue is in the API as I could reproduce the behavior with curl: `curl https://api.stripe.com/v1/accounts/acct_1CFlVaFhmtJOxl3R    -u MY_KEY:   -d legal_entity[additional_owners]= -d account_token=ct_1CFlVdDapaWG7UYcsXRnjAIZ`

**Comment by ob-stripe** [comment]
Yeah, that's what I was thinking as well. The doc for account tokens does mention that account tokens cannot be used to unset existing values, but it should make it clearer that if you do need to unset an existing value, you need to do it in a separate request before updating the account with the new token.

**Comment by louischatriot** [comment]
I think enabling a full update of `additional_owners` through the token might be a better solution so as to keep code simple on the platform end no? As it stands it seems I have two choices: (i) track if this specific field has been modified before issuing an update, so that I may first reset it; (ii) just reset it everytime the legal entity is modified, and recreate it from scratch

(i) is tedious
(ii) runs the risk of Stripe having to re-KYC the additional owners?

I'm going with (ii) for now, hopefully this is actually not that much of an issue, provided our merchants don't make too many input mistakes :)

Thanks for your help!
