### ISSUE TITLE
Unable to create tiered plan

### ISSUE THREAD

**Issue by LukGerman** [stripe/stripe-python#428]
Hi, I think there is a bug that makes impossible to create tiered plan. I get `stripe.error.InvalidRequestError: Request req_LOnLLZfSssUA4c: Missing required param: tiers[2][up_to]`

This is my implementation:

```
stripe.Plan.create(**plan_data)
```

where `plan_data` is:

```
{
    'id': 'pro',
    'nickname': 'Pro',
    'product': 'prod_CrKOiwro4jMsHE',
    'amount': None,
    'interval': 'month',
    'interval_count': 1,
    'currency': 'usd',
    'billing_scheme': 'tiered',
    'tiers': [
        {
            'up_to': 1,
            'amount': 2900
        },
        {
            'up_to': 25,
            'amount': 0
        },
        {
            'up_to': None,
            'amount': 100
        }
    ],
    'tiers_mode': 'graduated',
    'transform_usage': None,
    'usage_type': 'metered'
}
```
As you can see, last tier should cover all values between previous tier's `up_to` and infinity, but API prohibits setting that. Also, after creating plan using Stripe dashboard, on receiving webhook `plan.created` event, `tiers` structure is the same, as the one that leads to above error.

Python 3.6, Stripe Python 1.80.0

**Comment by remi-stripe** [comment]
@LukGerman To define the upper bound for the tiers you have to pass `up_to: 'inf'` and not `None` as mentioned in the docs here: https://stripe.com/docs/api/python#create_plan-tiers-up_to
