### ISSUE TITLE
InvalidRequestError: Received unknown parameters - when updating Plan

### ISSUE THREAD

**Issue by LukGerman** [stripe/stripe-python#429]
Hello, updating Plan objects using heper library leads to some strange errors: `stripe.error.InvalidRequestError: Request req_pixrHjd0n6OE99: Received unknown parameters: amount, billing_scheme, currency, interval, interval_count, tiers, tiers_mode, transform_usage, usage_type`

This is how I try to update plan:
```
plan_in_stripe = self.stripe.Plan.retrieve(plan_data['id'])
plan_in_stripe.update(plan_data)
plan_in_stripe.save()
```

where `plan_data` is:

```
{
    'id': 'plan_CrL26Isb4h9Uxa',
    'nickname': 'Base',
    'product': 'prod_CrKOiwro4jMsHE',
    'amount': None,
    'interval': 'month',
    'interval_count': 1,
    'currency': 'usd',
    'billing_scheme': 'tiered',
    'tiers': [
        {
            'up_to': 1,
            'amount': 2900
        },
        {
            'up_to': 25,
            'amount': 0
        },
        {
            'up_to': None,
            'amount': 100
        }
    ],
    'tiers_mode': 'graduated',
    'transform_usage': None,
    'usage_type': 'metered'
}
```

Python 3.6, Stripe Python 1.82 & 1.80 & 1.79

**Comment by remi-stripe** [comment]
@LukGerman Can you clarify why you call both `update` on the plan and then save? Usually you either do update as a static method passing the plan id as a parameter or you call save after updating the relevant plans on the plan.

Also, if you look at the Plan Update [API](https://stripe.com/docs/api#update_plan), you'll see that none of those are allowed either.

I don't think there's a bug with the library here and the issue is instead in your code.

**Comment by adclose** [comment]
So I have a similar issue with this set of code
````
   args = request.args
   data = request.json
   method = stripe.PaymentMethod.retrieve(args['method_id'])
  method.update(data)
  result = method.save()
```
it breaks in the save method 
it brings back in the serializes method all of the calculated parameters (even though they are not in my update dict)
Then I get the error when it tries to submit them to the api with this error

stripe.error.InvalidRequestError: Request req_Gjj3baxJZ3KUES: Received unknown parameters: number, cvc, fingerprint, wallet, funding, three_d_secure_usage, brand, generated_from, networks, last4, checks, country

it seems like its not merging the dicts the right way to produce the parts that need to be send back to the api.

Is there a work around or a diffrent suggested code structure?

**Comment by remi-stripe** [comment]
@adclose The `save()` approach is mostly deprecated and here for legacy integrations. What it used to do was basically loop over every property on the object to find the ones that changed to then send them in the update request. If your code is explicitly overwriting the whole hash/resource then we would think you changed things like `billing_details` and then send those in the API.
I would recommend moving off of `save()` entirely here and using the `modify` method instead to directly update the exact params you want to pass.

**Comment by adclose** [comment]
@remi-stripe 
Thanks that worked perfectly and took fewer lines of code!
