### ISSUE TITLE
Error in updating customer

### ISSUE THREAD

**Issue by ziXet** [stripe/stripe-python#433]
After I upgrade to api version 2018-05-21 and stripe python package to 1.82.1 I'm receiving the following error when I want to update a customer. (e.g. email address)
```
{
    "error": {
        "code": "parameter_invalid_empty",
        "doc_url": "https://stripe.com/docs/error-codes/parameter-invalid-empty",
        "message": "You passed an empty string for 'shipping'. We assume empty values are an attempt to unset a parameter; however 'shipping' cannot be unset. You should remove 'shipping' from your request or supply a non-empty value.",
        "param": "shipping",
        "type": "invalid_request_error"
    }
}
```
Here is what I do:
```
stripe_customer = stripe_api.Customer.retrieve(customer_id)
stripe_customer.email = billing_email
stripe_customer.save()
```
I did not have any issue with the previous version.

**Comment by ziXet** [comment]
@remi-stripe You are right.
I just figured out that the caching is causing the issue. I'm using django-cacheops to cache the retrieved customer. Sorry for the false reporting.

**Comment by remi-stripe** [comment]
Glad we were able to clear this up!
