### ISSUE TITLE
OBJECT_NAME for InvoiceItem

### ISSUE THREAD

**Issue by jleclanche** [stripe/stripe-python#451]
While trying to implement dj-stripe/dj-stripe#503 I've been faced with this problem:

```
ValueError: Trying to fit a 'line_item' into a 'InvoiceItem'. Aborting.
```

I am trying to compare the `object` key with, ultimately, `StripeObject.OBJECT_NAME`. This works for everything except InvoiceItem.

InvoiceItem is defined with `invoiceitem` as `OBJECT_NAME`, and yet, in the API examples, it's `line_item`:

```json
{
      "id": "ii_1Cra7SEU4JBg99IS5hUcti1X",
      "object": "line_item",
      "amount": 1000,
      "currency": "usd",
      "description": "My First Invoice Item (created for API docs)",
      "discountable": true,
      "invoice_item": "ii_1Cra7SEU4JBg99IS5hUcti1X",
      "livemode": false,
      "metadata": {
      },
      "period": {
        "end": 1532475642,
        "start": 1532475642
      },
      "plan": null,
      "proration": false,
      "quantity": 1,
      "subscription": null,
      "type": "invoiceitem"
    },
```

What am I missing? Is `OBJECT_NAME` just wrong?

**Comment by jleclanche** [comment]
Okay I see, it can be both.

```json
{
  "id": "ii_1Cra7SEU4JBg99IS5hUcti1X",
  "object": "invoiceitem",
  "amount": 1000,
  "currency": "usd",
  "customer": "cus_DIASHRDZBnf0ww",
  "date": 1532475642,
  "description": "My First Invoice Item (created for API docs)",
  "discountable": true,
  "invoice": null,
  "livemode": false,
  "metadata": {
  },
  "period": {
    "start": 1532475642,
    "end": 1532475642
  },
  "plan": null,
  "proration": false,
  "quantity": 1,
  "subscription": null,
  "unit_amount": 1000
}
```

This feels impractical. Should I treat them as the same object? There's no concept of InvoiceLineItem in stripe-python.

**Comment by ob-stripe** [comment]
Hey @jleclanche. [Invoice line items](https://stripe.com/docs/api#invoice_line_item_object) and [invoice items](https://stripe.com/docs/api#invoiceitem_object) are two different (though related) objects.

Invoice items are regular API resources, so they have their matching class in the Python library (`stripe.InvoiceItem`).

Line items are simply nested objects that only appear within invoice objects. They don't have any API methods, so we never added a class for them. If we did, it would simply be a container for the attributes returned by the API when it returns an invoice object.

Do you think it would be useful to add such a class? We do have one in our PHP library (https://github.com/stripe/stripe-php/blob/master/lib/InvoiceLineItem.php), so there's some precedent for it.

**Comment by jleclanche** [comment]
In dj-stripe they're currently the same object type as well. I have a hard time wrapping my head around this seeing as I don't actually use these (I let the billing api take care of invoices automatically). Instinctively yes I think it would be useful, at least so I don't hardcode OBJECT_NAME :)

**Comment by jleclanche** [comment]
Related: https://github.com/dj-stripe/dj-stripe/issues/511

**Comment by jleclanche** [comment]
Note my confusion from over a year ago when I first hit that API. And now again as I hit it again :)
