### ISSUE TITLE
Retry mechanism for failing requests

### ISSUE THREAD

**Issue by jonathan-s** [stripe/stripe-python#464]
Whether stripe times out, there are other network issues or general randomness of the interwebz it's good to be able to retry. 

So I would suggest that you implement a retry mechanism as described here: https://gist.github.com/benjiao/28dc36bd87121b3273e0b3e079a8e8d8

Make it an optional parameter for when initializing the client with a sane default. That way the user of the library can customize it if they deem it necessary.

**Comment by brandur-stripe** [comment]
Yeah, it's a good idea to have something like this. I'm tagging this issue a "future" for now because I don't think we'll have anyone actively working on it right away, but it's open for implementation.
