### ISSUE TITLE
sources.all() error

### ISSUE THREAD

**Issue by dhararon** [stripe/stripe-python#465]
i dont see in changelog if .all() was deprecated 
```python
stripe.Customer.retrieve(customer).sources.all()
```
Error code
```
    stripe_response = stripe.Customer.retrieve(customer).sources.all()
  File "/home/vagrant/environment/venv/lib/python3.4/site-packages/stripe/stripe_object.py", line 85, in __getattr__
    raise AttributeError(*err.args)
AttributeError: all
```

can you tell me if is it a bug or was deprecated?.

thank you

**Comment by ob-stripe** [comment]
Hi @dhararon. All `.all()` methods were deprecated and replaced by `.list()` in version 2.0. Check out the [migration guide for v2](https://github.com/stripe/stripe-python/wiki/Migration-guide-for-v2#deprecated-methods).
