### ISSUE TITLE
Stripe community contributions?

### ISSUE THREAD

**Issue by leebenson** [stripe/stripe-python#475]
Not an issue, just wondering if there's a place to post community code contributions outside of the official API?

I wrote [stripe-xero-csv](https://github.com/leebenson/stripe-xero-csv) -- a Python CLI tool for creating Xero-compatible `.csv` bank statements -- and thought some folks might find it useful.

**Comment by remi-stripe** [comment]
@leebenson that's amazing! I'd recommend sharing this with our support team who will be able to share with right people internally to have a look.

**Comment by leebenson** [comment]
Thanks, will do!
