### ISSUE TITLE
AttributeError: type object 'UsageRecordSummary' has no attribute 'list'

### ISSUE THREAD

**Issue by jandebleser** [stripe/stripe-python#479]
When I run the the snippet from here: `https://stripe.com/docs/api/python#usage_record_summary_all`
I get the following error:
`AttributeError: type object 'UsageRecordSummary' has no attribute 'list'`

**Comment by remi-stripe** [comment]
@jandebleser sorry about the trouble here. At the moment, accessing usage record summaries is done through the parent (the corresponding subscription item) like this:

```
item = stripe.SubscriptionItem.retrieve('si_123')
summaries = item.usage_record_summaries()
```

I'll flag internally to fix the docs, thank you for the report.

**Comment by jandebleser** [comment]
Alright, thanks!
