### ISSUE TITLE
Unable to cancel stripe subscription at period end

### ISSUE THREAD

**Issue by IlianIliev** [stripe/stripe-python#485]
# Python 3.6.5
# stripe 2.10.1

According to the docs https://stripe.com/docs/billing/subscriptions/canceling-pausing I am doing the following:
```
stripe_subscription = stripe.Subscription.retrieve(self.stripe_id)
stripe_subscription.update(cancel_at_period_end=True)
```

However it throws an error: `TypeError: update() got an unexpected keyword argument 'cancel_at_period_end'`

I have managed to get it working by changing it to:

```
stripe_subscription = stripe.Subscription.retrieve(self.stripe_id)
stripe_subscription.update({'cancel_at_period_end': True})
stripe_subscription.save()
```

However either the code or the documentation need to be updated. 
However for I think it will it will be better if we can do the following:

```
subscription.cancel()  # cancels subscription immediately
subscription.cancel(at_period_end=True)  # cancels subscription at period end
```

Both methods should commit the change so there is no need to call `.save()` explicitly.

I am willing to provide a fix in a PR if this sounds good to you.

**Comment by ob-stripe** [comment]
Hi @IlianIliev, thanks for the report. Indeed, it looks like the documentation is incorrect.

You can either retrieve the subscription first and use `save()`, as you mentioned:
```python
stripe_subscription = stripe.Subscription.retrieve(self.stripe_id)
stripe_subscription.cancel_at_period_end = True
stripe_subscription.save()
```

Or you can use `modify()` to send an update request without retrieving the subscription first:
```python
stripe_subscription = stripe.Subscription.modify(self.stripe_id, {
  'cancel_at_period_end': True,
})

I will report this issue to our docs team and we will fix the documentation.

Since this is not an issue with the library, I'm closing the issue, but feel free to reply if needed!

**Comment by IlianIliev** [comment]
Hi @ob-stripe , and thank for the quick reply.

Yes, it is mostly an issue with the documentation but I had no idea where report it so I posted here.

Regarding the library itself - I still find the cancellation process a bit confusing. It uses `delete` to cancel a subscription, but the subscription is not actually deleted and just marked as cancelled. I checked the REST API and apparently this is the situation there (it uses the DELETE method) for cancelling it, so I can kind of understand why the library uses that method.
However I still think that having a `cancel` method will be more convenient and clear for developers so if you ever decide to go in that direction just ping me, I'll be happy to help )

**Comment by pbriet** [comment]
Documentation is still wrong

**Comment by ob-stripe** [comment]
Oops, looks like there was some internal miscommunication and this was never fixed. I've prepared a fix, the documentation should be updated with the correct request soon. Sorry for the inconvenience!

**Comment by pbriet** [comment]
No worries!  Thanks for your answer.

**Comment by ob-stripe** [comment]
The documentation is now fixed!
