### ISSUE TITLE
Wiki is publicly editable

### ISSUE THREAD

**Issue by jsuter** [stripe/stripe-python#488]
It looks like the footer on the wiki for this repo can be edited by anyone.

e.g. https://github.com/stripe/stripe-python/wiki/Migration-guide-for-v2

It should probably be locked down for security reasons (e.g. misleading documentation).

Edit: looks like most of the wiki can be edited by the public.

**Comment by remi-stripe** [comment]
@jsuter Wow thanks a lot for the heads up, I had no idea this was the default! I just went ahead and locked each one down so we should be all set! Let me know if you see anything amiss though!
