### ISSUE TITLE
invoice.send_invoice not working as intended?

### ISSUE THREAD

**Issue by ProjectImpactIO** [stripe/stripe-python#492]
When using invoice.send_invoice() on the Stripe Dashboard it says invoice sent via email but when I check my email, I did not receive anything.

**Comment by ProjectImpactIO** [comment]
To add, when I send the email manually through the Dashboard I will instantly receive the email.

**Comment by remi-stripe** [comment]
@ProjectImpactIO we do not send emails in Test mode when you use the API. You have the use the Dashboard for this.
