### ISSUE TITLE
Unable to use usage record

### ISSUE THREAD

**Issue by danish1010** [stripe/stripe-python#499]
I want to use Stripe's https://stripe.com/docs/api/usage_records/object?lang=python
But i don't see any function named UsageRecord
```
dir(stripe)

['APIConnectionError', 'APIError', 'APIRequestor', 
'APIResource', 'Account', 'ApplicationFee',
 'AuthenticationError', 'Balance', 
'BalanceTransaction', 'Card', 
'CardError', 'Charge', 'Coupon', 
'CreateableAPIResource', 'Customer', 'DeletableAPIResource',
 'Event', 'InvalidRequestError', 'Invoice', 
'InvoiceItem', 'ListObject', 'ListableAPIResource', 'Plan',
 'Recipient', 'SingletonAPIResource', 'StripeError', 
'StripeObject', 'StripeObjectEncoder', 'Subscription',
 'Token', 'Transfer', 'UpdateableAPIResource', 
'VERSION', '__builtins__', '__doc__', '__file__',
 '__name__', '__package__', '__path__', 
'api_base', 'api_key', 'api_version', 
'convert_to_stripe_object', 'json', 
'logger', 'verify_ssl_certs']
```

Python 2.7
Stripe API 1.19.0

Also is their a way i can upgrade to that specific version where its available.

**Comment by remi-stripe** [comment]
@danish1010 UsageRecord is a recent feature which was released earlier this year in [1.80.0](https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#1800---2018-04-24). Your version was released well over 4 years ago though so you will have to upgrade to at least 1.80.0 to get access to UsageRecord (and numerous other improvements).
