### ISSUE TITLE
Subscription Items Not Accessible

### ISSUE THREAD

**Issue by jakepoz** [stripe/stripe-python#504]
We have code such as this:

```
 active_subs = stripe.Subscription.list(status="active", customer=stripe_customer_id)

 for sub in active_subs:
        items = sub.items
        for item in items:
          print(item)
```

However, this throws an exception on the `for item in items` line with a `TypeError: 'builtin_function_or_method' object is not iterable`

If you just print the active_subs response, you see that the fully populated items are returned in the response, and you can even read them the values from the PyCharm debugger.

We are on python 3.6, and stripe python 2.14.0

**Comment by remi-stripe** [comment]
The issue is that `items` is a Python method so you can't use it. You have to do `items = sub['items']` instead!

**Comment by nZac** [comment]
@remi-stripe, This is an odd aspect of the dotted notation for `StripeObject` because it is a subclass of `dict` and `dict.items` is the way to iterate over key / values.  

Would it be possible to move subscription items to a new key, so that there is an obvious way grab them without running into the current `TypeError`?

At the very least, can we put a note in the [docs](https://stripe.com/docs/api/subscriptions/object?lang=python#subscription_object-items)?

**Comment by remi-stripe** [comment]
@nZac Changing the name would not be possible since it maps to the API resource itself and is the same in all our libraries. We definitely should improve the docs though and I made a note of this!

**Comment by js-beaulieu** [comment]
@remi-stripe  Is it documented anywhere as of today? I kind of figured the solution out after reading the source and trying stuff out, but I wish I didn't have to dig out this GitHub issue to get confirmation of this behavior.

**Comment by remi-stripe** [comment]
@js-beaulieu Unfortunately we don't have specific documentation for this at the moment, but I'll see if we can find a home for it. We're also hoping to introduce support for `LineItem` as a resource on Subscription in the future which will resolve this but it's more longer term.

**Comment by aegoff** [comment]
Could you please change the [documentation](https://stripe.com/docs/billing/subscriptions/integrating-customer-portal) on the website to indicate python's differences? I wanted to access my subscription's quantity, but it wouldn't work using: subscription.items.data[0].quantity
After stumbling upon this after a few hours, now I know why. 
subscription["items"].data[0].quantity
would give you quantity of a subscription in python.

**Comment by remi-stripe** [comment]
@aegoff sorry for the trouble. That code is more supposed to be "pseudo-code" and not copy-pasted but it's not clear that this isn't valid Python as a Python dev, while if you are in the PHP tab you know this is "pseudo-code" and not real PHP.
I'll see how we can make this clearer though as I agree it's confusing!

**Comment by xavdid-stripe** [comment]
We're soliciting feedback around some potential solutions to the `items` problem. There are breaking changes and tradeoffs in each direction, so we're hoping that hearing from developers can give us some direction. Please leave a comment if this is still relevant to you: https://github.com/stripe/stripe-python/issues/1454
