### ISSUE TITLE
Unable to update a given subscription from one metered plan to another

### ISSUE THREAD

**Issue by danish1010** [stripe/stripe-python#506]
**Stripe library version: 1.19.0**
**Python: 2.7**

When i am changing subscription from one metered plan to another metered plan. I edit the subscription object as mentioned below
```bash
// fetch the subscription object

subscription.plan = new_plan_id
subscription.save()
```

Issue is subscription.quantity is `None` as its a metered plan and i get this error `InvalidRequestError: Invalid integer:` when i do so. How do i update the subscription plan.

And if i set the quantity `subscription.quantity = 0` then i get the following error `InvalidRequestError: You cannot set the quantity for metered plans`

**Comment by ob-stripe** [comment]
Hi @danish1010. Could you provide the request ID (`req_...`) that appears in the `InvalidRequestError: Invalid integer:` exception?

Also, you're using a very old version of the stripe module. I recommend you upgrade to the latest version (2.15.0) if you can, or at least to the latest 1.x version (1.84.2). Can you give it a try and see if that solves the issue?

**Comment by danish1010** [comment]
@ob-stripe thanks. Will update the version and also try. But the Subscription.save() is basically the same in `1.19.01` and `1.84.2`. Let me also provide u the request ID

**Comment by ob-stripe** [comment]
Closing due to age, but feel free to reply if this is still an issue.
