### ISSUE TITLE
Filter list by custom attributes

### ISSUE THREAD

**Issue by holmberd** [stripe/stripe-python#509]
Does API support filtering a list by a custom attribute, e.g. if a  SKU has a custom attribute called `type` how would the arguments be constructed? `stripe.SKU.list(product='123', attributes_type='test')`

It feels like it should since you can perform that request with `curl`:
`curl https://api.stripe.com/v1/skus?limit=1 -d product=prod_1 -d attributes[type]=test ...`

![image](https://user-images.githubusercontent.com/13058304/49754447-f0b61d80-fc6a-11e8-9c55-e28724918d6b.png)

**Comment by ob-stripe** [comment]
Hi @holmberd. `attributes` should be a dictionary in this request, e.g.:

```python
skus = stripe.SKU.list(product='prod_123', attributes={'type': 'test'})
```

Since this isn't a bug or a feature request with the library, I'm closing the issue. If you have further questions, please reach out to support at https://support.stripe.com/email.
