### ISSUE TITLE
'_thread._local' object has no attribute 'session'

### ISSUE THREAD

**Issue by andreage** [stripe/stripe-python#533]
Since version 2.20.1 I get the following error when I call `stripe.Source.retrieve` (or any other function):

File "VIRTUALENV_PATH/lib/python3.5/site-packages/stripe/http_client.py" in request
  211.                 result = self._thread_local.session.request(

During handling of the above exception ('_thread._local' object has no attribute 'session'), another exception occurred:

[...]

File "VIRTUALENV_PATH/lib/python3.5/site-packages/stripe/http_client.py" in _handle_request_error
  288.         raise error.APIConnectionError(msg, should_retry=should_retry)

Going back to 2.20.0 works. Trying it from a Python shell works.

Stripe Python library: 2.20.1
Python: 3.5.3
requests: 2.21.0
Apache/2.4.25 (Debian) w. WSGI

**Comment by ob-stripe** [comment]
Hi @andreage, thanks for the report. I've managed to reproduce the issue, we should have a fix out promptly!

**Comment by brandur-stripe** [comment]
Sorry about the trouble here and thanks for reporting. We've released a fix in 2.20.2.
