### ISSUE TITLE
Invoice.list(customer=None) returns all invoices

### ISSUE THREAD

**Issue by kennell** [stripe/stripe-python#544]
Using version `2.21.0` doing the following:
```
import stripe
stripe.Invoice.list(customer=None)
```
will return all invoices, for all customers. Is this the intended behaviour? I feel like this should be a empty response.

**Comment by ob-stripe** [comment]
@kennell Yes, that's the expected behavior. Cf. https://stripe.com/docs/api/invoices/list?lang=python:
> You can list all invoices, or list the invoices for a specific customer.

Closing, but feel free to reply if needed.
