### ISSUE TITLE
stripe.Subscription.cancel raises an error

### ISSUE THREAD

**Issue by joshuamanns** [stripe/stripe-python#549]
Using Python v3.7
Using Stripe Python SDK v2.21.0

Calling `stripe.Subscription.cancel(subscription_id)` throws an error, but calling it via curl works.

```
stripe.Subscription.delete(stripe_subscription_id)
  File "~/.pyenv/versions/forest-server-37-2/lib/python3.7/site-packages/stripe/api_resources/abstract/deletable_api_resource.py", line 10, in delete
    self.refresh_from(self.request("delete", self.instance_url(), params))
AttributeError: 'str' object has no attribute 'refresh_from'
```

**Comment by ob-stripe** [comment]
@joshuamanns You need to be using the latest version of the `stripe` Python module (2.24.0) for this to work.

With older versions, you have to retrieve the subscription first, then call `delete` as an instance method:
```python
subscription = stripe.Subscription.retrieve(stripe_subscription_id)
subscription.delete()
```

With the latest version, you can call `delete()` as a class method with the subscription ID as the argument, avoiding the unnecessary retrieve request:
```python
stripe.Subscription.delete(stripe_subscription_id)
```

The documentation on Stripe's site was updated to be consistent with the latest version of the library.

Closing the issue, but feel free to reply or reach out to Stripe's support at https://support.stripe.com/email if you have any questions.
