### ISSUE TITLE
Stripe Create Person  function create_person does not exist

### ISSUE THREAD

**Issue by jmgamboa** [stripe/stripe-python#556]
Hi 

I am trying to create a Persons object to update identity verification parameters on accounts.

I am using the signature provided on the docs

`stripe.Account.create_person('account id', **kwargs)`

The error i am getting is `type object Account has no attribute 'create_person'

I when to search through the repository and found that this function is not unavailable anywhere but exists in the tests and exists in the stripe api docs. 

https://stripe.com/docs/api/persons/create

**Comment by jmgamboa** [comment]
updated package and its fine. getting a permission error now.

**Comment by remi-stripe** [comment]
@jmgamboa `create_person` was added in stripe-python 2.11.0 which is why you need to upgrade: https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#2110---2018-10-30
