### ISSUE TITLE
TaxRate percentage param

### ISSUE THREAD

**Issue by k90armstrong** [stripe/stripe-python#568]
I am trying to use the list method on the TaxRate and get results with a percentage param like so `stripe.TaxRate.list(percentage='1.0')` or `stripe.TaxRate.list(percentage=1)` not really sure because the documentation seems to be a little wrong see here: https://stripe.com/docs/api/tax_rates/list#list_tax_rates-percentage

When using the string '1.0' I get this error: `Invalid integer: 1.0`

When using an int I get this error: `Tax rates cannot be filtered by percentage.`

When using a dictionary with {"gte": 90} i get this error: `Tax rates cannot be filtered by percentage` 

Also it seems like the param `inclusive` is doing the same thing. `Tax rates cannot be filtered by inclusive`

I am running version 2.27.0

Please let me know if I am just doing something wrong or if this is a bug. Thanks!

**Comment by remi-stripe** [comment]
@k90armstrong It seems to be an issue with the API and not the library. I'm investigating and will reply back once I have more details

**Comment by k90armstrong** [comment]
@remi-stripe any word on this yet? Thanks!

**Comment by remi-stripe** [comment]
@k90armstrong No update for now unfortunately as we're working on fixing the API. I would recommend to ignore this filter for now and just list tax rates and filter on your end. I'll update this issue once the fix is deployed!

**Comment by richardm-stripe** [comment]
Update: `percentage` was removed in the next API version. Closing this issue since it didn't involve `stripe-python`.
