### ISSUE TITLE
stripe.PaymentIntent.confirm() should not be an instance method or docs are incorrect

### ISSUE THREAD

**Issue by benjhastings** [stripe/stripe-python#571]
I'm trying to confirm a PaymentIntent. The docs at https://stripe.com/docs/api/payment_intents/confirm and also at https://stripe.com/docs/payments/payment-intents/quickstart#manual-confirmation-flow show the following code:
```
import stripe
stripe.api_key = "<my secret key>"
intent = stripe.PaymentIntent.confirm('<payment_intent_id>',)
```

However, when I do that I get the following error:
```
     24 
     25     def confirm(self, idempotency_key=None, **params):
---> 26         url = self.instance_url() + '/confirm'
     27         headers = util.populate_headers(idempotency_key)
     28         self.refresh_from(self.request('post', url, params, headers))

AttributeError: 'str' object has no attribute 'instance_url
```
This is because `confirm` is an instance method rather than a `classmethod`.

The only way I could get this working was by doing the following:

```
import stripe
stripe.api_key = "<my secret key>"
intent = stripe.PaymentIntent('<payment_intent_id>').confirm()
```

I'm not sure whether this is because the docs are wrong or whether the `confirm` method should be a `classmethod` like `create`

**Comment by ob-stripe** [comment]
Hi @benjhastings. It's not obvious from just looking at the source code, but `PaymentIntent.confirm` is actually both a class and an instance method. The invocation shown in the API reference should work.

Which version of the `stripe` Python library are you using? If you're not already using it, can you try upgrading to the latest version (2.28.0)?

**Comment by attack68** [comment]
I faced the same issue as @benjhastings which led me here.

> Upgrading from 2.10.1 to 2.28 fixed the problem in my case.

**Comment by ob-stripe** [comment]
Thanks for confirming @attack68.

I'm closing the issue, but for anyone stumbling here in the future: please make sure that you're using stripe-python 2.24.0 or more recent. If you're still having trouble after upgrading, feel free to reply here or open a new issue.

**Comment by benjhastings** [comment]
Sorry for not replying to this sooner.  I was using version `2.10.1` (which was the latest that pip installed).  Just upgraded to `2.29.0` and it resolved the issue.

**Comment by alxpck** [comment]
I had a similar error with version `1.75.0` and upgrading to version `2.29.3` resolved the issue. Thanks!
