### ISSUE TITLE
Check webhook signature before constructing `Event` from the payload

### ISSUE THREAD

**Issue by rfk** [stripe/stripe-python#577]
Hi!

I happened to be poking around in the details of your webhook signature-checking code, and I noticed that it does some processing on the event payload before checking the signature, in particular calling `stripe.Event.construct_from` on the not-yet-authenticated data:

  https://github.com/stripe/stripe-python/blob/15d03381b3a3019517e7a31e1607bb5af0bda5a6/stripe/webhook.py#L23-L26

I don't have any reason to believe that this can be used to trigger bad behaviour, but `Event.construct_from` seems to do quite a lot of dynamic work to hydrate the data into live objects. Calling `WebhookSignature.verify_header` before doing that work could be a nice defense-in-depth measure against bugs elsewhere in the codebase.

Just a small suggestion that I wanted to pass along; thanks for providing this nice library, and for an API that seems to strongly encourage the webhook-handling code down the right path security-wise!

**Comment by ob-stripe** [comment]
Hi @rfk! You are entirely correct, we've made a similar change to most of our client libraries for other languages, but it looks like we never updated stripe-python.

I'll open a PR and we'll release a fix promptly. Thanks for bringing this to our attention!

**Comment by ob-stripe** [comment]
Fixed in 2.29.1.
