### ISSUE TITLE
Feature request: auto_paging_iter() using ending_before

### ISSUE THREAD

**Issue by WinnieP** [stripe/stripe-python#585]
It would be useful to support paginating backwards using `auto_paging_iter()` on listable resources. Currently, it assumes you're paginating forwards using `starting_after`. If you try to use it with `ending_before`, the library will attempt to use `starting_after` anyways on the last item's `id` and error out.

As a side note on consistency, the API returns an error message like "Received both starting_after and ending_before parameters. Please pass in only one." The documentation at https://stripe.com/docs/api/pagination claims that only ending_before is used in this case (although I think it's good that this is not the actual behavior).

**Comment by ob-stripe** [comment]
Hi @WinnieP, thanks for the suggestion! I think adding support for paginating backwards should be doable, I'll look into it.

Thanks for reporting the error in the documentation too, I'll pass that along. (And agreed that the actual behavior is better than what's being described!)

**Comment by ob-stripe** [comment]
Sorry for the late reply! stripe-python 2.38.0 now supports paginating backwards.
