### ISSUE TITLE
Plan.create product argument requires name

### ISSUE THREAD

**Issue by Kyle-Verhoog** [stripe/stripe-python#593]
Hi there,

In the Stripe official documentation (https://stripe.com/docs/api/plans/create) the `name` argument is not mentioned... but it is used in an example.

No `name` argument mentioned:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/6321485/61384218-287ae880-a87e-11e9-8e93-a0c4808fd25f.png">

`name` being used in the example:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/6321485/61384273-49dbd480-a87e-11e9-9eec-ab189afeeb58.png">

When trying to create a stripe plan as follows:

```python
stripe.Plan.create(
    # ... all other required fields
    product={
        id=my_product_id
    }
)
```

I get a
`stripe.error.InvalidRequestError: Request ...: Missing required param: product[name].`

**Comment by remi-stripe** [comment]
@Kyle-Verhoog Thanks for the report. Github issues should be limited to bugs with the python library so I'm going to close this out, but I flagged it internally to get this fixed. Don't hesitate to reach out to our support team if you have any follow up questions: https://support.stripe.com/contact

**Comment by Kyle-Verhoog** [comment]
Okay, seems like I overlooked this line: 
> This can either be the ID of an existing product, or a dictionary containing fields used to create a service product.

Maybe this can be made more clear? Perhaps two examples can be provided, both with creating a product and attaching to an existing product. Also, the wording in the docstrings for the fields could be made more clear that they are for a _new_ product, not an existing one.

I completely skipped over the crucial line since the dictionary documentation caught my attention.

**Comment by Kyle-Verhoog** [comment]
Thanks @remi-stripe I, _at the time_ did think it was a bug in the python library due to the missing argument error.

**Comment by remi-stripe** [comment]
Yeah I totally agree this can be confusing. It's one of the limitation of our examples today where we only show one. Hopefully something we can fix in the future to make it easier to see various ways an API can be used!
