### ISSUE TITLE
Retrieving a bank account requires 2 requests to the API when a single one would be enough

### ISSUE THREAD

**Issue by mobiware** [stripe/stripe-python#594]
The API documentation shows that a `Bank Account` can be retrieved using a single HTTP API request:
https://stripe.com/docs/api/customer_bank_accounts/retrieve?lang=curl
```
curl https://api.stripe.com/v1/customers/cus_XYZ/sources/ba_XYZ \
  -u sk_test_XYZ:
```

However the sample code for the same action using the Python SDK translates to 2 requests to the HTTP API:
https://stripe.com/docs/api/customer_bank_accounts/retrieve?lang=python
```
import stripe
stripe.api_key = "sk_test_XYZ"

customer = stripe.Customer.retrieve('cus_XYZ')
bank_account = customer.sources.retrieve('ba_XYZ')
```

The 1st HTTP request (retrieving the full `Customer` object) is not necessary when one only wants to get a particular `Bank Account`

We would need a method in the Python SDK that takes both a `Customer` ID and a `Bank Account` ID and returns the corresponding `Bank Account` object in a single HTTP API request.

**Comment by remi-stripe** [comment]
@mobiware You can use `retrieveSource` to do this in one call:

```
import stripe
stripe.api_key = "sk_test_XYZ"

bank_account = stripe.Customer.retrieveSource('cus_XYZ', 'ba_XYZ')
```

**Comment by mobiware** [comment]
Awesome, thanks a lot !
