### ISSUE TITLE
Invoice Settings on Subscription

### ISSUE THREAD

**Issue by brymcg** [stripe/stripe-python#608]
When I modify Accepted Payment Methods on a subscription through the dashboard I can see that there is an "invoice_settings" section in the subscription object:

<img width="318" alt="sub_invsettings" src="https://user-images.githubusercontent.com/6333380/64295403-48e62b80-cf2e-11e9-9d33-5850e8ce7048.png">

However, this is not in the API documentation nor can I get at it in any way. It is just not supported? Is that on a road map?

**Comment by remi-stripe** [comment]
@brymcg Unfortunately, this is not supported in the API today and can only be set through the Dashboard. It's something we want to support in the future but we don't have a clear timeline just yet. I would recommend reaching out to our support team to discuss this: https://support.stripe.com/contact
