### ISSUE TITLE
The underlying error was: wrap_socket() got an unexpected keyword argument '_context'

### ISSUE THREAD

**Issue by archienorman11** [stripe/stripe-python#628]
Confirmed that the latest version of `requests` is being used. 

```(Network error: A TypeError was raised with error message Warning: It looks like your installed version of the "requests" library is not compatible with Stripe's usage thereof. (HINT: The most likely cause is that your "requests" library is out of date. You can fix that by running "pip install -U requests".) The underlying error was: wrap_socket() got an unexpected keyword argument '_context')```

```Unexpected error communicating with Stripe. It looks like there's probably a configuration issue locally.  If this problem persists, let us know at support@stripe.com.```

**Comment by ob-stripe** [comment]
Hi @archienorman11. Can you share more information about your environment? In particular, the following would help:
- OS and version
- exact version number of the Python interpreter
- exact version number of the `stripe` module
- exact version number the `requests` module

**Comment by archienorman11** [comment]
`Docker-compose: version: "3"`
`Python: 3.7.2`
`requests==2.22.0`
`stripe==2.38.0` (tested with the 3 most recent versions of stripe)

thanks @ob-stripe

**Comment by ob-stripe** [comment]
Are you using eventlet? It looks like this error could be caused by `eventlet.monkey_patch()` (https://github.com/eventlet/eventlet/issues/526).

**Comment by archienorman11** [comment]
Yes I am using eventlet, strange because everything was working fine a couple of days ago. ill try to find out what has changed. Thanks @ob-stripe

**Comment by archienorman11** [comment]
@ob-stripe downgrading to python 3.6 resolved the issue for me. thanks for your support.
