### ISSUE TITLE
Checkout Session object: It makes more sense to allow Negative Amount in "line_items"

### ISSUE THREAD

**Issue by hust-whw** [stripe/stripe-python#629]
There is a scenario in my use where, due to some discount coupon or product combination discount, a **negative amount** should be allowed to append in "line_items" when create the Checkout Session object. Because discounts are supposed to appear in the checkout build-in page by stripe or the customers will never know how the total price came from (The total amount should still be limited to a positive number).

Or, on the other hand, allowing **Stripe Coupon Object** to Checkout feather makes more sence as well.

**Comment by remi-stripe** [comment]
@hust-whw Github issues on the library should be limited to bugs with the library itself. Those are more product questions (and feedback). 

Adding support for coupons on Checkout is definitely on our roadmap and something we want to ship in the future. We don't yet support this though for now!

If you have any follow-up questions, make sure to reach out to our support team instead: https://support.stripe.com/contact
