### ISSUE TITLE
Unable to retrieve metadata when running in docker container

### ISSUE THREAD

**Issue by marty331** [stripe/stripe-python#638]
My app (Flask) is live and works correctly in deployed environments (AWS lambda) however I for running locally I spin up a series of Docker containers.  In all of my API retrieve calls within the Docker container the metadata fields are always empty.  So far I have confirmed this issue exists on Customers, Subscriptions, and Products.

Example calls are structured such:
`stripe.Customer.retrieve("cus_mycustomer")` and I receive the customer object back, but the metadata portion is always empty.  Is there a fix for this?  I've already reached out in IRC and was told this is not an issue, however it continues to happen.

**Comment by remi-stripe** [comment]
@marty331 It would be surprising if this was an issue with the library itself. Are you sure that the objects you are retrieving currently have metadata set on them? Do you have an example object you could share, for example in Test mode and some code to reproduce the issue, for example by creating a customer with metadata and immediately fetching it to compare?
Separately, what is your Python version and your stripe-python version?

**Comment by marty331** [comment]
> @marty331 It would be surprising if this was an issue with the library itself. Are you sure that the objects you are retrieving currently have metadata set on them? Do you have an example object you could share, for example in Test mode and some code to reproduce the issue, for example by creating a customer with metadata and immediately fetching it to compare?
> Separately, what is your Python version and your stripe-python version?

I'm 100% sure I have metadata set on all of these objects.  My Python version is 3.7 and my stripe-python is version 2.41.1

I do have an example (test) object I can share, are you wanting just a customer id or a full object?  How do you want me to share, paste in here or a different way?

**Comment by remi-stripe** [comment]
If it's just test mode, sharing your exact code to reproduce would be helpful with a relevant object I could look at. Otherwise, contacting the support team directly is likely the better option since they have direct access to your account and can look at your logs (and show them to you). You can contact them here: https://support.stripe.com/contact

**Comment by marty331** [comment]
@remi-stripe Here you go:
Here is the relevant Customer retrieve call we use.
`from stripe import Customer, Subscription, Charge, Invoice, Plan, Product, api_key
from stripe.error import (
    InvalidRequestError,
    APIConnectionError,
    APIError,
    CardError,
    RateLimitError,
    IdempotencyError,
    StripeErrorWithParamCode,
    AuthenticationError,
)
...
def retrieve_stripe_customer(customer_id: str) -> Optional[Customer]:
    """
    Retrieve Stripe Customer
    :param customer_id:
    :return: Customer
    """
    try:
        customer = Customer.retrieve(id=customer_id)
        logger.debug("retrieve stripe customer", customer=customer)
        return customer
    except (
        InvalidRequestError,
        APIConnectionError,
        APIError,
        RateLimitError,
        StripeErrorWithParamCode,
    ) as e:
        logger.error("retrieve stripe customer error", error=e)
        raise e`

and the actual call where customer_id = 'cus_GNXQwWObWf8NwZ':
`        try:
            customer = vendor.retrieve_stripe_customer(customer_id=customer_id)

        except InvalidRequestError as e:
            logger.error("Unable to find customer", error=e)
            raise e`
and finally the resulting customer object:
`"customer": {"address": null, "balance": 0, "created": 1234567890, "currency": "usd", "default_source": null, "delinquent": false, "description": null, "discount": null, "email": null, "id": "cus_GNXQwWObWf8NwZ", "invoice_prefix": "458ADC5", "invoice_settings": {"custom_fields": null, "default_payment_method": null, "footer": null}, "livemode": false, "metadata": {}, "name": null, "object": "customer", "phone": null, "preferred_locales": [], "shipping": null, "sources": {"data": [{"created": 1234567890, "customer": null, "fingerprint": "KmWIKfWrblk2LFwu", "id": "aliacc_1FcJiDGMZ7bZIeITe0tGv7RN", "livemode": false, "metadata": {}, "object": "alipay_account", "payment_amount": 1000, "payment_currency": "usd", "reusable": false, "used": false, "username": "test@example.com"}], "has_more": false, "object": "list", "url": "/v1/customers/cus_GNXQwWObWf8NwZ/sources"}, "subscriptions": {"data": [{"application_fee_percent": null, "billing_cycle_anchor": 1234567890, "billing_thresholds": null, "cancel_at": 1234567890, "cancel_at_period_end": false, "canceled_at": 1234567890, "collection_method": "charge_automatically", "created": 1234567890, "current_period_end": 1234567890, "current_period_start": 1234567890, "customer": "cus_GNXQwWObWf8NwZ", "days_until_due": null, "default_payment_method": null, "default_source": null, "default_tax_rates": [], "discount": null, "ended_at": 1234567890, "id": "sub_G8auRBhnxWG8VU", "invoice_customer_balance_settings": {"consume_applied_balance_on_void": true}, "items": {"data": [{"billing_thresholds": null, "created": 1573166661, "id": "si_G8auhfS0JyULQv", "metadata": {}, "object": "subscription_item", "plan": {"active": true, "aggregate_usage": null, "amount": 2000, "amount_decimal": "2000", "billing_scheme": "per_unit", "created": 1573165323, "currency": "usd", "id": "gold", "interval": "month", "interval_count": 1, "livemode": false, **"metadata": {}**, "nickname": null, "object": "plan", "product": "prod_G8aXHNsyixFgjW", "tiers": null, "tiers_mode": null, "transform_usage": null, "trial_period_days": null, "usage_type": "licensed"}, "quantity": 1, "subscription": "sub_G8au5oWVgTnZej", "tax_rates": []}], "has_more": false, "object": "list", "url": "/v1/subscription_items?subscription=sub_G8auRBhnxWG8VU"}, "latest_invoice": null, "livemode": false, "metadata": {}, "next_pending_invoice_item_invoice": 1234567890, "object": "subscription", "pending_invoice_item_interval": null, "pending_setup_intent": null, "plan": {"active": true, "aggregate_usage": null, "amount": 2000, "amount_decimal": "2000", "billing_scheme": "per_unit", "created": 1573165323, "currency": "usd", "id": "gold", "interval": "month", "interval_count": 1, "livemode": false, "metadata": {}, "nickname": null, "object": "plan", "product": "prod_G8aXHNsyixFgjW", "tiers": null, "tiers_mode": null, "transform_usage": null, "trial_period_days": null, "usage_type": "licensed"}, "quantity": 1, "start_date": 1234567890, "status": "active", "tax_percent": null, "trial_end": 1234567890, "trial_start": 1234567890}], "has_more": false, "object": "list", "url": "/v1/customers/cus_GNXQwWObWf8NwZ/subscriptions"}, "tax_exempt": "none", "tax_ids": {"data": [{"country": "DE", "created": 1234567890, "customer": "cus_GNXQwWObWf8NwZ", "id": "txi_123456789", "livemode": false, "object": "tax_id", "type": "eu_vat", "value": "DE123456789", "verification": {"status": "pending", "verified_address": null, "verified_name": null}}], "has_more": false, "object": "list", "url": "/v1/customers/cus_GNXQwWObWf8NwZ/tax_ids"}, "tax_info": null, "tax_info_verification": null}`

**Comment by marty331** [comment]
Here is the same customer, but I'm retrieving it directly from the python repl calling stripe.Customer.retrieve:
`<Customer customer id=cus_GNXQwWObWf8NwZ at 0x10cab5410> JSON: {
  "account_balance": 0,
  "address": null,
  "balance": 0,
  "created": 1576613356,
  "currency": "usd",
  "default_source": "card_1FqmNAJNcmPzuWtRf9QSnYrL",
  "delinquent": false,
  "description": "fab_1217a",
  "discount": null,
  "email": "fab_1217a@testmail.com",
  "id": "cus_GNXQwWObWf8NwZ",
  "invoice_prefix": "0C100B86",
  "invoice_settings": {
    "custom_fields": null,
    "default_payment_method": null,
    "footer": null
  },
  "livemode": false,
  "metadata": {
    "userid": "fab_1217a"
  },
  "name": "Santa Claus",
  "object": "customer",
  "phone": null,
  "preferred_locales": [],
  "shipping": null,
  "sources": {
    "data": [
      {
        "address_city": null,
        "address_country": null,
        "address_line1": null,
        "address_line1_check": null,
        "address_line2": null,
        "address_state": null,
        "address_zip": null,
        "address_zip_check": null,
        "brand": "Visa",
        "country": "US",
        "customer": "cus_GNXQwWObWf8NwZ",
        "cvc_check": null,
        "dynamic_last4": null,
        "exp_month": 12,
        "exp_year": 2020,
        "fingerprint": "eYFLxJ8weKg24R6o",
        "funding": "credit",
        "id": "card_1FqmNAJNcmPzuWtRf9QSnYrL",
        "last4": "4242",
        "metadata": {},
        "name": null,
        "object": "card",
        "tokenization_method": null
      }
    ],
    "has_more": false,
    "object": "list",
    "total_count": 1,
    "url": "/v1/customers/cus_GNXQwWObWf8NwZ/sources"
  },
  "subscriptions": {
    "data": [
      {
        "application_fee_percent": null,
        "billing": "charge_automatically",
        "billing_cycle_anchor": 1576613424,
        "billing_thresholds": null,
        "cancel_at": null,
        "cancel_at_period_end": false,
        "canceled_at": null,
        "collection_method": "charge_automatically",
        "created": 1576613424,
        "current_period_end": 1579291824,
        "current_period_start": 1576613424,
        "customer": "cus_GNXQwWObWf8NwZ",
        "days_until_due": null,
        "default_payment_method": null,
        "default_source": null,
        "default_tax_rates": [],
        "discount": null,
        "ended_at": null,
        "id": "sub_GNXSiQH6mRwZ0D",
        "invoice_customer_balance_settings": {
          "consume_applied_balance_on_void": true
        },
        "items": {
          "data": [
            {
              "billing_thresholds": null,
              "created": 1576613425,
              "id": "si_GNXSuzMFydNjf1",
              "metadata": {},
              "object": "subscription_item",
              "plan": {
                "active": true,
                "aggregate_usage": null,
                "amount": 499,
                "amount_decimal": "499",
                "billing_scheme": "per_unit",
                "created": 1573274041,
                "currency": "usd",
                "id": "plan_G93lTs8hfK7NNG",
                "interval": "month",
                "interval_count": 1,
                "livemode": false,
                "metadata": {},
                "nickname": "Basic FPN",
                "object": "plan",
                "product": "prod_G93l8Yn7XJHYUs",
                "tiers": null,
                "tiers_mode": null,
                "transform_usage": null,
                "trial_period_days": null,
                "usage_type": "licensed"
              },
              "quantity": 1,
              "subscription": "sub_GNXSiQH6mRwZ0D",
              "tax_rates": []
            }
          ],
          "has_more": false,
          "object": "list",
          "total_count": 1,
          "url": "/v1/subscription_items?subscription=sub_GNXSiQH6mRwZ0D"
        },
        "latest_invoice": "in_1FqmNAJNcmPzuWtRdBuwIDLn",
        "livemode": false,
        "metadata": {
          "plan_change_date": "1576614865",
          "previous_plan_id": "plan_G93mMKnIFCjZek"
        },
        "next_pending_invoice_item_invoice": null,
        "object": "subscription",
        "pending_invoice_item_interval": null,
        "pending_setup_intent": null,
        "plan": {
          "active": true,
          "aggregate_usage": null,
          "amount": 499,
          "amount_decimal": "499",
          "billing_scheme": "per_unit",
          "created": 1573274041,
          "currency": "usd",
          "id": "plan_G93lTs8hfK7NNG",
          "interval": "month",
          "interval_count": 1,
          "livemode": false,
          "metadata": {},
          "nickname": "Basic FPN",
          "object": "plan",
          "product": "prod_G93l8Yn7XJHYUs",
          "tiers": null,
          "tiers_mode": null,
          "transform_usage": null,
          "trial_period_days": null,
          "usage_type": "licensed"
        },
        "quantity": 1,
        "schedule": null,
        "start": 1576614865,
        "start_date": 1576613424,
        "status": "active",
        "tax_percent": null,
        "trial_end": null,
        "trial_start": null
      }
    ],
    "has_more": false,
    "object": "list",
    "total_count": 1,
    "url": "/v1/customers/cus_GNXQwWObWf8NwZ/subscriptions"
  },
  "tax_exempt": "none",
  "tax_ids": {
    "data": [],
    "has_more": false,
    "object": "list",
    "total_count": 0,
    "url": "/v1/customers/cus_GNXQwWObWf8NwZ/tax_ids"
  },
  "tax_info": null,
  "tax_info_verification": null
}`

**Comment by remi-stripe** [comment]
@marty331 Can you clarify how you print the customer exactly? Could you also try printing this
```
customer.last_response.body
```
to see what the API returns (no need to post the whole output for that one, more confirmation that metadata is here (or isn't)

**Comment by remi-stripe** [comment]
@marty331 I looked into it a bit more internally. It _seems_ like the requests you're making outside of the REPL are not getting to Stripe, at least not directly. What I see is requests made with no user agents, as if something in the middle was interfering. Do you maybe have a proxy service or similar that is between your code and our servers that could alter the response?

**Comment by marty331** [comment]
@remi-stripe I think you are correct, since this code is being routed into a docker container of of the other devs had activated `stripe.api_base = (
            stripe.upload_api_base
        ) = f"https://{MOCK_HOST}:{MOCK_PORT}"`
after bypassing this correctly, then I'm getting the metadata.  Sorry for the false alarm and thank you for trying to help me out.

**Comment by remi-stripe** [comment]
Oh neat, glad you were able to figure this one out already!
