### ISSUE TITLE
stripe.OAuth.token doesn't offer a way to override global api_key

### ISSUE THREAD

**Issue by jarcoal** [stripe/stripe-python#645]
Unlike most of the stripe object methods, [stripe.OAuth.token](https://github.com/stripe/stripe-python/blob/598566add896a571088c76acc073a8243afbbfb2/stripe/oauth.py#L39-L43) doesn't offer a way to pass in an `api_key` to override the global API key.

This capability is necessary to generate test access tokens from a production refresh token: https://stripe.com/docs/connect/testing#test-keys-for-livemode-applications

**Comment by remi-stripe** [comment]
@jarcoal Thanks for the report! We'll look into fixing this.

You should not have to make this call today in your integration though. When you connect an account to your platform in Live mode you automatically get access to Test mode on their account. Most integrations should be using the platform's API request and pass the connected account id in the `Stripe-Account` header instead as documented [here](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header). This should unblock you and remove the need to make that call.

**Comment by ob-stripe** [comment]
Fixed in 2.44.0.

**Comment by jarcoal** [comment]
@remi-stripe @ob-stripe Thanks for the quick action here!

As for the `Stripe-Account` header, I didn't understand how to use that at first, but after some playing around with it today I see how it's easier than juggling access tokens.  I'll move forward with that technique.

Thanks again!
