### ISSUE TITLE
It's not really clear what the limit paramer in stripe.Model.list() do

### ISSUE THREAD

**Issue by PabloCastellano** [stripe/stripe-python#654]
Hello. Not sure if it's a bug or a feature.

I've been reading the Pagination documentation and specially the [Auto pagination](https://stripe.com/docs/api/pagination/auto) section and I'm confused now.

The example shown is the following one

```
customers = stripe.Customer.list(limit=3)
for customer in customers.auto_paging_iter():
  # Do something with customer
```

I read it as "I want to get just 3 customers". And in fact, `stripe.Customer.list(limit=3)` returns a list of 3 objects. However calling `auto_paging_iter()` right after that, loops over **all pages** and ends up returning **all** customers.

https://github.com/stripe/stripe-python/blob/036f258ddcdd01a2900146a090fc205f9faf612a/stripe/api_resources/list_object.py#L106-L123

For my use case I just want to limit the number of results, that is, getting the most recent N stripe Events. And I want to easily auto paginate over that list. How can I do it? 

And if limit is not understood as the limit of results, but the limit of results **in each page**... then what is the point of using a limit and then iterating over all pages as show in the example?

The documentation section also says:

> To use the auto-pagination feature in Python, simply issue an initial "list" call with the parameters you need, then call auto_paging_iter() on the returned list object to iterate over all objects matching your initial parameters.

auto_paging_iter() is definitely not honouring my initial parameters!

Cheers

**Comment by remi-stripe** [comment]
@PabloCastellano The `limit` parameter is specifically to limit the number of object per page today. So in your example, you would fetch a page with 3 customers, and then you loop over that list. For the first 3 customers we use the ones in that page. For the fourth customer we know we need a new page so we fetch a new page of 3 customers.

The reason you would want to do this, is usually to handle latency better. Fetching 100 objects, sometimes while expanding other related objects, can take some time to complete. Limiting the number of objects allows you to get the first page faster, especially if the information you are looking for is already in that page.

If you want to get a certain amount of objects back, the easiest solution is to paginate but count the number of objects you've processed and then stop the loop once you have processed enough.

Hope this clarifies the feature!

**Comment by PabloCastellano** [comment]
@remi-stripe Thanks for clarifying!

Since I found this confusing I think other users might find it too. I recommend adding a small clarification also in the documentation page and an example piece of code to fetch only N objects, but up to you!

Feel free to close this issue
