### ISSUE TITLE
Module 'stripe' has no 'Price' memberpylint(no-member)

### ISSUE THREAD

**Issue by leeadh** [stripe/stripe-python#659]
I am able to create a stripe charge and stripe payment intent. however when I try to do stripe.price it keeps throwing me this error. I have already ensured that my file is not named stripe (its called sample.py). Whats wrong

**Comment by remi-stripe** [comment]
@leeadh the `Price` resource has been added to the API recently. It shipped in stripe-python in the version 2.47.0 [changelog](https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#2470---2020-04-29). You need to make sure you upgrade your code to use the most recent version of stripe-python and it will work.
