### ISSUE TITLE
Auto paginator in rare case attempts to call next on list object even though has_more should be false

### ISSUE THREAD

**Issue by asaf-erlich** [stripe/stripe-python#661]
I'm a developer from [Stitch](https://www.stitchdata.com/) where I am helping to diagnose an issue one of our shared customers has running our [tap-stripe code](https://app.circleci.com/pipelines/github/singer-io/tap-stripe) to download stripe data. There is a request made by the auto paginator which fails with the error:
```
Request req_zbWCK7axFicC3v: Old `id` values cannot be used to specify an invoice line item in this API version. Please use the current value of the `id` field of the invoice line item object.
```
This occurs when the previous list request using curl returns the following (wrote ... / REDACTED for a lot of values, not 100% sure what customer data is public / private exactly):
```
curl -H 'Stripe-Account: REDACTED' -H 'Stripe-Version: 2018-0
9-24' -u REDACTED: -G 'https://api.stripe.com/v1/invoices/<REDACTED>/lines?limit=100'
{
  "object": "list",
  "data": [
    ...
  ],
  "has_more": false,
  ...
}
```
But I put a debugger in the python sdk in the next_page method and when printing self I get:
```
self
<ListObject list at 0x7fce04929f48> JSON: {
  "data": [
    ...
  ],
  "has_more": true,
  "object": "list",
  "total_count": 11,
  ...
}
```
Note the "has_more" is different. It looks like a bug in the python sdk to me. Let me know if you need more information to reproduce this. I can reach out to the shared customer to ask for their information for you. A support ticket is an option as well.

Python version: 3.5.2
Python stripe library version: 2.48.0 (also tested earlier on 2.10.1, but we tried upgrading to see if that fixes it)

**Comment by remi-stripe** [comment]
@asaf-erlich Thanks for reaching out! I think this one will be a bit tricky to debug without seeing raw data that is returned by each call. I think your product is pinned to a really old API version today, from before line items had unique ids too and I wonder if you're hitting an edge-case.

First, could you confirm this happens even when you explicitly force the most recent API version in the call? Just to make sure whether it's related to an API version change.

Second, if it does still happen I think the best option is to contact our support team, link to this thread and provide the raw JSON you see for each page. This would allow us to debug more actively while also looking at the logs we see on our end.

**Comment by asaf-erlich** [comment]
I just an a support email linking to this github issue. I'm happy to include full requests, but I was worried if it's including any client secret / private data they don't want to share. I did mention above that we we tried running this after upgrading to the latest python stripe library version 2.48.0 .

**Comment by asaf-erlich** [comment]
That sounds like a good idea. We can try that.

**Comment by remi-stripe** [comment]
@asaf-erlich Is this issue still ongoing on your end?

**Comment by asaf-erlich** [comment]
@remi-stripe we still have a backlog ticket to address this. If you would like to close this you may and we we can re-open or submit a new ticket if we finish the update and still find further issues.

**Comment by remi-stripe** [comment]
Sounds good, I'm going to close for now but just reopen this ask if you find more details!
