### ISSUE TITLE
API is not the same as the other methods

### ISSUE THREAD

**Issue by victorct-pronto** [stripe/stripe-python#663]
In your [documentation](https://stripe.com/docs/api/versioning?lang=python) says that in order to use multiple api versions you have to use `stripe_version` as a parameter to a function, but in the `File` class the  `create` method follows a different convention and the parameter is called `api_version` I think it should follow what is already posted on the documentation

https://github.com/stripe/stripe-python/blob/d3835ab73fcb8270d68e99ccc19fe2f21465b312/stripe/api_resources/file.py#L29

**Comment by victorct-pronto** [comment]
Python Version: 2.48.0

**Comment by remi-stripe** [comment]
@victorct-pronto Thanks for the report! We'll get this one fixed!

**Comment by remi-stripe** [comment]
closing as @richardm-stripe got this fixed in 2.49.0
