### ISSUE TITLE
Unable to access stripe error classes

### ISSUE THREAD

**Issue by crazyberry7** [stripe/stripe-python#668]
Maybe I'm missing something, but stripe/__init__.py is missing an import statement for error.py

e.g. "from error.py import *"

**Comment by remi-stripe** [comment]
@crazyberry7 Thanks for reaching out! That one is expected on our end and you need to explicitly import those from `stripe.error`. This is to ensure that we keep the top-level classes for API resources separate from the classes for errors.

**Comment by crazyberry7** [comment]
Thanks for the quick reply! Cheers!
