### ISSUE TITLE
Basic tests which dont depend on stripe-mock

### ISSUE THREAD

**Issue by jayvdb** [stripe/stripe-python#670]
Would it be possible to re-arrange the test harness so that stripe-mock is optional, so that some basic tests can be run without it?

This would be helpful for distro packaging, where basic tests can catch basic packaging / dependency problems, and creating packages for stripe-mock is a tough ask as it is not useful for normal users, and would only exist to support a single commercial use, possibly multiple packages only if stripe packages are created for multiple languages.

fwiw, I have been maintaining https://build.opensuse.org/package/show/home:jayvdb:django/python-stripe for quite a while, and been unable/unwilling to submit it to the main Python package repository because of the package isnt testable.

Worth noting that Redhat has `perl-Business-Stripe`, but not `python-stripe`.  `*`BSD does have py*-stripe.  None have stripe-mock, so any package they have is untested.  So there is broad interest in having packaging, but lack of motivation to create arch specific packages in Go for a Python package.

**Comment by jayvdb** [comment]
Another alternative would be to have a package which uses the Python stripe library, and does have a Python based mock test suite that gets deep enough into stripe that it exercises enough of the stripe library to confirm it is 'functional'.  Then distros could package both, and use the latter to verify the former.

**Comment by jayvdb** [comment]
Another alternative would be to have a package which uses the Python stripe library, and does have a Python based mock test suite that gets deep enough into stripe that it exercises enough of the stripe library to confirm it is 'functional'.  Then distros could package both, and use the latter to verify the former.

**Comment by suz-stripe** [comment]
Hi @jayvdb, thanks for reporting this difficulty with running the test suite without Stripe Mock. Your request makes sense so we're looking into a possible workaround for you and will report back shortly.

**Comment by suz-stripe** [comment]
Hi @jayvdb I'm writing again to let you know that we just merged #672 which allows you to run `make test-nomock` in order to run a percentage of our tests that do not need stripe-mock installed and running. We hope this is a good workaround for you and of course it goes without saying that we welcome any further feedback if you have it.

I hope you're having a great day!

**Comment by jayvdb** [comment]
Much appreciated.  I'll try this when a new release is pushed out.

**Comment by jayvdb** [comment]
Re-submitted stripe to openSUSE package collection: https://build.opensuse.org/request/show/850230

ftr, `pytest --nomock` is how to enable this new feature.
