### ISSUE TITLE
Checkout-Session: You can not pass `allow_promotion_codes` in `payment` mode.

### ISSUE THREAD

**Issue by fabianriewe** [stripe/stripe-python#675]
Hi,
we are creating a Checkout-Session with a variable mode (payment or subscription). I set `allow_promotion_codes` to `True` and noticed, that I got the following error when creating a session in payment mode:
`
stripe.error.InvalidRequestError: Request req_PgDTvYMLHdG9Ph: You can not pass 'allow_promotion_codes' in 'payment' mode.
`

Note: There is no information in the documentation that you can't use this parameter in payment mode (https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-allow_promotion_codes)

When using the `subscription` mode, everything is working fine. For testing purpose I set `allow_promotion_codes` to `False` and still got the error in `payment` mode. I expected, that when setting the option to `False`, the parameter is not passed. Is this a bug or an expected behavior?

Thank you :)

**Comment by remi-stripe** [comment]
@fabianriewe At the moment, promotion codes only work with Subscriptions though we're working on making them work with payment mode too. The parameter only works when you have `mode='subscription'` so you need to make sure you do not pass it in payment mode, even if passing false.
