### ISSUE TITLE
Feature request: Retrieving Promotion code from code value

### ISSUE THREAD

**Issue by Raduan77** [stripe/stripe-python#677]
Hey there!
I'm trying to implement the usage of Promotion codes for subscriptions via Stripe Checkout. [This](https://stripe.com/docs/api/checkout/sessions/create) is the API I'm using for creation of checkout and the field I'm using to provide info about coupon is `subscription_data.coupon`. I have to provide coupon id here.

This is how I'm getting this coupon id:
```python
promo_id = 'promo_...'
coupon_id = stripe.PromotionCode.retrieve(promo_id)['coupon']['id']
```

Stripe API requires me to pass the id of promotion code in order to get its object.
Is there a possibility to get a promotion code from the `code` value somehow?
Because otherwise, it seems like my system should know all the possible promotion codes and map them to their ids.

**Comment by remi-stripe** [comment]
@Raduan77 Thanks for reaching out! Github issues should be limited to bugs with the stripe-python library. Your question is more a product question instead so we recommend that you reach out to our support team directly for help on questions like this. You can contact them here: https://support.stripe.com/contact

Just to answer your question though, we do expect the coupon id in this parameter and we don't plan to support the `code`. The `code` property is a customer-facing version that would be entered when the customer pays in Checkout with the value you would have sent them. In the API, we expect the exact coupon id instead.
