### ISSUE TITLE
Topup.create does not have keyword argument for metadata

### ISSUE THREAD

**Issue by alexwong98** [stripe/stripe-python#685]
There is no keyword argument for `metadata` when creating a Topup using `stripe.Topup.create()`, even though it is suggested by documentation that it is possible: https://stripe.com/docs/api/topups/create#create_topup-metadata

I'm getting this error: 
```
create() got an unexpected keyword argument 'metadata'
```

**Comment by remi-stripe** [comment]
@alexwong98 I've tried to reproduce locally with the latest stripe-python but I don't get an error when I pass metadata with the following code and the request reaches Stripe as expected:

```
topup = stripe.Topup.create(
  amount=2000,
  currency="usd",
  description="Top-up for Jenny Rosen",
  statement_descriptor="Top-up",
  metadata={
    "key1": "value1",
  },
)
```

Would you be able to provide a bit more details such as the exact version of stripe-python you are using and some simple code to reproduce the exact error you get?

**Comment by alexwong98** [comment]
I'm using stripe-python version `2.55.0`. 

This is my code:
```
        stripe.api_key = settings.STRIPE["API_KEY"]

        try:
            topup = stripe.Topup.create(
                amount=amount_cents,
                currency=currency,
                description=description,
                destination_balance="issuing",
                source=self.stripe_source_token,
                stripe_account=self.business.stripe_account_id,
                metadata={
                    "key1":"value1"
                }
            )
...
```

**Comment by ob-stripe** [comment]
Very strange, the `create` method should accept any keyword argument and thus should never throw "got an unexpected keyword argument".

There is probably something in your code that redefines or overrides the default `create` method from the `stripe` module somehow. Can you try the following and share the output?

```python
import inspect
import stripe
print(inspect.signature(stripe.Topup.create))
```

The expected output is:
```
(api_key=None, idempotency_key=None, stripe_version=None, stripe_account=None, **params)
```

**Comment by alexwong98** [comment]
You are correct in suggesting something was overriding the create method. There is no issue with the package. Thank you, closing this out now.
