### ISSUE TITLE
Default card for customer is not set

### ISSUE THREAD

**Issue by ritikbhatia** [stripe/stripe-python#690]
I am trying out the stripe-python library and using `stripe 2.55.0` for the same. My Python version is `3.7.7`

In a trial script, I am creating a customer first, using `stripe.Customer.create`, followed by creating a card using `stripe.Customer.create_source` and passing it the `id` of the customer created earlier.

The API docs [here](https://stripe.com/docs/api/cards/create) for card creation mention the following:
_If the card’s owner has no default card, then the new card will become the default. However, if the owner already has a default, then it will not change. To change the default, you should update the customer to have a new default_source._

However, when I print the default source for the customer using `print(customer["default_source"])`, it returns `None`. The card is set as default only if I use the command `stripe.Customer.modify` and pass it the card id as the `default_source` attribute.

Since this may be confusing at first (even if it is handled properly elsewhere), could either the API docs be changed to inform that the user will have to explicitly run `stripe.Customer.modify` the **first** time to set the default card OR a change could be made in the implementation of `stripe.Customer.create_source` to handle this situation in order to be consistent with the docs?

Could be an understanding issue from my end but just wanted to give my view as a user to contribute in maintaining the amazing standard of Stripe's libraries :)

**Comment by remi-stripe** [comment]
@ritikbhatia When you call `create_source`, this call will **not** update the `customer` variable that you have locally in your script. You would have to retrieve the customer again to find an updated version that would have `default_source` set as expected. It can definitely be confusing when approaching it for the first time with our Python library (or any of our libraries). That's in part why we're moving away from a model where you call methods on variables themselves and instead prefer a client/service model where you call static methods and don't expect local variables/instances to refresh automatically.

Also, I wanted to flag that using `create_source`, `default_source` and such are considered legacy. We built a new API called the PaymentMethod API, in mid 2018 and this is the new canonical integration that we recommend all new integrations rely on. You should steer clear from `Token` and `Card` or `Source` objects and use `PaymentIntent` and `PaymentMethod` directly. This is the best guide to get started: https://stripe.com/docs/payments/accept-a-payment

I hope this helps!

**Comment by ritikbhatia** [comment]
Hi @remi-stripe !
Thanks for the detailed explanation. It has indeed helped provide a lot of clarification! Will move work with the newer APIs now :)
