### ISSUE TITLE
gpg signature on pypi is done by an expired key

### ISSUE THREAD

**Issue by mapreri** [stripe/stripe-python#692]
Hi,

I was trying to validate the archive on pypi, but it seems to be coming from an expired key:

```
% gpg --verify stripe-2.55.0.tar.gz.asc
gpg: assuming signed data in 'stripe-2.55.0.tar.gz'
gpg: Signature made Wed 14 Oct 2020 04:55:20 PM CEST
gpg:                using RSA key C33033E4B583FE612EDE877C05D02D3D57ABFF46
gpg: Can't check signature: No public key
% gpg --recv-keys --keyserver keyserver.ubuntu.com C33033E4B583FE612EDE877C05D02D3D57ABFF46
gpg: key 0x05D02D3D57ABFF46: 13 signatures not checked due to missing keys
gpg: key 0x05D02D3D57ABFF46: public key "Stripe <support@stripe.com>" imported
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  53  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  52  signed: 510  trust: 52-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2020-12-08
gpg: Total number processed: 1
gpg:               imported: 1
% gpg --verify stripe-2.55.0.tar.gz.asc                                                    
gpg: assuming signed data in 'stripe-2.55.0.tar.gz'
gpg: Signature made Wed 14 Oct 2020 04:55:20 PM CEST
gpg:                using RSA key C33033E4B583FE612EDE877C05D02D3D57ABFF46
gpg: Good signature from "Stripe <support@stripe.com>" [expired]
gpg:                 aka "Stripe <security@stripe.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: C330 33E4 B583 FE61 2EDE  877C 05D0 2D3D 57AB FF46
% gpg -k C33033E4B583FE612EDE877C05D02D3D57ABFF46
pub   rsa2048/0x05D02D3D57ABFF46 2011-01-09 [SC] [expired: 2018-09-06]
      C33033E4B583FE612EDE877C05D02D3D57ABFF46
uid                   [ expired] Stripe <support@stripe.com>
uid                   [ expired] Stripe <security@stripe.com>
```

Could you please either rotate the signing key, or bump the expiry date?  In fact, I'm surprised to see a recent release signed by such long-expired key, as I thought gpg refused to use expired keys to sign stuff.  Perhaps the updated key was not pushed to the keyservers?  FTR, I also tried looking for it on pool.sks-keyservers.net and keys.openpgp.org, with no luck in either keyserver.

Thank you for duly signing your releases!

**Comment by remi-stripe** [comment]
@mapreri Thanks for reporting this! I'll have the team look and see what we need to do to fix the signature!

**Comment by joek-stripe** [comment]
Hi @mapreri, 

Thank you for reporting this to us. 

> Perhaps the updated key was not pushed to the keyservers?

From what I can tell this looks to be the case, we'll be improving our processes to ensure that does not happen again.

As per https://www.gnupg.org/gph/en/manual/x457.html, the other keyservers should synchronize themselves eventually, but the one I pushed to was keyserver.ubuntu.com. 

If you run your checks again you'll see that the expiry has been removed from the SC subkey (`05D02D3D57ABFF46`), however you will encounter the more common warning such as: 
```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```
to address this trust anchor, the best approach I can think of is displaying the key fingerprint on a page on our root domain so that users of our SDKs can review those and then mark the key as trusted locally. 
This is the case with our security and data-migration keys:
- https://stripe.com/docs/security/pgp-key
- https://stripe.com/docs/security/pgp-migration-key

Thanks! 
Joe

**Comment by mapreri** [comment]
Hi @joek-stripe thank you for handling this!

> As per https://www.gnupg.org/gph/en/manual/x457.html, the other keyservers should synchronize themselves eventually, but the one I pushed to was keyserver.ubuntu.com.

Unfortunately, the situation is a tad more dire than it should be.  A couple of years ago somebody successfully figured out a way to permanently damage the SKS network (by spamming keys with additional certifications), and since then there have been quite a few issues.  I recommend you also push the key to https://keys.openpgp.org/ - that is a a kind of newer SKS implementation, where people need to verify their UIDs and don't allow for extra certifications to be pushed, preventing that kind of spamming attack.

Either way, I successfully retrieved the key and successfully verified the tarball, thank you!

> however you will encounter the more common warning such as:
> ```
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> ```

That's a very normal thing to see! :) To any slightly-more-than-average gpg user they will understand what's that about ;)

> the best approach I can think of is displaying the key fingerprint on a page on our root domain so that users of our SDKs can review those and then mark the key as trusted locally.
> This is the case with our security and data-migration keys:

Yes, that's one way about it indeed.

BTW, there are also these two "new" things related to attributing trusting anchors to gpg keys that you might wish to consider:
 * WKD: https://wiki.gnupg.org/WKD
 * RFC 7929, aka OPENPGPKEY records in DNS
Neither of these are actually used by anything TTBOMK, but at some point some clients might appear and/or gnupg itself might become slightly more clever with a different idea of "trust".


Again, thank you, I'm closing this issue since I'm satisfied with what you did already! :)

**Comment by joek-stripe** [comment]
@mapreri thanks for the WKD, DANE links and clarification on key synchronization (or lack thereof), I'll push the update to a couple of mirrors today to cover our bases!
