### ISSUE TITLE
Is /v1/payment_pages undocumented ?

### ISSUE THREAD

**Issue by FabriceSalvaire** [stripe/stripe-python#693]
From **strip-cli** `triggers/checkout.session.completed.json`

```
{
  "_meta": {
    "template_version": 0
  },
  "fixtures": [
    {
      "name": "checkout_session",
      "path": "/v1/checkout/sessions",
      "method": "post",
      "params": {
        "success_url": "https://httpbin.org/post",
        "cancel_url": "https://httpbin.org/post",
        "payment_method_types": ["card"],
        "line_items": [
          {
            "name": "t-shirt",
            "description": "comfortable cotton t-shirt",
            "amount": 1500,
            "currency": "usd",
            "quantity": 2
          }
        ],
        "payment_intent_data": {
          "shipping": {
            "name": "Jenny Rosen",
            "address": {
              "line1": "510 Townsend St",
              "postal_code": "94103",
              "city": "San Francisco",
              "state": "CA",
              "country": "US"
            }
          }
        }
      }
    },
    {
      "name": "payment_page",
      "path": "/v1/payment_pages",
      "method": "get",
      "params": {
        "session_id": "${checkout_session:id}"
      }
    },
    {
      "name": "payment_method",
      "path": "/v1/payment_methods",
      "method": "post",
      "params": {
        "type": "card",
        "card": {
          "token": "tok_visa"
        },
        "billing_details": {
          "email": "stripe@example.com"
        }
      }
    },
    {
      "name": "payment_page_confirm",
      "path": "/v1/payment_pages/${payment_page:id}/confirm",
      "method": "post",
      "params": {
        "payment_method": "${payment_method:id}"
      }
    }
  ]
}
```

**Comment by remi-stripe** [comment]
@FabriceSalvaire This API is internal to Stripe and helps power Checkout's UI. This is now a public API and you can not interact with it directly except via the CLI. We use that API to simulate the successful completion of a Checkout Session in the CLI to help developers write webhook handlers more easily!

I'm going to close this out as it's not something we will make public but let me know if you have any follow up questions!

**Comment by sripalli1** [comment]
Hi Remi, How can we fetch the promotion code that customer has entered on payment screen? As of now, I see only  /v1/payment_pages endpoint providing these details. Not sure why Checkout Session object doesnt store the Promotion code entered on the payment screen. Do you hvae any info on this?

**Comment by remi-stripe** [comment]
@sripalli1 Please reach out to our support team for help instead and they can sort you out! https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
@Archie818 Please work with our support team for 1:1 help: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
@Shrutipandya this is an integration support question. Please work with our support team for 1:1 support help: https://support.stripe.com/contact
