### ISSUE TITLE
Intermittent customer.subscription.updated event attributes access

### ISSUE THREAD

**Issue by trovafer** [stripe/stripe-python#697]
Python version: 3.8.5
Stripe lib version: 2.55.0

This is happening to me only with **customer.subscription.updated** event.

```
event = stripe.Webhook.construct_event(
                payload=request.data, sig_header=signature, secret=STRIPE_WEBHOOK_SECRET)

subscription = event.data.object

(Pdb) type(subscription.plan)
<class 'stripe.api_resources.plan.Plan'>
(Pdb) type(subscription.plan)
<class 'NoneType'>
(Pdb) type(subscription.id)
<class 'str'>
(Pdb) type(subscription.plan)
<class 'NoneType'>
(Pdb) type(subscription.plan)
<class 'stripe.api_resources.plan.Plan'>
(Pdb) type(subscription.plan.product)
(Pdb) *** AttributeError: 'NoneType' object has no attribute 'product'
(Pdb) type(subscription.plan.product)
<class 'str'>
```

The first time I access any nested attribute, it works.. the next, no matter which one, it fails. And it keeps going like that.

**Comment by ob-stripe** [comment]
Hi @trovafer. Very strange issue indeed!

Can you try reproducing using `event = stripe.Event.construct_from(data, 'sk_test_123')`? And try with a minimal payload?

E.g. on my machine, this works:

```python
>>> event = stripe.Event.construct_from({'data': {'object': {'id': 'sub_123', 'object': 'subscription'}}}, 'sk_test_123')

>>> subscription = event.data.object

>>> type(subscription.id)
<class 'str'>

>>> type(subscription.id)
<class 'str'>
```

**Comment by trovafer** [comment]
I don't know what to say. I tried your code and worked, so I went back to my service to reproduce the error and send you more information but it is not happening anymore.

I'm not sure if it was a very particular scenario or what but I guess I will rollback my workaround and get back here with more information if it happens again (hopefully not)

**Comment by ob-stripe** [comment]
Weird! Going to close the issue for now, but feel free to reply if you observe the issue again and we'll reopen and investigate.
