### ISSUE TITLE
Subscription per-seats model for Customer Portal

### ISSUE THREAD

**Issue by kompotkot** [stripe/stripe-python#702]
Hello, I wonder of possibility to control subscription user seats at customer portal. 

As I understand right now according with documentation [Stripe Customer Portal](https://stripe.com/docs/billing/subscriptions/customer-portal) there is no possibility to modify quantity of seats if I set product as `unit_label="seat"` and price as `billing_scheme="tiered", tiers_mode="volume"`. Customer portal allow me to modify billing address, payment information and cancel/renew subscription only.

I found only one way to modify seats described at [Stripe per-seat](https://stripe.com/docs/billing/subscriptions/per-seat). But even if I merge this approach with Stripe Checkout, I still required to handle manually 3D Secure verification steps at frontend side, when I modify purchased seat for subscription and create Invoices. 

Has the Stripe team considered seats support for Customer Portal?

**Comment by remi-stripe** [comment]
@kompotkot Thanks for reaching out! Github issues should be limited to bugs or issues with the stripe-python library itself and not for feature requests on the API at the moment. Based on your question, I recommend reaching out to our support team directly to register your interest for that feature: https://support.stripe.com/contact 

In the meantime, you're correct that the only solution is to handle upgrades and 3D Secure with Elements for now.
