### ISSUE TITLE
Receiving intermitent issues with the hosted_page_url of a Connected Account invoice

### ISSUE THREAD

**Issue by drulang** [stripe/stripe-python#705]
Python 3.7
Package Version : 2.44.0

We have about 155 connected accounts that we send invoices on behalf of.  Our implementation has been find for about 8 months now, however yesterday we started getting this error for some of the hosted invoices we create.  This does not affect all of our users, only some.

```Uncaught (in promise) UnexpectedError: This endpoint does not allow impersonation as a Connected Account.```

![image](https://user-images.githubusercontent.com/2532229/106774966-ab09fb00-6610-11eb-91fe-178afdb9abf7.png)

I've tried googling and do not see any mention of this particular error.  Also I'm not convinced this is an issue on our side because the API is allowing the creation of the invoices and we are using the correct `hosted_page_url`.  Any help would be greatly appreciated as this is very hard to debug.

**Comment by remi-stripe** [comment]
@drulang Just circling back, thanks a lot for the report, this was really helpful and it did help us pinpoint the issue internally and get it fixed so you shouldn't see the error anymore
