### ISSUE TITLE
Missing changelog for 2.52.0 and 2.53.0

### ISSUE THREAD

**Issue by gdvalderrama** [stripe/stripe-python#706]
The changelog message for versions 2.52.0 and 2.53.0 are missing.

They currently read:

> 2.53.0 - 2020-09-24
> #999 DESCRIBE CHANGES HERE (try to use the same style, tense, etc. as the other entries)
> 2.52.0 - 2020-09-24
> #999 DESCRIBE CHANGES HERE (try to use the same style, tense, etc. as the other entries)

**Comment by remi-stripe** [comment]
@gdvalderrama Thanks for raising! Those releases were a "no-op" on our end as they didn't contain any change. They were used to finalize our automated tooling for releases. The changelog is definitely confusing though so we'll fix it soon!

**Comment by richardm-stripe** [comment]
Fixed in master, thank you @gdvalderrama.
