### ISSUE TITLE
Async Sypport

### ISSUE THREAD

**Issue by awemulya** [stripe/stripe-python#715]
Any plan to support async calls.
I am using Uvicorn and stripe http calls are blocking.

`customers = await stripe.Customer.list()`

**Comment by remi-stripe** [comment]
@awemulya Thanks for reaching out! We have looked into this in the past and built some prototypes to understand what it would look like. We have plans to re-design the library entirely or ship an alternative async-first version in the future but it likely won't happen this year.

I'm going to close this ask in favour of https://github.com/stripe/stripe-python/issues/327 which is the canonical one. We haven't forgotten about it and we are definitely interested to ship this but it's in parallel to other work such as finishing codegen for stripe-go for example and adding client/services to existing libraries like stripe-java.

**Comment by SerGeRybakov** [comment]
Any updates on this?
