### ISSUE TITLE
[Subscriptions] How would I check if a user is currently subscribed to a price or had in the past?

### ISSUE THREAD

**Issue by smac89** [stripe/stripe-python#732]
This is currently how I am checking:

```python
def check_user_has_trialed_subscription(stripe_customer, stripe_price) -> bool:
    '''
    https://stripe.com/docs/billing/subscriptions/overview#subscription-statuses
    '''
    customer_subscriptions = stripe.Subscription.list(
        customer=stripe_customer.id,
        price=stripe_price.id,
        status="all"
    ).data

    return any(sub.status in ('active', 'trialing', 'canceled') or not (sub.trial_start is None) for sub in customer_subscriptions)
```

Is this good enough, or do I need more than this?

**Comment by remi-stripe** [comment]
@smac89 Github issues should be limited to bugs with the library itself. This is more an integration question and we recommend contacting our [support team](https://support.stripe.com/contact) or joining our Discord server to talk to other developers: https://stripe.com/go/developer-chat
