### ISSUE TITLE
[Feature request] Multiple shipping options when creating checkout session

### ISSUE THREAD

**Issue by josie-smith** [stripe/stripe-python#734]
I noticed that you only allow 1 shipping option to be sent through when creating a checkout session: https://stripe.com/docs/payments/checkout/shipping

It would be great if you were allowed to pass more through, so the customer can select their shipping option when they enter their payment details.

**Comment by remi-stripe** [comment]
@josie-smith Github issues should be limited to bugs with the stripe-python library itself. Your request is more an API feature, which you should report to our support team directly: https://support.stripe.com/contact

I'm going to close this out, hope it's okay
