### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [stripe/stripe-python#744]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/stripe/stripe_object.py b/stripe/stripe_object.py
index 8dbe49f..498b0ae 100644
--- a/stripe/stripe_object.py
+++ b/stripe/stripe_object.py
@@ -208,14 +208,14 @@ class StripeObject(dict):
         # updating a customer, where there is no persistent card
         # parameter.  Mark those values which don't persist as transient
         if partial:
-            self._unsaved_values = self._unsaved_values - set(values)
+            self._unsaved_values -= set(values)
         else:
             removed = set(self.keys()) - set(values)
-            self._transient_values = self._transient_values | removed
+            self._transient_values |= removed
             self._unsaved_values = set()
             self.clear()
 
-        self._transient_values = self._transient_values - set(values)
+        self._transient_values -= set(values)
 
         for k, v in six.iteritems(values):
             super(StripeObject, self).__setitem__(
```

**Comment by richardm-stripe** [comment]
Hello @elfring,

I see you have made this same comment across multiple open-source repos. Is there a compelling reason to make this change other than aesthetics?

I am closing this issue as I am not convinced it would help us or our users. Feel free to reopen if you want to detail a user benefit.

**Comment by elfring** [comment]
>Feel free to reopen if you want to detail a user benefit.

:thinking: Can you reopen this issue if you would like to take information (like the following) better into account?
* I find that [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13) can indicate also motivation for another bit of collateral evolution.
* The proposed software adjustment should influence run time characteristics of affected components in desirable directions.
  How do you think about measuring any differences?
