### ISSUE TITLE
cannot expire checkout session made for connected account

### ISSUE THREAD

**Issue by databasedav** [stripe/stripe-python#759]
python 3.9
stripe-python 2.6.3

```python
import stripe

cs = stripe.checkout.Session.create(
    mode='subscription',
    payment_method_types=['card'],
    line_items=[{
        'price_data': {
            'currency': 'usd',
            'product_data': {
                'name': 'test',
            },
            'unit_amount': 1000,
            'recurring': {
                'interval': 'month',
                'interval_count': 1
            }
        },
        'quantity': 1
    }],
    expires_at=int(time.time()) + 60*70,
    subscription_data={
        'application_fee_percent': 15
    },
    success_url='http://localhost',
    cancel_url='http://localhost',
    stripe_account=TEST_STRIPE_ACCOUNT_ID,
)
stripe.checkout.Session.expire(cs.id, stripe_account=TEST_STRIPE_ACCOUNT_ID)
```
the `.expire` fails with
```
stripe.error.InvalidRequestError: Request req_KrBIQGGmx9R6NI: This endpoint does not allow impersonation as a Connected Account.
```
this might be an issue with the api itself, since creating checkout sessions for connected accounts work fine (and is well documented in the Connect docs), is disallowing expiring for connected accounts intended?

**Comment by remi-stripe** [comment]
@databasedav Thanks for the report, this definitely should work so I've reported it internally. It's not a bug with stripe-python itself so I'm going to close and I recommend that you report it to our support team directly too: https://support.stripe.com/contact but I'll make sure we fix it soon!

**Comment by remi-stripe** [comment]
Circling back that the issue has been fixed and you should be able to expire a Checkout Session on a connected account now!
