### ISSUE TITLE
Documentation link on Pypi is broken (Project Links -> Documentation)

### ISSUE THREAD

**Issue by banagale** [stripe/stripe-python#760]
[Stripe on Pypi](https://pypi.org/project/stripe/2.64.0/)

Currently links to https://stripe.com/docs/api/python which is a 404.

It appears that it should be https://stripe.com/docs/api?lang=python

<img width="429" alt="Screen Shot 2022-01-05 at 7 08 32 PM" src="https://user-images.githubusercontent.com/1409710/148322106-dbc69b04-478c-40e0-bee7-f78594a1ece6.png">

**Comment by richardm-stripe** [comment]
Hello @banagale, thanks for the report
This should be fixed by https://github.com/stripe/stripe-python/pull/758 on the next stripe-python release, which I expect to happen in the next two weeks.

**Comment by banagale** [comment]
@richardm-stripe Thanks for the note, Richard, you are welcome. 

I hope you have a great week.
