### ISSUE TITLE
What's your 2.7 support  plan?

### ISSUE THREAD

**Issue by joe-narvaez** [stripe/stripe-python#762]
Hello, 
I googled this and I couldn't find anything.   Apologies if it was right in front of me.  I've inherited a python 2.7 with stripe 2.10 project.  I've got two main questions. 

1. Generally, what would be my best strategy here? migrate to python3?  stay on 2?   Bump stripe to latest?

2. I'm trying to access `stripe.checkout` and its telling me `stripe has no attribute called checkout`. I printed `dir(stripe)` and did not see `checkout` on that list, but there were other stripe modules `Account, AliPayAccount, ...`.  I got it to work with python3.  What could possibly be the cause of this? 

Thank you for such an awesome library. 

-------------
Edit: Punctuation

**Comment by richardm-stripe** [comment]
Hello @joe-narvaez. Python 2.7 is still supported by the latest version of `stripe-python` - 2.64.0, which will have `stripe.checkout`. 

Please upgrade to Python 3 if you can. Python 2.7 is two years past its end of life. Stripe hasn't yet established an official policy for supporting runtimes past their end-of-life, but we do deprecate them, especially when continued support limits us from improving the library for users of more modern runtimes.

**Comment by richardm-stripe** [comment]
Closing because I hope this answers your question. Feel free to comment again or re-open if you need more information.
