### ISSUE TITLE
Search API support

### ISSUE THREAD

**Issue by jleclanche** [stripe/stripe-python#772]
I understand the stripe-python package does not support the [Search API](https://stripe.com/docs/search-api) yet. 

It'd be a really nice addition. Is it not planned at all?

**Comment by remi-stripe** [comment]
@jleclanche our client libraries don't support beta features. If they did, we wouldn't be able to make changes to the API while in beta since it'd be a breaking change for all users of the package. Once the API is released publicly, all client libraries will support the Search API automatically!

**Comment by remi-stripe** [comment]
Search is not in beta anymore and went public in [March](https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#2690---2022-03-29). The Search API is a bit special as it has its own logic for pagination so we needed a resource to represent the result from a Search API on various objects.
