### ISSUE TITLE
[Design] custom_method usage query

### ISSUE THREAD

**Issue by capitalfact** [stripe/stripe-python#779]
I'm fascinated by the APIRequestor layout and trying to understand the usage of [stripe.api_resources.abstract.custom_method](https://github.com/stripe/stripe-python/blob/master/stripe/api_resources/abstract/custom_method.py).

Appreciate this is auto-generated from OpenAPI but for better understanding, why in [stripe.api_resources.charge](https://github.com/stripe/stripe-python/blob/master/stripe/api_resources/charge.py) do you not decorate/create a custom_method for refund?

```
@custom_method("capture", http_verb="post")
class Charge(
    CreateableAPIResource, ListableAPIResource, UpdateableAPIResource
):
    OBJECT_NAME = "charge"

    def capture(self, idempotency_key=None, **params):
        url = self.instance_url() + "/capture"
        headers = util.populate_headers(idempotency_key)
        self.refresh_from(self.request("post", url, params, headers))
        return self

    def refund(self, idempotency_key=None, **params):
        url = self.instance_url() + "/refund"
        headers = util.populate_headers(idempotency_key)
        self.refresh_from(self.request("post", url, params, headers))
        return self
```

**Comment by richardm-stripe** [comment]
(Closing this, as I think this should answer your question and I don't think we are going to take action to resolve the inconsistency)

**Comment by capitalfact** [comment]
Thank you Richard for taking the time to respond. Much appreciated.
