### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by Axomme87** [stripe/stripe-python#780]
Hello, I've recently upgraded my stripe library version to the latest v2.67.0 and after checking my app I saw all the stripe related endpoints failing. Checking my AWS Lambda CloudWatch logs I got this message:
`cannot import name 'test_helpers' from 'stripe.api_resources'`
While investigating the stripe library in my python environment's site-packages and checking all the imports of the stripe.api_resources I also found other 2 that seem to have import problems according to my PyCharm IDE saying it doesn't find their reference. Below I'm posting the all those that look like to have import issues in the stripe.api_resources __init__ file:
`from stripe.api_resources import test_helpers`
`from stripe.api_resources.payment_link import PaymentLink`
`from stripe.api_resources.shipping_rate import ShippingRate`

**Comment by remi-stripe** [comment]
@Axomme87 those are recent additions to the stripe-python library. Are you sure you properly upgraded on your server and don't use a cached version of the library that doesn't have those?

**Comment by ramya-stripe** [comment]
@Axomme87 We hope that properly upgrading the stripe-python library like @remi-stripe suggested above has resolved the failures you were seeing. Since we did not hear back from you in a while, we are closing this issue.
