### ISSUE TITLE
An expired stripe checkout session for connect account does not retain the `stripe_account` parameter

### ISSUE THREAD

**Issue by smac89** [stripe/stripe-python#817]
### Describe the bug

I generated a checkout session using the following code:

```py
stripe.checkout.Session.create(
    stripe_account=connect_account.stripe_acc_id,
    success_url=success_url,
    cancel_url=cancel_url,
    mode="payment",
    customer_email=customer_email,
    submit_type="pay",
    payment_intent_data=dict(
        application_fee_amount=(app_fee.to_integral_value() if app_fee else None),
        setup_future_usage="off_session",
        description=transaction_description if transaction_description else "Payment for services",
    ),
    line_items=[
        {
            "price_data": {
                "unit_amount_decimal": unit_cost,
                "product": product.product_id,
                "currency": connect_account.default_currency,
            },
            "quantity": unit_count,
            "adjustable_quantity": {"enabled": False},
        }
    ],
    # purchase recovery...
    expires_at=int((datetime.now() + timedelta(hours=1)).timestamp()),
    after_expiration={
        "recovery": {
            "enabled": True,
        },
    },
)
```

After the checkout session expired, I found the event in stripe's dashboard and I tried using the `after_expiration.recovery.url` link to create a new session, only to be met with an error:

![image](https://user-images.githubusercontent.com/8305511/171060075-13f25019-7b6b-4208-ad1e-c04e5e594af0.png)

Upon checking devtools in FF, I see the following 400 error:
```json
{
  "error": {
    "code": "parameter_missing",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-missing",
    "message": "Can only apply an application_fee_amount when the PaymentIntent is attempting a direct payment (using an OAuth key or Stripe-Account header) or destination payment (using `transfer_data[destination]`).",
    "param": "application_fee_amount",
    "type": "invalid_request_error"
  }
}
``` 

### To Reproduce

1. Create a new checkout session for a connect account, with an recovery enabled (See [docs](https://stripe.com/docs/payments/checkout/abandoned-carts#configure-recovery))
2. Wait until the session expires, then attempt to use the recovery link shown
3. The resulting checkout page shows an error

### Expected behavior

The new checkout session should retain the same parameters as the original (including `stripe_account` parameter)

### OS

Linux

### Language version

Python 3.8

### Library version

stripe-python v2.65.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@smac89 Thanks for the report. I'd recommend flagging with our support team directly instead though as this is not a bug with the stripe-python library itself. You can contact them at https://support.stripe.com/contact I'll flag on my end too!

**Comment by remi-stripe** [comment]
@smac89 Just wanted to circle back on this as we were finally able to track down the issue and push a fix so those URLs should now work as expected moving forward

**Comment by smac89** [comment]
Just wanted to report that it is indeed working now.
Thanks
