### ISSUE TITLE
cannot create test clocks for connected accounts

### ISSUE THREAD

**Issue by databasedav** [stripe/stripe-python#819]
### Describe the bug

cannot create test clocks for connected accounts, which i would expect to be able to do to test recurring subscription payments on a connected account

### To Reproduce

```
import time
import stripe

stripe.api_key = ...
TEST_STRIPE_ACCOUNT_ID = ...
clock = stripe.test_helpers.TestClock.create(frozen_time=int(time.time()), stripe_account=TEST_STRIPE_ACCOUNT_ID)
```
```
stripe.error.InvalidRequestError: Request req_On772LGSOa0RHJ: Connected account impersonation is not allowed on this endpoint.
```

### Expected behavior

test clock successfully created on the connected account, whose id can then be passed to customer creation on behalf of test connected account

### OS

ubuntu 22.04

### Language version

python 3.9.13

### Library version

stripe-python 3.2.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
Thanks for the report @databasedav! This isn't a bug with the stripe-python library though and just a limitation of the API today. I'm going to flag internally as I agree it should work but I'm going to close this issue out. I'd recommend contacting our support team too to raise the issue: https://support.stripe.com/contact
