### ISSUE TITLE
Metadata for line_items

### ISSUE THREAD

**Issue by Artucuno** [stripe/stripe-python#852]
### Is your feature request related to a problem? Please describe.

I'm surprised that the Stripe API doesn't have metadata for line items. Adding metadata to line items would be a great feature and will save me **alot** of time and stress.

### Describe the solution you'd like

```py
            {
            'amount': '100',
            'currency': 'AUD',
            'quantity': 1,
            'name': 'test',
            'description': 'yes',
            'images': [None],
            'metadata': {'item_num': 0}
            }
```
and
```py
            {
            'quantity': 1,
            'metadata': {'item_num': 0},
            'price_data': {
                'recurring': {"interval": "month"},
                'unit_amount': '100',
                'currency': 'AUD',
                'product_data': {
                    'name': 'test',
                    'description': 'yes',
                    'images': [None],
                },
            },
            }
```

### Describe alternatives you've considered

Using the checkout metadata, but when I use lists it shows:
`stripe.error.InvalidRequestError: Request req_xxxx: Invalid value type: {:"0"=>"My Product", :"1"=>"default", :"2"=>"0"} must be a string`

### Additional context

Thanks!

**Comment by remi-stripe** [comment]
@Artucuno Github issues are limited to bugs with the library itself and this isn't really a bug. Feature requests are better directed to our support team which you can contact here: https://support.stripe.com/contact

To unblock you, we don't plan to support LineItem specific metadata. In your second example, you can already set `metadata` in `price_data` and/or inside `product_data` where you're doing a dynamic/ad-hoc price for that LineItem which fits the same purpose. But reporting the feature request to our support team is your best path forward.
