### ISSUE TITLE
Debugging webhook signature verification failures

### ISSUE THREAD

**Issue by accountForIssues** [stripe/stripe-python#857]
### Describe the bug

I'm trying to integrate stripe webhooks into our FastAPI. The related code is given below.

I keep getting signature verification exceptions over and over again.

The same code works on localhost and on my laptop but when I deploy it on the server with our API, it fails.

I dumped the payload, headers, secrets and compared them the ones on my laptop and they are identical (besides the usual times and request ids)

As I use docker, I thought it was that but the same Dockerfile image works on my laptop but not on the server. I have no idea why it is failing and how do I debug or solve this ?

### To Reproduce

Run the above code on a server (?) and trigger an event via Stripe CLI.

### Expected behavior

The signature is verified.

### Code snippets

```Python
from fastapi import Request, Response, FastAPI
import stripe
import traceback

api = FastAPI()

@api.post("/api/internal/webhook/")
async def return_response(request: Request):
    try:
        stripe.api_key = "sk_test_"
        endpoint_secret = (
            "whsec_"
        )
        event = None
        payload = await request.body()
        sig_header = request.headers["stripe-signature"]

        try:
            event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
        except ValueError as e:
            # Invalid payload
            raise e
        except stripe.error.SignatureVerificationError as e:
            # Invalid signature
            raise e

        # Handle the event    # Handle the event
        if event["type"] == "customer.subscription.updated":
            subscription = event["data"]["object"]

        # ... handle other event types
        else:
            print("Unhandled event type {}".format(event["type"]))
        return Response("", status_code=201)
    except:
        traceback.print_exc()
```
```


### OS

Ubuntu 22.04

### Language version

Python 3.10.5

### Library version

stripe-python 4.0.2

### API version

2022-08-01

### Additional context

_No response_

**Comment by remi-stripe** [comment]
@accountForIssues Github issues are limited to bugs with the library itself. This is not a bug with the library and is more an integration help question better directed at our support team instead: https://support.stripe.com/contact/email
You can also talk to developers on our Discord server: https://stripe.com/go/developer-chat
