### ISSUE TITLE
v4.2.0 is not on PyPI.

### ISSUE THREAD

**Issue by bhch** [stripe/stripe-python#880]
### Describe the bug

Latest release [v4.2.0](https://github.com/stripe/stripe-python/releases/tag/v4.2.0) is not on PyPI ([see available releases](https://pypi.org/project/stripe/#history)).

Probably due to the publish action failure: https://github.com/stripe/stripe-python/actions/runs/3113621642/jobs/5048575324

### To Reproduce

Try `pip install stripe==4.2.0`

### Expected behavior

Should be able to install stripe==4.2.0

### OS

Ubuntu

### Language version

Python 3.8

### Library version

v4.2.0

### API version

2022-08-01

**Comment by pakrym-stripe** [comment]
Thank you for the report. Somehow I managed to miss the failure notification. 

4.2.0 is out.
