### ISSUE TITLE
CreditNote not searchable?

### ISSUE THREAD

**Issue by dannywillems** [stripe/stripe-python#896]
### Is your feature request related to a problem? Please describe.

Looks like CreditNote is not searchable. Is there any reason?

### Describe the solution you'd like

CreditNote should be Searchable

**Comment by remi-stripe** [comment]
@dannywillems Github issues should be limited to bugs with the library itself. Your ask is more a feature request for our API which you should report to our support team directly: https://support.stripe.com/contact
