### ISSUE TITLE
Feature Request: Renaming of each price object within a product for invoices

### ISSUE THREAD

**Issue by gjegoh** [stripe/stripe-python#911]
### Is your feature request related to a problem? Please describe.

When implementing Usage-based billing for a subscription-based product with multiple overage costs, namely a product with a base price object and two price objects to track usage records for 2 different overages, the invoice becomes difficult to read given that the name of each invoice item line will follow the product's name.

### Describe the solution you'd like

Feature to rename the price objects such that it'll reflect accordingly on the invoice, for example I want to rename the base price object to be Plan Price and price objects to track usage records to be Overages 1/Overages 2, allowing the user to be able to easily determine what each invoice line item refers to.

**Comment by richardm-stripe** [comment]
Hello @gjegoh,

Thanks for writing in! This repository is for issues and feature requests with the stripe-python library itself; whereas your feature request is for the broader Stripe API and Stripe Billing product itself. The best way to make a feature request is through a support ticket at https://support.stripe.com/contact/login

I will try and forward this appropriately internally. We do appreciate you writing in! I am closing the ticket here as it's not something we can fix/should track in stripe-python.
