### ISSUE TITLE
When creating an empty draft invoice and the 'pending_invoice_items_behavior' is not explicitly set to 'exclude' the request fails.

### ISSUE THREAD

**Issue by FreshNar** [stripe/stripe-python#949]
Edit: formatting.

### Describe the bug

In reference to the [Create an invoice](https://stripe.com/docs/api/invoices/create) section of the Invoices API docs the pending_invoice_items_behavior parameter is said to default to 'exclude'. However, if you attempt to create a draft invoice using only the _customer_ parameter an "InvalidRequestError" is raised. 

### To Reproduce

To reproduce. [Run the code from the docs:](url)
```
import stripe
stripe.api_key = "sk_test_xxxx"

stripe.Invoice.create(
  customer="cus_xxxx",
)
```

or from the [Integration Guide](https://stripe.com/docs/invoicing/integration):
```
import stripe
stripe.api_key = "sk_test_xxxx"

stripe.Invoice.create(
  customer="cus_xxxx",
  collection_method="send_invoice",
  days_until_due=30,
)
```

The following error is raised: stripe.error.InvalidRequestError: Request req_iuQ6XucMWS7nyz: Nothing to invoice for customer

### Expected behavior

**The expected behavior is to create a draft invoice for the customer without any invoice items.**

Current workaround is to explicitly set the "pending_invoice_items_behavior" to "exclude":

```import stripe
stripe.api_key = "sk_test_xxxx"

stripe.Invoice.create(
  customer="cus_xxxx",
  pending_invoice_items_behavior="exclude",
)
```

### OS

Windows

### Language version

Python 3.11.0

### Library version

stripe-python 

### API version

2020-08-27

### Additional context

This is relevant regardless of the SDK/library used (cURL, PHP, etc..)

**Comment by remi-stripe** [comment]
Hey @FreshNar Github issues are limited to bugs with the library itself and this is more an integration question so if you have follow up questions I'd recommend talking to our support team directly for real time answers. You can contact them [here](https://support.stripe.com/contact)

To unblock you though I can explain what's causing this issue. The ability to create a draft Invoice without any line items was added in the API version [2022-08-01](https://stripe.com/docs/upgrades#2022-08-01). Before that you had to create an InvoiceItem first and then create the draft Invoice after that which would pull in that pending InvoiceItem into it.

The best option is to set the right API version in your code instead as documented [here](https://stripe.com/docs/api/versioning).
