### ISSUE TITLE
Error in netrc.py 

### ISSUE THREAD

**Issue by gjae** [stripe/stripe-python#957]
### Describe the bug

When start a checkout session , in response an error cause that  netrc.py should reloaded causing an error 502

### To Reproduce

```python
  s = self._client.checkout.Session.create(
      success_url=settings.SUCCESS_CHECKOUT_URL,
      line_items=[{"price": price_id, "quantity": qtty}],
      mode="payment",
      metadata=metadata,
      customer_email=customer_email,
      cancel_url=settings.FAIL_CHECKOUT_URL,
      payment_method_types=[
          "card",
      ]
  )
```

### Expected behavior

Get checkout url and return it to frontend

### OS

Ubuntu / Docker 

### Language version

Python 3.10

### Library version

stripe-python 5.3.0

### API version

2022-11-15

### Additional context

I'm using Django, the process is very simple , just create a price (if not exists) then creates a new checkout session and return the url to frontend

**Comment by pakrym-stripe** [comment]
Hi @gjae, can you please provide more details of the error you are seeing? The message and the stack trace will help.

**Comment by gjae** [comment]
> Hi @gjae, can you please provide more details of the error you are seeing? The message and the stack trace will help.

The only one message thtat I can see it's:
```bash
INFO 2023-04-13 15:09:24,238 util 3408 139857347208960 message='Request to Stripe api' method=post path=https://api.stripe.com/v1/products
 * Detected change in '/usr/local/lib/python3.10/netrc.py', reloading
 * Restarting with watchdog (inotify)
```

**Comment by gjae** [comment]
> This doesn't seem to be related to stripe SDK as we don't write any files especially python base library files.
> 
> I've found a few reports of unwanted flask reloads like https://stackoverflow.com/questions/67650294/prevent-flask-apps-development-server-from-unwanted-reloads.

Well, I'm using  Django with Docker (A project generated by Cookiecutter)

**Comment by pakrym-stripe** [comment]
Sorry, @gjae, without a small repro we can't diagnose the issue. I'm also quite confident it's not a bug in Stripe SDK as we don't write files on disk.

**Comment by gjae** [comment]
> Sorry, @gjae, without a small repro we can't diagnose the issue. I'm also quite confident it's not a bug in Stripe SDK as we don't write files on disk.

A dependency called "Watchdog" was the responsible, after removed it everything work fine. Thanks for support
